import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {dirname,join,extname} from 'node:path';
import {randomBytes} from 'node:crypto';
import {networkInterfaces} from 'node:os';
import {DungeonEngine} from './src/dungeon-engine.js';
import {Simulation} from './simulation.mjs';
import {MAPS} from './src/maps.js';
import {AGENTS} from './src/agents.js';
import {unlockedAgents} from './src/profile.js';
const root=dirname(fileURLToPath(import.meta.url));
export function localAddresses(port){try{return Object.values(networkInterfaces()).flat().filter(x=>x&&x.family==='IPv4'&&!x.internal).map(x=>'http://'+x.address+':'+port);}catch{return [];}}
function options(value={}){if(value.mode==='dungeon')return {mode:'dungeon',map:'duel',rounds:12,unlimited:false};const map=MAPS.find(m=>m.id===value.map);if(!map||!Number.isInteger(value.rounds)||value.rounds<1||value.rounds>99||typeof value.unlimited!=='boolean')throw Error('맵·라운드(1~99)·스킬 제한을 확인하세요.');return {map:map.id,rounds:value.rounds,unlimited:value.unlimited};}
export function createServer({publicOrigin=null,allowedOrigins=['capacitor://localhost','https://localhost','http://localhost','http://127.0.0.1:8787','http://localhost:8787']}={}){const rooms=new Map(),sessions=new Map();let last=performance.now(),acc=0,snapshotAt=0;
 const roomView=r=>({code:r.code,owner:r.owner,stage:r.stage,options:r.options,players:[...r.players.values()].map(({id,name,team,agent,ready,connected})=>({id,name,team,agent,ready,connected}))});
 const send=(p,data)=>{if(p.stream&&!p.stream.destroyed){if(p.stream.writableLength>1024*1024){p.stream.destroy();return;}p.stream.write('data: '+JSON.stringify(data)+'\n\n');}};
 const broadcast=r=>{const data={kind:'room',room:roomView(r)};for(const p of r.players.values())send(p,data);};
 function member(r,name,profile){if(r.options.mode==='dungeon'&&r.players.size>=4)throw Error('협동 던전 정원은 4명입니다.');const cap=MAPS.find(m=>m.id===r.options.map).size;const count=t=>[...r.players.values()].filter(p=>p.team===t).length;const team=r.options.mode==='dungeon'?'A':count('A')<=count('B')?'A':'B';if(r.options.mode!=='dungeon'&&count(team)>=cap)throw Error('방 정원이 찼습니다.');const owned=unlockedAgents(profile);const p={owned,id:randomBytes(6).toString('hex'),token:randomBytes(24).toString('hex'),name:String(name||'플레이어').trim().slice(0,20)||'플레이어',team,agent:null,ready:false,connected:true,stream:null,lastSeen:Date.now(),room:r};r.players.set(p.id,p);sessions.set(p.token,p);return p;}
 const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control','no-store');const json=(obj,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(obj));};try{
 const origin=req.headers.origin,allowed=origin&&(allowedOrigins.includes(origin)||origin===publicOrigin);if(allowed){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');}if(req.method==='OPTIONS'){res.writeHead(allowed?204:403);res.end();return;}
 if(url.pathname==='/api/info'){json({version:'0.7.2-beta.1',protocol:2,addresses:publicOrigin?[publicOrigin]:localAddresses(server.address().port)});return;}
 if(url.pathname==='/api/events'){const p=sessions.get(url.searchParams.get('token'));if(!p){json({error:'다시 방에 참가하세요.'},401);return;}if(p.stream)p.stream.end();p.connected=true;const actor=p.room.sim?.actors.get(p.id);if(actor)actor.connected=true;p.lastSeen=Date.now();p.stream=res;res.writeHead(200,{'Content-Type':'text/event-stream','Connection':'keep-alive','X-Accel-Buffering':'no'});res.write(': connected\n\n');send(p,{kind:'room',room:roomView(p.room)});if(p.room.sim)send(p,p.room.lastSnapshot||p.room.sim.snapshot());broadcast(p.room);req.on('close',()=>{if(p.stream===res){p.stream=null;p.lastSeen=Date.now();}});return;}
 if(url.pathname.startsWith('/api/')){if(req.method!=='POST'){json({error:'POST 요청이 필요합니다.'},405);return;}if(req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`&&req.headers.origin!==publicOrigin&&!allowed){json({error:'같은 게임 주소에서 접속하세요.'},403);return;}let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>32768){json({error:'요청이 너무 큽니다.'},413);return;}}let data;try{data=JSON.parse(raw||'{}');}catch{json({error:'잘못된 요청입니다.'},400);return;}
 if(url.pathname==='/api/create'){if(rooms.size>=20)throw Error('동시에 열 수 있는 방 수를 초과했습니다.');let code;do{code=randomBytes(3).toString('hex').toUpperCase();}while(rooms.has(code));const r={code,owner:null,stage:'setup',options:options(data.options),players:new Map(),sim:null};const p=member(r,data.name,data.profile);r.owner=p.id;rooms.set(code,r);json({id:p.id,token:p.token,room:roomView(r)});return;}
 if(url.pathname==='/api/join'){const r=rooms.get(String(data.code||'').toUpperCase());if(!r)throw Error('방 코드를 확인하세요.');if(r.stage!=='setup')throw Error('요원 선택 또는 대전 중인 방입니다. 방장이 대기실로 돌아온 뒤 참가하세요.');const p=member(r,data.name,data.profile);broadcast(r);json({id:p.id,token:p.token,room:roomView(r)});return;}
 const p=sessions.get(String(req.headers.authorization||'').replace(/^Bearer /,''));if(!p){json({error:'접속이 만료되었습니다. 다시 참가하세요.'},401);return;}const r=p.room;p.lastSeen=Date.now();
 if(url.pathname==='/api/poll'){p.connected=true;const actor=r.sim?.actors.get(p.id);if(actor)actor.connected=true;json({room:roomView(r),snapshot:r.lastSnapshot||null});return;}
 if(url.pathname==='/api/resume'){json({id:p.id,token:p.token,room:roomView(r)});return;}
 if(url.pathname==='/api/input'){p.connected=true;const actor=r.sim?.actors.get(p.id);if(actor)actor.connected=true;if(r.sim)r.sim.input(p.id,data);json({ok:true,room:roomView(r),snapshot:r.lastSnapshot||null});return;}
 if(url.pathname==='/api/leave'){p.stream?.end();r.sim?.disconnect(p.id);sessions.delete(p.token);if(r.sim){p.connected=false;}else r.players.delete(p.id);if(r.owner===p.id)r.owner=[...r.players.values()].find(q=>q.id!==p.id&&q.connected)?.id||null;if(![...r.players.values()].some(q=>q.connected)){rooms.delete(r.code);for(const q of r.players.values()){sessions.delete(q.token);q.stream?.end();}}else broadcast(r);json({ok:true});return;}
 if(url.pathname==='/api/profile'){if(r.stage==='match')throw Error('경기 중에는 해금 목록을 변경할 수 없습니다.');p.owned=unlockedAgents(data.profile);json({ok:true});return;}
 if(url.pathname==='/api/config'){if(p.id!==r.owner||r.stage!=='setup')throw Error('방장만 대기실 설정을 변경할 수 있습니다.');if(r.options.mode==='dungeon'||data.options?.mode==='dungeon')throw Error('던전의 진행 규칙은 고정입니다.');const o=options(data.options),cap=MAPS.find(m=>m.id===o.map).size;for(const t of ['A','B'])if([...r.players.values()].filter(x=>x.team===t).length>cap)throw Error('현재 팀 인원보다 작은 맵으로 변경할 수 없습니다.');r.options=o;}
 else if(url.pathname==='/api/team'){if(r.options.mode==='dungeon'||r.stage!=='setup'||!['A','B'].includes(data.team))throw Error('대기실에서 팀을 선택하세요.');const cap=MAPS.find(m=>m.id===r.options.map).size;if([...r.players.values()].filter(q=>q.id!==p.id&&q.team===data.team).length>=cap)throw Error('선택한 팀의 정원이 찼습니다.');p.team=data.team;}
 else if(url.pathname==='/api/select'){if(p.id!==r.owner||r.stage!=='setup')throw Error('방장만 게임을 시작할 수 있습니다.');if(r.options.mode!=='dungeon'&&[...r.players.values()].filter(p=>p.connected).length>1&&!['A','B'].every(t=>[...r.players.values()].some(p=>p.team===t&&p.connected)))throw Error('공격·수비 양 팀에 최소 1명씩 필요합니다.');r.stage='select';for(const q of r.players.values()){q.ready=false;q.agent=null;}}
 else if(url.pathname==='/api/ready'){if(r.stage!=='select'||!AGENTS.some(a=>a.id===data.agent))throw Error('요원을 선택하세요.');if(!p.owned.includes(data.agent))throw Error('아직 잠겨 있는 요원입니다. 첫 요원을 선택하거나 던전 보상으로 해금하세요.');p.agent=data.agent;p.ready=true;if([...r.players.values()].filter(q=>q.connected).every(q=>q.ready)){r.stage='match';r.sim=r.options.mode==='dungeon'?new DungeonEngine(r):new Simulation(r);}}
 else if(url.pathname==='/api/lobby'){if(p.id!==r.owner||r.sim&&r.sim.rules.phase!=='done')throw Error('경기 종료 후 방장이 대기실로 돌아갈 수 있습니다.');r.sim=null;r.lastSnapshot=null;r.stage='setup';for(const q of r.players.values()){if(!q.connected){r.players.delete(q.id);sessions.delete(q.token);}else{q.agent=null;q.ready=false;}}}
 else throw Error('알 수 없는 요청입니다.');broadcast(r);json({ok:true});return;
 }
 if(req.method!=='GET'){res.writeHead(405).end();return;}const route=url.pathname==='/'?'/index.html':url.pathname;const permitted=route==='/index.html'||/^\/src\/[a-zA-Z0-9._-]+\.(js|css)$/.test(route);if(!permitted){res.writeHead(404).end();return;}const bytes=await readFile(join(root,route));res.writeHead(200,{'Content-Type':({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'})[extname(route)]});res.end(bytes);
 }catch(error){if(!res.headersSent)json({error:error.code==='ENOENT'?'파일을 찾을 수 없습니다.':error.message},400);else res.end();}});
 const timer=setInterval(()=>{const now=performance.now();acc+=Math.min((now-last)/1000,.1);last=now;let steps=0;while(acc>=1/60&&steps++<6){for(const r of rooms.values())if(r.sim)r.sim.tick(1/60);acc-=1/60;}snapshotAt+=1;for(const r of rooms.values()){
 for(const p of r.players.values())if(!p.stream&&p.connected&&Date.now()-p.lastSeen>15000){p.connected=false;r.sim?.disconnect(p.id);if(!r.sim){r.players.delete(p.id);sessions.delete(p.token);if(r.stage==='select'){r.stage='setup';for(const q of r.players.values()){q.ready=false;q.agent=null;}}}if(r.owner===p.id)r.owner=[...r.players.values()].find(q=>q.connected)?.id||null;broadcast(r);}
 if(![...r.players.values()].some(p=>p.connected)){rooms.delete(r.code);for(const p of r.players.values())sessions.delete(p.token);continue;}
 if(r.sim&&snapshotAt%3===0){r.lastSnapshot=r.sim.snapshot();for(const p of r.players.values())send(p,r.lastSnapshot);}
 if(snapshotAt%300===0)for(const p of r.players.values())if(p.stream)p.stream.write(': heartbeat\n\n');
 }},1000/60);timer.unref();server.on('close',()=>{clearInterval(timer);for(const p of sessions.values())p.stream?.end();});return {server,rooms,sessions,setPublicOrigin(value){if(value===null){publicOrigin=null;return;}const u=new URL(value);if(u.protocol!=="https:"||u.origin!==value)throw Error("Invalid public origin");publicOrigin=value;}};}
if(process.argv[1]===fileURLToPath(import.meta.url)){const {server}=createServer();const port=Number(process.env.PORT)||8787;server.on('error',e=>{console.error('서버 시작 실패:',e.message);process.exitCode=1;});server.listen(port,'0.0.0.0',()=>{console.log('\n능력전선 LAN 0.7 BETA\n내 PC: http://localhost:'+port+'\n같은 네트워크의 친구에게 아래 주소를 알려주세요:');for(const address of localAddresses(port))console.log('  '+address);console.log('\n종료: Ctrl+C\n');});}
