import test from 'node:test';import assert from 'node:assert/strict';import {Simulation} from '../simulation.mjs';
function make(id,unlimited=false){const s=new Simulation({options:{map:'duel',rounds:4,unlimited},players:new Map([['a',{id:'a',team:'A',agent:id,connected:true}],['b',{id:'b',team:'B',agent:'arc',connected:true}]])});s.rules.phase='live';s.rules.time=100;return {s,a:s.actors.get('a')};}
const tick=(s,n)=>{for(let i=0;i<n;i++)s.tick(1/60);};
test('Spidey E jump heights are 2.55 and 3 while Space stays unchanged',()=>{const {a}=make('spidey');for(const [ultimate,height] of [[false,2.55],[true,3]]){a.transformed=ultimate;a.player.grounded=true;a.bank.fill();a.skill('E');assert(Math.abs(a.player.v.y**2/(2*22)-1.15*height)<1e-8);}a.transformed=false;a.player.grounded=true;a.jump(1);assert(Math.abs(a.player.v.y**2/(2*22)-1.15)<1e-8);});
test('Spidey regenerates 1 per second normally and 5 in ultimate, capped at max',()=>{const {s,a}=make('spidey');a.hp=60;tick(s,60);assert(Math.abs(a.hp-61)<.001);a.transformed=true;tick(s,60);assert(Math.abs(a.hp-66)<.001);a.hp=99;tick(s,60);assert.equal(a.hp,100);});
test('last Widow round holsters gun and next click becomes punch',()=>{const {a}=make('widow');a.bank.base[0]=0;a.bank.extra[0]=1;a.skill('Q');let shots=0,punches=0;a.shootRay=()=>shots++;a.melee=()=>punches++;a.attack(0);assert.equal(shots,1);assert.equal(a.equipped,null);a.attack(0);assert.equal(punches,1);});
test('Widow unlimited ammunition stays equipped, copied one-shot gun holsters',()=>{const {a}=make('widow',true);a.skill('Q');a.bank.extra[0]=0;a.attack(0);assert.equal(a.equipped,'gun');a.gunFree=true;a.attack(0);assert.equal(a.equipped,null);});
test('electric net stun halves while damage-over-time duration remains five seconds',()=>{const {a}=make('widow');a.skill('E');const p=a.projectiles[0];assert.equal(p.status.stun,2.5);assert.equal(p.status.dot,5);assert.equal(p.status.dotDamage,2);});
test('Pigeon release and cancel both enforce .7 seconds before punch',()=>{for(const cancel of [false,true]){const {s,a}=make('pigeon');a.skill('Q');if(cancel)s.input('a',{actions:[{type:'unequip'}]});else a.releaseCharge();assert.equal(a.charge,null);assert.equal(a.cool.punch,.7);a.attackAnim=0;a.attack(0);assert.equal(a.attackAnim,0);tick(s,41);a.attack(0);assert.equal(a.attackAnim,0);tick(s,2);a.attack(0);assert(a.attackAnim>0);}});
