import test from 'node:test';import assert from 'node:assert/strict';
// DOM contract harness: exercises the real client state/UI functions without a GPU.
const nodes=new Map(),context=new Proxy({measureText:()=>({width:50})},{get:(o,k)=>k in o?o[k]:()=>{}});
function element(){return {innerHTML:'',textContent:'',style:{setProperty(){}},classList:{toggle(){}},dataset:{},addEventListener(){},append(){},appendChild(){},insertAdjacentHTML(){},getContext:()=>context,querySelectorAll:()=>[],width:512,height:64};}
globalThis.document={querySelector:s=>{if(!nodes.has(s))nodes.set(s,element());return nodes.get(s);},querySelectorAll:()=>[],createElement:element,documentElement:element(),addEventListener(){},exitPointerLock(){}};
globalThis.window={addEventListener(){}};globalThis.innerWidth=1280;globalThis.innerHeight=720;
const T=await import('../src/three.module.js');const {Body,V}=await import('../src/physics.js');const {Game}=await import('../src/game.js');const {NetMatch}=await import('../src/lan-client.js');const {Simulation}=await import('../simulation.mjs');
test('client handles snapshots, HUD, deaths, spectator switching, walls, 70 ants and size menu',()=>{const room={options:{map:'squad',rounds:6,unlimited:false},players:new Map([['a',{id:'a',name:'Alice',team:'A',agent:'ant',connected:true}],['b',{id:'b',name:'Bob',team:'B',agent:'hera',connected:true}],['c',{id:'c',name:'Chris',team:'A',agent:'thor',connected:true}]])};const sim=new Simulation(room);sim.rules.phase='live';sim.rules.time=100;const g=Object.create(Game.prototype);Object.assign(g,{scene:new T.Scene(),camera:new T.PerspectiveCamera(78,16/9,.06,200),player:new Body(V(),V(.36,.9,.36)),preview:new T.Group(),arms:new T.Group(),effects:[],audio:{start(){},play(){}},sensitivity:.002,reset(){},updateHeldVisual(){},updateCamera(){},hud(){this.mapCtx=context;}});g.scene.add(g.camera);const lobby={g,identity:{id:'a'},room:{owner:'a'},api:async()=>({}),accept(){}};const net=new NetMatch(lobby,sim.snapshot());net.renderHud();assert(nodes.get('#agent-gauge').innerHTML.includes('일반'));const a=sim.actors.get('a');a.bank.fill();a.skill('C');net.receive(sim.snapshot());assert.equal(net.instances.ants.count,70);a.skill('E');net.receive(sim.snapshot());assert(nodes.get('#net-overlay').innerHTML.includes('5배 커지기'));a.menu=null;sim.hurt(a,999,sim.actors.get('b').player);net.receive(sim.snapshot());net.updateSpectator();net.renderHud();assert.equal(net.spectatorId,'c');assert(nodes.get('#killfeed').innerHTML.includes('Alice'));assert.equal(net.corpseMeshes.size,1);net.cycleSpectator(-1);assert.equal(net.spectatorId,'c');net.dispose();});

test('dungeon client renders ready, combat, room changes, rewards, bonus and unlock screens without PvP lookup failures',async()=>{
 const {DungeonEngine}=await import('../src/dungeon-engine.js');const room={owner:'a',options:{mode:'dungeon'},players:new Map([['a',{id:'a',name:'Alice',agent:'spidey',team:'A',connected:true}]])},sim=new DungeonEngine(room),g=Object.create(Game.prototype);
 Object.assign(g,{scene:new T.Scene(),camera:new T.PerspectiveCamera(78,16/9,.06,200),player:new Body(V(),V(.36,.9,.36)),preview:new T.Group(),arms:new T.Group(),effects:[],audio:{start(){},play(){}},sensitivity:.002,reset(){},updateHeldVisual(){},updateCamera(){},hud(){this.mapCtx=context;}});g.scene.add(g.camera);const lobby={g,identity:{id:'a'},room:{owner:'a'},api:async()=>({}),accept(){}};const net=new NetMatch(lobby,sim.snapshot());net.renderHud();assert(nodes.get('#net-overlay').innerHTML.includes('준비 완료'));
 sim.input('a',{actions:[{type:'dungeonReady'}]});sim.spawnMonster('crawler',V(0,1,-8));net.receive(sim.snapshot());assert.equal(net.monsterMeshes.size,1);net.paused=false;net.renderOverlay();net.renderHud();assert(nodes.get('#zone').textContent.includes('01 / 12'));assert(nodes.get('#stats').innerHTML.includes('V 대시'));
 sim.clearStage();net.receive(sim.snapshot());assert(nodes.get('#net-overlay').innerHTML.includes('승리'));assert(!nodes.get('#net-overlay').innerHTML.includes('data-dpick'));for(let i=0;i<180;i++)sim.tick(1/60);net.receive(sim.snapshot());assert(nodes.get('#net-overlay').innerHTML.includes('요원의 다음 진화'));sim.pick('a',sim.offers.get('a').ids[0]);net.receive(sim.snapshot());assert.equal(net.sceneStage,2);assert.equal(net.g.world.spec.stage,2);
 sim.enterStage(11);sim.input('a',{actions:[{type:'dungeonReady'}]});sim.clearStage();for(let i=0;i<180;i++)sim.tick(1/60);sim.pick('a',sim.offers.get('a').ids[0]);net.receive(sim.snapshot());assert(nodes.get('#net-overlay').innerHTML.includes('마지막 두 가지'));assert(nodes.get('#net-overlay').innerHTML.includes('data-dpick'));
 sim.finish(true,'test');net.receive(sim.snapshot());assert(nodes.get('#net-overlay').innerHTML.includes('해금 보상'));net.dispose();
});
