import test from 'node:test';import assert from 'node:assert/strict';import {once} from 'node:events';import {createServer} from '../server.mjs';
test('four independent co-op clients share one dungeon, remain same team and keep reward choices isolated',async()=>{
 const {server,rooms}=createServer();server.listen(0,'127.0.0.1');await once(server,'listening');const root='http://127.0.0.1:'+server.address().port;
 const post=async(path,data={},client)=>{const response=await fetch(root+'/api/'+path,{method:'POST',headers:{'Content-Type':'application/json',...(client?{Authorization:'Bearer '+client.token}:{})},body:JSON.stringify(['create','join'].includes(path)?{...data,profile:{schema:2,allUnlocked:true}}:data)});return {status:response.status,...await response.json()};};
 try{const host=await post('create',{name:'A',options:{mode:'dungeon'}}),people=[host];assert.equal(host.status,200);for(let i=1;i<4;i++)people.push(await post('join',{name:'P'+i,code:host.room.code}));assert.equal((await post('join',{code:host.room.code})).status,400);assert(people.every(p=>p.status===200));assert([...rooms.get(host.room.code).players.values()].every(p=>p.team==='A'));
 assert.equal((await post('team',{team:'B'},people[1])).status,400);assert.equal((await post('select',{},people[1])).status,400);assert.equal((await post('select',{},host)).status,200);for(const p of people)assert.equal((await post('ready',{agent:'arc'},p)).status,200);
 const s=rooms.get(host.room.code).sim;assert.equal(s.phase,'ready');await post('input',{actions:[{type:'dungeonReady'}]},host);assert.equal(s.phase,'ready');for(const p of people.slice(1))await post('input',{actions:[{type:'dungeonReady'}]},p);assert.equal(s.phase,'combat');assert.equal((await post('input',{actions:[{type:'dash'}]})).status,401);
 s.clearStage();for(let i=0;i<181;i++)s.tick(1/60);const chosen=s.offers.get(host.id).ids[0];await post('input',{actions:[{type:'dungeonPick',value:chosen,playerId:people[1].id}]},host);assert.deepEqual(s.actors.get(people[1].id).pendingBuild,[]);assert.equal(s.actors.get(host.id).pendingBuild.length,1);assert.equal(s.phase,'reward');
 for(const p of people.slice(1))await post('input',{actions:[{type:'dungeonPick',value:s.offers.get(p.id).ids[0]}]},p);assert.equal(s.stage,2);assert.equal(s.snapshot().players.length,4);assert.equal((await fetch(root+'/src/dungeon-engine.js')).status,200);assert.equal((await fetch(root+'/src/simulation-core.js')).status,200);
 }finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
});
