import test from 'node:test';
import assert from 'node:assert/strict';
import {DungeonEngine} from '../src/dungeon-engine.js';
import {BUFFS,UPGRADES,CATALOG,DungeonBank,rewardPool,seeded,unlockProfile} from '../src/dungeon-data.js';
import {AGENTS} from '../src/agents.js';
import {applyUpgrade} from '../src/dungeon-abilities.js';
import {V,overlaps} from '../src/physics.js';
const make=(agent='spidey',other)=>new DungeonEngine({owner:'a',options:{mode:'dungeon',seed:22},players:new Map([['a',{id:'a',name:'A',agent,team:'A',connected:true}],...(other?[['b',{id:'b',name:'B',agent:other,team:'A',connected:true}]]:[])])});
const start=s=>{for(const a of s.actors.values())s.input(a.id,{actions:[{type:'dungeonReady'}]});};
const ticks=(s,sec)=>{for(let i=0;i<Math.ceil(sec*60);i++)s.tick(1/60);};
const choose=s=>{for(const a of s.alive())while(s.offers.get(a.id)?.left>0)s.pick(a.id,s.offers.get(a.id).ids[0]);};
test('catalog contains 23 common buffs and eight implemented upgrades for every agent; stable unique IDs',()=>{assert.equal(BUFFS.length,23);assert.equal(CATALOG.length,111);assert.equal(new Set(CATALOG.map(b=>b.id)).size,111);for(const a of AGENTS)assert.equal(UPGRADES[a.id].length,8);});
test('reward pools match easy / medium / hard, exclude owned upgrades, bonus contains ALL unowned entries',()=>{const picked=new Set(['giant','spidey:regen']);for(let stage=1;stage<=5;stage++)assert(rewardPool('spidey',picked,stage).every(x=>x.kind==='buff'));assert.equal(rewardPool('spidey',picked,6,'medium').filter(x=>x.kind==='upgrade').length,1);assert(rewardPool('spidey',picked,6,'hard').every(x=>x.kind==='upgrade'));assert.equal(rewardPool('spidey',picked,12).length,29);assert(rewardPool('spidey',picked,12).every(x=>!picked.has(x.id)));});
test('complete 1-5 -> branch6 -> 7-11 -> bonus2 -> boss12 sequence, future-stage application and once-only ult credit',()=>{
 const s=make(),a=s.actors.get('a');for(let stage=1;stage<=11;stage++){assert.equal(s.stage,stage);assert.equal(s.phase,'ready');start(s);s.clearStage();assert.equal(s.phase,'victory');ticks(s,3);const points=a.ultPoints;s.clearStage();assert.equal(a.ultPoints,points);assert.equal(s.phase,'reward');const id=s.offers.get('a').ids[0];assert(!a.build.has(id));s.pick('a',id);assert(!s.pick('a',id));if(stage===5){assert.equal(s.phase,'branch');s.input('a',{actions:[{type:'dungeonVote',value:'hard'}]});assert.equal(s.difficulty,'hard');}else if(stage===11){assert.equal(s.phase,'bonus');const ids=[...s.offers.get('a').ids];assert(ids.length>5);s.pick('a',ids[0]);assert.equal(s.phase,'bonus');s.pick('a',ids[1]);assert.equal(s.stage,12);}else assert(a.build.has(id));}
 start(s);s.clearStage();ticks(s,3);assert(s.won);assert.equal(s.phase,'done');assert.equal(a.build.size,0);s.input('a',{actions:[{type:'dungeonUnlock',value:'vision'}]});assert.equal(s.rewardClaims.get('a'),'vision');s.input('a',{actions:[{type:'dungeonUnlock',value:'thor'}]});assert.equal(s.rewardClaims.get('a'),'vision');
});
test('kills, death, fake input and orbs do not grant dungeon ultimate points; stage awards refill after use',()=>{const s=make('arc'),a=s.actors.get('a');start(s);const m=s.spawnMonster('crawler',V(0,1,0));s.damage(a,m,999);assert.equal(a.ultPoints,0);a.gainUlt('처치');a.gainUlt('구슬');assert.equal(a.ultPoints,0);assert.equal(s.orbs.orbs.length,0);a.ultPoints=a.ultCost;a.skill('R');assert.equal(a.ultPoints,0);s.clearStage();assert.equal(a.ultPoints,1);});
test('cooldown bank regenerates forever, magazines auto-holster and restore, overclock costs are bounded',()=>{const s=make('widow'),a=s.actors.get('a');start(s);a.skill('Q');for(let i=0;i<8;i++){a.cool.gun=0;a.attack(0);}assert.equal(a.equipped,null);assert.equal(a.bank.count(0),0);a.bank.tick(8.01);assert.equal(a.bank.count(0),8);for(let i=0;i<50;i++){assert(a.use(1));a.bank.tick(15.01);}applyUpgrade(a,'overclock');a.hp=1;assert(a.use(2));assert.equal(a.hp,1);assert.equal(a.bank.timers[2],8);});
test('V dash moves with collision and does not provide invulnerability; timed failure clears run',()=>{const s=make('arc'),a=s.actors.get('a');start(s);const z=a.player.p.z;s.input('a',{yaw:0,keys:['KeyW'],actions:[{type:'dash'}]});assert(a.evadeTime>0);assert(!a.dungeonDash());s.hurt(a,10);assert.equal(a.hp,90);ticks(s,.22);assert(a.player.p.z<z-2);applyUpgrade(a,'giant');s.rules.time=.01;s.tick(.02);assert.equal(s.phase,'done');assert(!s.won);assert.equal(a.build.size,0);assert.match(s.reason,/제한 시간/);});
test('pit collision is a real missing floor, flight can pass above it, falling fails even on immortal entry',()=>{const s=make(),a=s.actors.get('a');s.enterStage(3);start(s);applyUpgrade(a,'phoenix');a.entryGuard=5;a.player.p.set(-10,.9,0);a.player.v.set(0,0,0);ticks(s,1);assert.equal(s.phase,'done');assert(!s.won);});
test('co-op rewards remain personal and duplicate picks cannot change another player; vote tie favors host',()=>{const s=make('spidey','arc');start(s);s.clearStage();ticks(s,3);const own=s.offers.get('a').ids[0],other=s.offers.get('b').ids[0];s.pick('a',own);assert.deepEqual(s.actors.get('b').pendingBuild,[]);assert.equal(s.phase,'reward');assert(!s.pick('a',own));s.pick('b',other);assert.equal(s.stage,2);s.enterStage(5);start(s);s.clearStage();ticks(s,3);choose(s);assert.equal(s.phase,'branch');s.input('a',{actions:[{type:'dungeonVote',value:'hard'}]});assert.equal(s.phase,'branch');s.input('b',{actions:[{type:'dungeonVote',value:'easy'}]});assert.equal(s.stage,6);assert.equal(s.difficulty,'hard');});
test('single death ends solo; team death permits spectating and Hera can revive before a full wipe',()=>{const s=make('hera','arc'),a=s.actors.get('a'),b=s.actors.get('b');start(s);s.hurt(b,999);assert(b.dead);assert.equal(s.phase,'combat');assert.equal(s.corpses.length,1);assert(s.revive('b'));assert.equal(b.hp,50);s.hurt(a,999);s.hurt(b,999);assert.equal(s.phase,'done');});
test('boss has three phases, ranged patterns and resistance to permanent stun / instant shrink lock',()=>{const s=make('ant'),a=s.actors.get('a');s.enterStage(12);start(s);const b=s.spawnMonster('boss',V(0,3,-8));s.bossPattern(b,a);assert.equal(b.phase,1);b.hp=b.maxHP*.6;s.bossPattern(b,a);assert.equal(b.phase,2);b.hp=b.maxHP*.2;s.bossPattern(b,a);assert.equal(b.phase,3);s.status(b,{stun:5},a);assert(b.stun<=.3);const height=b.h.y;s.shrink(b,1,a);assert.equal(b.h.y,height);assert(b.weakenUntil>s.time);assert(s.telegraphs.length>=3);});
test('every agent and all eight upgrades execute skills, projectiles, frame updates and JSON snapshot safely',()=>{for(const agent of AGENTS){const s=make(agent.id),a=s.actors.get('a');for(const u of UPGRADES[agent.id])applyUpgrade(a,u.id);start(s);a.player.p.set(0,a.player.h.y,7);s.camera(a);for(let i=0;i<5;i++)s.spawnMonster('stalker',V((i-2)*1.5,1,-1));if(agent.id==='bane'){a.rage=100;a.transformBane();}for(const key of ['Q','E','C']){a.cast=null;a.menu=null;a.cool={punch:0,right:0,shield:0};a.bank.fill();a.skill(key);if(a.menu==='size')a.chooseExpansion('large');if(a.menu==='arrow'){a.arrowType=2;a.menu=null;}if(a.charge){a.charge.start=a.t-2;a.releaseCharge();}a.attack(0);a.attack(2);ticks(s,.35);}a.cast=null;a.menu=null;a.scope=0;a.ultPoints=a.ultCost;a.skill('R');ticks(s,3);assert(Number.isFinite(a.hp),agent.id);assert.doesNotThrow(()=>JSON.stringify(s.snapshot()),agent.id);}});
test('stat, ability, damage and timing upgrades change actual mechanics (not just text)',()=>{
 const s=make('arc'),a=s.actors.get('a');start(s);applyUpgrade(a,'arc:shield');a.skill('Q');assert.equal(a.shieldHP,150);a.shieldOn=false;applyUpgrade(a,'arc:snap');a.hp=20;a.ultPoints=a.ultCost;a.skill('R');assert.equal(a.cast,null);assert.equal(a.hp,100);
 const t=make('pigeon'),p=t.actors.get('a');start(t);applyUpgrade(p,'pigeon:double');assert.equal(p.bank.count(1),2);applyUpgrade(p,'pigeon:switch');p.charge={kind:'arrow',start:p.t};p.stowCharge();assert.equal(p.cool.punch,0);
 const b=make('bane'),g=b.actors.get('a');start(b);applyUpgrade(g,'bane:rage');applyUpgrade(g,'bane:skin');g.rage=70;g.transformBane();assert(g.transformed);assert.equal(g.maxHP,350);applyUpgrade(g,'bane:instant');g.skill('Q');assert.equal(g.cast,null);
});
test('save adapter is idempotent and only records explicit successful unlock, never run buffs',()=>{let p=unlockProfile({},'ant','r1');p=unlockProfile(p,'vision','r1');assert.deepEqual(p.unlocked,['ant']);assert.equal(p.schema,1);assert(!p.build);});

test('quantum rewind restores five-second-old monsters, health, position, cooldowns and timer without refunding ultimate',()=>{
 const s=make('ant'),a=s.actors.get('a');start(s);s.spawnPending=[];s.spawnMonster('sentinel',V(15,1,-18));s.monsters[0].cool=999;a.player.p.set(0,.9,15);ticks(s,6);a.hp=30;a.player.p.x=4;a.bank.base[0]=0;a.bank.timers[0]=12;a.ultPoints=a.ultCost;const timer=s.rules.time;a.skill('R');ticks(s,2.1);assert(a.hp>30);assert(Math.abs(a.player.p.x)<.1);assert.equal(a.ultPoints,0);assert.equal(a.bank.count(0),1);assert(s.rules.time>timer);assert(s.monsters.length>0);assert.doesNotThrow(()=>JSON.stringify(s.snapshot()));
});
test('damage buff math, debuffs, reflect, cooldown and safety effects are live in combat',()=>{
 const s=make('arc'),a=s.actors.get('a');start(s);const b=s.spawnMonster('juggernaut',V(0,1,12));b.armor=0;b.hp=60;b.maxHP=300;applyUpgrade(a,'execution');s.damage(a,b,10);assert.equal(b.hp,46);applyUpgrade(a,'opportunity');b.slow=2;s.damage(a,b,10);assert(Math.abs(b.hp-27.8)<.001);
 applyUpgrade(a,'vampire');a.hp=50;s.damage(a,b,10);assert(a.hp>50);applyUpgrade(a,'reflect');const before=b.hp;s.hurt(a,10,b);assert(b.hp<before);
 applyUpgrade(a,'escape');a.hp=19;s.hurt(a,1,b);assert(a.escapeUntil>a.t);applyUpgrade(a,'will');s.monsterHit(b,a,1,{status:{stun:4}});assert.equal(a.player.stun,2);
 const c=make('cap'),cap=c.actors.get('a');start(c);const enemy=c.spawnMonster('stalker',V(0,1,15));cap.spin=3;applyUpgrade(cap,'cap:reflect');const hp=cap.hp;c.hurt(cap,10,enemy);assert.equal(cap.hp,hp);assert.equal(enemy.hp,enemy.maxHP-30);
});
test('charged piercing arrows pass through successive monsters while solid walls block ordinary attacks',()=>{
 const s=make('pigeon'),a=s.actors.get('a');start(s);a.player.p.set(0,.9,10);s.camera(a);const b=s.spawnMonster('stalker',V(0,.98,5)),c=s.spawnMonster('stalker',V(0,.98,2));applyUpgrade(a,'pigeon:pierce');a.skill('Q');a.charge.start=a.t-2;a.releaseCharge();for(let i=0;i<25;i++)a.tickProjectiles(1/120);assert(b.hp<b.maxHP);assert(c.hp<c.maxHP);
});

test('last enemy defeated before deadline clears immediately without a wave-transition time penalty',()=>{const s=make(),a=s.actors.get('a');start(s);s.spawnPending=[];const b=s.spawnMonster('crawler',V(0,1,0));s.rules.time=.005;s.damage(a,b,999);s.tick(1/60);assert.equal(s.phase,'victory');assert.equal(a.ultPoints,1);ticks(s,3);assert.equal(s.phase,'reward');});
