import test from 'node:test';import assert from 'node:assert/strict';import {Simulation} from '../simulation.mjs';import {V,Body} from '../src/physics.js';import {AGENTS} from '../src/agents.js';import {MAPS} from '../src/maps.js';
function make(agent='ant',map='squad'){const s=new Simulation({options:{map,rounds:6,unlimited:false},players:new Map([['a',{id:'a',team:'A',agent,name:'Alice',connected:true}],['b',{id:'b',team:'B',agent:'arc',name:'Bob',connected:true}],['c',{id:'c',team:'A',agent:'thor',name:'Chris',connected:true}]])});s.rules.phase='live';s.rules.time=100;for(const a of s.actors.values())a.bank.fill();return s;}
const ticks=(s,n)=>{for(let i=0;i<n;i++)s.tick(1/60);};
test('four map slots and unchanged agent-relative map scale',()=>{assert.deepEqual(MAPS.map(m=>[m.id,m.size]),[['duel',1],['trio',3],['squad',5],['atrium',5]]);const s=make();assert.equal(s.world.map.w,128);assert.equal(s.world.map.d,144);assert.equal(s.actors.get('a').player.h.y,.9);assert.equal(AGENTS.length,11);});
test('bomb starts in attack base, ground pickup, 4 then G, teammate pickup and death drop',()=>{const s=make('arc'),a=s.actors.get('a'),c=s.actors.get('c');assert.equal(s.rules.spike.carrier,null);a.player.p.set(0,.9,-s.world.map.spawn);ticks(s,1);assert.equal(s.rules.spike.carrier,'a');s.input('a',{actions:[{type:'dropSpike'}]});assert.equal(s.rules.spike.carrier,'a');s.input('a',{actions:[{type:'selectBomb'},{type:'dropSpike'}]});assert.equal(s.rules.spike.carrier,null);c.player.p.copy(a.player.p);ticks(s,1);assert.equal(s.rules.spike.carrier,'c');s.hurt(c,1000,s.actors.get('b').player);assert.equal(s.rules.spike.carrier,null);assert(s.rules.spike.dropped);assert.equal(s.corpses.length,1);});
test('5v5 credits spend, refuse unaffordable purchase, reward and preserve unused skills',()=>{const s=make('hera'),a=s.actors.get('a');s.rules.phase='buy';a.bank.extra=[0,0,0];a.credits=800;assert(s.buy(a,'armor',0));assert.equal(a.credits,400);assert(s.buy(a,2));assert.equal(a.credits,0);assert.equal(s.buy(a,0),false);s.reward(a,10000);assert.equal(a.credits,9000);s.rules.round=2;s.resetRound();assert.equal(a.bank.count(2),1);assert.equal(a.credits,9000);});
test('ant size choice, fivefold hitbox, early revert and enemy shrink restoration',()=>{const s=make(),a=s.actors.get('a'),b=s.actors.get('b');a.player.p.set(0,.9,-55);a.skill('E');assert.equal(a.menu,'size');s.input('a',{actions:[{type:'chooseSize',value:'large'}]});assert.equal(a.bodyScale,5);assert.equal(a.player.h.y,4.5);a.skill('E');assert.equal(a.bodyScale,1);a.expansionImpact({kind:'change',scale:1},b.player.p,b.player);assert.equal(b.bodyScale,.5);assert.equal(b.outgoing(70),10);ticks(s,302);assert.equal(b.bodyScale,1);});
test('70 ants spawn as game entities and acquire nearby targets',()=>{const s=make(),a=s.actors.get('a');a.skill('C');assert.equal(a.ants.length,70);assert(s.snapshot().ants.length<=70);});
test('Hera soul heal and revival preserve death counter but restore ally at 50HP x2',()=>{const s=make('hera'),a=s.actors.get('a'),b=s.actors.get('b'),c=s.actors.get('c');s.damage(a,b.player,999);assert.equal(a.souls,1);a.skill('E');assert.equal(a.hp,150);s.rules.phase='live';s.hurt(c,999,b.player);assert(s.revive('c'));assert.equal(c.hp,50);assert.equal(c.outgoing(25),50);assert.equal(s.roundDeaths,2);assert.equal(s.corpses.some(x=>x.id==='c'),false);});
test('thorn wall placement consumes one, segments decay and break independently',()=>{const s=make('hera'),a=s.actors.get('a');a.player.p.set(0,.9,-55);a.yaw=0;a.pitch=0;a.wallAngle=0;a.wallScale=1;assert(a.placeWall());assert.equal(s.dynamicWalls.length,3);assert(s.dynamicWalls.every(w=>w.hp===400));a.damageWall(s.dynamicWalls[0],400);assert.equal(s.dynamicWalls[0].active,false);assert.equal(s.dynamicWalls[1].active,true);s.dynamicWalls[1].decay=.01;a.tickExpansion(.02);assert.equal(s.dynamicWalls[1].hp,300);});
test('Panther absorbs energy; release clears; ancestor toggle cannot heal indefinitely',()=>{const s=make('panther'),a=s.actors.get('a');a.armor=0;s.hurt(a,20,s.actors.get('b').player);assert.equal(a.energy,10);a.skill('C');assert.equal(a.energy,0);a.ultPoints=a.ultCost;s.roundDeaths=2;a.skill('R');a.tickExpansion(.01);assert.equal(a.maxHP,150);const hp=a.hp;a.skill('R');a.tickExpansion(.01);a.skill('R');a.tickExpansion(.01);assert(Math.abs(a.hp-hp)<.001);});
test('Vision ally passive, flight fuel/recharge, phase invulnerability and beam duration',()=>{const s=make('vision'),a=s.actors.get('a');assert.equal(a.maxHP,120);a.skill('E');a.keys={Space:true};a.tickExpansion(2);assert.equal(a.flightGauge,98);a.skill('E');a.tickExpansion(2);assert.equal(a.flightGauge,99);a.skill('Q');s.hurt(a,80,s.actors.get('b').player);assert.equal(a.hp,120);a.skill('Q');assert.equal(a.phased,0);a.ultPoints=a.ultCost;a.skill('R');assert.equal(a.beamTime,3);});
test('Quantum restores health positions skills timer bomb and corpses; cost not refunded',()=>{const s=make(),a=s.actors.get('a'),b=s.actors.get('b');a.player.p.set(0,.9,-55);a.ultPoints=a.ultCost;ticks(s,360);const old=b.player.p.clone();s.actors.get('c').team='B';s.room.players.get('c').team='B';s.damage(a,b.player,999);b.player.p.x=10;a.bank.extra[0]=0;s.rules.time=20;s.rules.spike.carrier='a';s.rules.spike.dropped=null;a.skill('R');assert(a.cast);ticks(s,121);assert.equal(b.dead,false);assert.equal(b.hp,100);assert(b.player.p.distanceTo(old)<.1);assert.equal(a.bank.count(0),2);assert.equal(a.ultPoints,0);assert(s.rules.time>80);assert.equal(s.corpses.length,0);assert.equal(s.rules.spike.carrier,null);assert.equal(s.revision,1);});
test('Ctrl hold plus move/jump/attack keeps physics finite',()=>{const s=make('arc');for(let i=0;i<300;i++){s.input('a',{keys:['ControlLeft','KeyW'],actions:[{type:'jump'},{type:'attack',button:0}]});s.tick(1/60);}const a=s.actors.get('a');assert(a.player.p.toArray().every(Number.isFinite));assert.equal(a.player.h.y,.56);});
test('fall damage affects ordinary agents but exempts Spidey Arc Thor',()=>{for(const id of ['hera','spidey','arc','thor']){const s=make(id),a=s.actors.get('a');a.armor=0;a.player.p.set(0,9,-55);a.player.grounded=false;ticks(s,100);assert.equal(a.hp<100,id==='hera');}});
