import test from 'node:test';import assert from 'node:assert/strict';import {once} from 'node:events';import {createServer} from '../server.mjs';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
test('two independent LAN connections: lobby, authority, selection, inputs and shared round results',async()=>{
 const {server,rooms}=createServer();server.listen(0,'127.0.0.1');await once(server,'listening');const root='http://127.0.0.1:'+server.address().port;const controllers=[];
 const post=async(path,data={},who)=>{const r=await fetch(root+'/api/'+path,{method:'POST',headers:{'Content-Type':'application/json',...(who?{Authorization:'Bearer '+who.token}:{})},body:JSON.stringify(data)});return {status:r.status,...await r.json()};};
 try{
 const host=await post('create',{name:'방장',options:{map:'duel',rounds:2,unlimited:false}});assert.equal(host.status,200);const guest=await post('join',{name:'친구',code:host.room.code});assert.equal(guest.status,200);assert.equal((await post('join',{code:host.room.code})).status,400);assert.equal((await post('config',{options:{map:'squad',rounds:99,unlimited:true}},guest)).status,400);
 const streams=[];for(const client of [host,guest]){const controller=new AbortController();controllers.push(controller);const r=await fetch(root+'/api/events?token='+client.token,{signal:controller.signal});assert.equal(r.headers.get('content-type'),'text/event-stream');const reader=r.body.getReader();const messages=[];streams.push(messages);(async()=>{let pending='';try{while(true){const chunk=await reader.read();if(chunk.done)break;pending+=new TextDecoder().decode(chunk.value);let n;while((n=pending.indexOf('\n\n'))>=0){const event=pending.slice(0,n);pending=pending.slice(n+2);if(event.startsWith('data: '))messages.push(JSON.parse(event.slice(6)));}}}catch{}})();}
 assert.equal((await post('select',{},host)).status,200);assert.equal((await post('ready',{agent:'spidey'},host)).status,200);assert.equal((await post('ready',{agent:'arc'},guest)).status,200);const room=rooms.get(host.room.code);assert.equal(room.stage,'match');await sleep(100);for(const stream of streams)assert(stream.some(m=>m.kind==='snapshot'));
 room.sim.rules.phase='live';room.sim.rules.time=100;const actor=room.sim.actors.get(host.id),enemy=room.sim.actors.get(guest.id);const start=actor.player.p.z;await post('input',{keys:['KeyW'],yaw:Math.PI,pitch:0,actions:[{type:'jump'}]},host);await sleep(150);assert(actor.player.p.z>start);assert(actor.player.p.y>.9);assert.equal(enemy.player.p.z,room.sim.world.map.spawn);
 room.sim.damage(actor,enemy.player,999);await sleep(110);for(const stream of streams){const last=stream.filter(m=>m.kind==='snapshot').at(-1);assert.equal(last.match.score.A,1);assert.equal(last.match.result.team,'A');assert.equal(last.players.find(p=>p.id===guest.id).dead,true);}
 assert.equal((await post('resume',{},host)).id,host.id);assert.equal((await post('input',{keys:['KeyW']})).status,401);const page=await fetch(root+'/');assert.equal(page.status,200);assert((await page.text()).includes('/src/app.js'));assert.equal((await fetch(root+'/server.mjs')).status,404);
 }finally{for(const c of controllers)c.abort();server.closeAllConnections();await new Promise(r=>server.close(r));}
});
test('5v5 capacity and all player sessions remain isolated',async()=>{const {server,rooms}=createServer();server.listen(0,'127.0.0.1');await once(server,'listening');const root='http://127.0.0.1:'+server.address().port;const post=async(path,data,who)=>{const r=await fetch(root+'/api/'+path,{method:'POST',headers:{'Content-Type':'application/json',...(who?{Authorization:'Bearer '+who.token}:{})},body:JSON.stringify(data)});return {status:r.status,...await r.json()};};try{const host=await post('create',{name:'A',options:{map:'squad',rounds:1,unlimited:true}}),people=[host];for(let i=1;i<10;i++)people.push(await post('join',{name:'P'+i,code:host.room.code}));assert.equal((await post('join',{name:'overflow',code:host.room.code})).status,400);const r=rooms.get(host.room.code);assert.equal([...r.players.values()].filter(p=>p.team==='A').length,5);assert.equal(new Set(people.map(p=>p.token)).size,10);await post('select',{},host);for(const p of people)await post('ready',{agent:'spidey'},p);assert.equal(r.sim.actors.size,10);assert.equal(r.sim.snapshot().players.length,10);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}});
