import test from 'node:test';
import assert from 'node:assert/strict';
import {Simulation} from '../simulation.mjs';
import {decorateAgent,poseAgent} from '../src/visuals.js';
function setup(agent){const s=new Simulation({options:{map:'duel',rounds:4,unlimited:false},players:new Map([['a',{id:'a',team:'A',agent,connected:true}],['b',{id:'b',team:'B',agent:'arc',connected:true}]])});s.rules.phase='live';s.rules.time=100;return {s,a:s.actors.get('a'),b:s.actors.get('b')};}
test('monster grows 15 percent, turns green and regains transformed size after shrink',()=>{const {s,a}=setup('bane');a.rage=100;a.transformBane();assert.equal(a.bodyScale,1.15);const mesh=a.player.mesh;decorateAgent(mesh,false);poseAgent(mesh,s.snapshot().players[0],0);assert.equal(mesh.userData.form,'monster');assert.equal(mesh.userData.torso.material.color.getHexString(),'78bc57');a.resizeBody(.5);a.shrinkTime=.01;a.tickExpansion(.02);assert.equal(a.bodyScale,1.15);assert.equal(a.shrinkTime,0);});
test('Pigeon recovery has exactly one provided slot, including refill',()=>{const {a}=setup('pigeon');assert.equal(a.bank.count(1),1);assert.equal(a.bank.canBuy(1),false);a.bank.fill();assert.equal(a.bank.count(1),1);assert(a.bank.use(1));assert.equal(a.bank.use(1),false);});
test('shrunken outgoing skills and reflected attacks deal ten until restoration',()=>{const {s,a,b}=setup('cap');a.shrinkTime=5;a.resizeBody(.5);for(const n of [1,20,80,10000])assert.equal(a.outgoing(n),10);a.spin=3;a.armor=0;b.armor=0;s.hurt(a,80,b.player);assert.equal(b.hp,90);a.shrinkTime=.01;a.tickExpansion(.02);assert.equal(a.shrinkTime,0);assert.equal(a.outgoing(80),80);});
test('Vision beam allows movement, retains attack lock and emits three visible layers',()=>{const {s,a}=setup('vision');a.beamTime=3;a.frame=4;a.tickExpansion(.01);assert.equal(a.effects.length,3);assert.deepEqual(a.effects.map(e=>e.opacity),[.2,.55,1]);assert(a.busy());assert.equal(a.busy(false),false);const old=a.player.p.clone();s.input('a',{keys:['KeyD']});for(let i=0;i<20;i++)s.tick(1/60);assert(a.player.p.distanceTo(old)>.2);assert(a.beamTime>0);assert(s.snapshot().players[0].beamTime>0);a.stun=1;assert(a.busy(false));});
