import test from 'node:test';import assert from 'node:assert/strict';import {MatchRules} from '../src/match-rules.js';
const rules=()=>{const m=new MatchRules({rounds:4},[{x:0,z:0,r:3},{x:10,z:0,r:3}]);m.phase='live';m.time=100;m.spike.carrier='a';return m;};
const players=()=>[{id:'a',team:'A',alive:true,interact:false,grounded:true,x:0,z:0},{id:'b',team:'B',alive:true,interact:false,grounded:true,x:0,z:0}];
function steps(m,p,n,dt=1/60){for(let i=0;i<n;i++)m.step(dt,p);}
test('defender elimination wins for attackers',()=>{const m=rules(),p=players();p[1].alive=false;m.step(.01,p);assert.equal(m.result.team,'A');});
test('attacker elimination before plant wins for defenders',()=>{const m=rules(),p=players();p[0].alive=false;m.step(.01,p);assert.equal(m.result.team,'B');});
test('planted spike continues after attacker elimination and explodes',()=>{const m=rules(),p=players();p[0].interact=true;steps(m,p,241);assert.equal(m.spike.state,'planted');p[0].alive=false;p[0].interact=false;m.step(.01,p);assert.equal(m.phase,'live');steps(m,p,2701);assert.equal(m.result.team,'A');});
test('defuse saves half progress and wins after resumed channel',()=>{const m=rules(),p=players();m.spike.state='planted';m.spike.site=0;p[1].interact=true;steps(m,p,215);p[1].interact=false;m.step(.02,p);assert.equal(m.spike.progress,3.5);p[1].interact=true;steps(m,p,211);assert.equal(m.result.team,'B');assert.equal(m.spike.state,'defused');});
test('plant progress resets when switching player or leaving site',()=>{const m=rules(),p=players();p[0].interact=true;steps(m,p,120);p[0].x=20;m.step(.01,p);assert.equal(m.spike.progress,0);p[0].x=0;steps(m,p,120);assert.equal(m.spike.state,'idle');});
test('multiple attackers cannot accelerate planting',()=>{const m=rules(),p=players();p[0].interact=true;p.push({...p[0],id:'c'});steps(m,p,125);assert.equal(m.spike.state,'idle');assert(m.spike.progress<2.2);});
test('time expiration awards defense and scores once',()=>{const m=rules(),p=players();m.time=.01;m.step(.02,p);m.finish('B','duplicate');assert.equal(m.score.B,1);});
test('exact configured rounds and halftime side swap',()=>{const m=rules();for(let i=1;i<=4;i++){assert.equal(m.round,i);assert.equal(m.role('A'),i<=2?'attack':'defend');m.finish('A','test');m.step(5.1,players());}assert.equal(m.phase,'done');assert.equal(m.round,4);assert.equal(m.score.A,4);});
test('only spike carrier can plant; eliminated carrier drops for teammate recovery',()=>{const m=rules(),p=players();p[0].x=2;p[0].interact=false;p.push({id:'c',team:'A',alive:true,interact:true,grounded:true,x:0,z:0});m.spike.carrier='a';steps(m,p,250);assert.equal(m.spike.state,'idle');p[0].alive=false;m.step(.01,p);assert(m.spike.dropped);assert.equal(m.spike.carrier,null);p[2].x=2;m.step(.01,p);assert.equal(m.spike.carrier,'c');steps(m,p,241);assert.equal(m.spike.state,'planted');assert.equal(m.spike.position.x,2);});
