import test from 'node:test';import assert from 'node:assert/strict';import {Simulation} from '../simulation.mjs';import {AGENTS} from '../src/agents.js';import {MAPS} from '../src/maps.js';import {V} from '../src/physics.js';
function make(agent='spidey',map='duel',unlimited=false){const room={options:{map,rounds:4,unlimited},players:new Map([['a',{id:'a',team:'A',name:'A',agent,connected:true}],['b',{id:'b',team:'B',name:'B',agent:'arc',connected:true}]])};const s=new Simulation(room);s.rules.phase='live';s.rules.time=100;return s;}
function tick(s,n=1){for(let i=0;i<n;i++)s.tick(1/60);}
test('all three maps have valid spawns and fresh round state',()=>{for(const m of MAPS){const s=make('spidey',m.id);tick(s,10);for(const a of s.actors.values()){assert.equal(a.hp,100);assert(a.player.grounded);assert(a.player.p.toArray().every(Number.isFinite));}assert.equal(s.world.map.size,m.size);}});
test('movement, normal jump, server-owned health',()=>{const s=make(),a=s.actors.get('a');s.input('a',{keys:['KeyW'],yaw:Math.PI,pitch:0,actions:[{type:'jump'}],hp:9999});tick(s,20);assert(a.player.p.y>.9);assert(a.player.p.z>-s.world.map.spawn);assert.equal(a.hp,100);});
test('space heights and one rechargeable E slot',()=>{const s=make(),a=s.actors.get('a');s.input('a',{keys:[],yaw:Math.PI,pitch:0,actions:[{type:'skill',key:'E'}]});assert.equal(a.bank.count(1),1);tick(s,90);s.input('a',{actions:[{type:'skill',key:'E'}]});assert.equal(a.bank.count(1),0);tick(s,1800);assert.equal(a.bank.count(1),1);tick(s,1800);assert.equal(a.bank.count(1),1);});
test('unlimited mode consumes no normal skill charges',()=>{const s=make('spidey','duel',true),a=s.actors.get('a');const n=a.bank.count(0);a.skill('Q');a.attack(0);assert.equal(a.bank.count(0),n);assert.equal(a.projectiles.length,1);a.skill('R');assert.equal(a.transformed,false);});
test('friendly fire ignored; enemy kill gives one point without respawn',()=>{const s=make(),a=s.actors.get('a'),b=s.actors.get('b');s.damage(a,a.player,1000);assert.equal(a.hp,100);s.damage(a,b.player,1000);assert(b.dead);assert.equal(a.ultPoints,1);assert.equal(b.ultPoints,1);assert.equal(a.ultReady,false);assert.equal(a.kills,1);assert.equal(b.tasks.length,0);tick(s,1);assert.equal(s.rules.result.team,'A');});
test('only Spidey regenerates health',()=>{const s=make(),a=s.actors.get('a'),b=s.actors.get('b');a.hp=b.hp=70;tick(s,60);assert(a.hp>70.9);assert.equal(b.hp,70);});
test('all eleven agents can use normal skills and ult in authoritative simulation',()=>{for(const ag of AGENTS){for(const key of ['Q','E','C','R']){const s=make(ag.id),a=s.actors.get('a'),b=s.actors.get('b');a.player.p.set(0,.9,-3);b.player.p.set(0,.9,-1.1);s.camera(a);s.camera(b);a.yaw=Math.PI;a.ultPoints=a.ultCost;a.ultReady=true;if(ag.id==='bane'){a.rage=100;a.transformBane();}s.input('a',{keys:[],yaw:Math.PI,pitch:0,actions:[{type:'skill',key}]});tick(s,4);if(a.menu==='arrow')s.input('a',{actions:[{type:'chooseArrow',value:1}]});if(a.menu==='copy')s.input('a',{actions:[{type:'copy',agent:'spidey',key:'E'}]});if(a.charge){tick(s,60);s.input('a',{actions:[{type:'releaseQ'}]});}tick(s,240);const snap=s.snapshot();assert(snap.players.every(p=>Number.isFinite(p.hp)&&p.pos.every(Number.isFinite)),ag.id+key);}}});
test('stun blocks actions and control while root blocks movement only',()=>{const s=make(),a=s.actors.get('a'),b=s.actors.get('b');s.damage(b,a.player,0,{stun:2});tick(s);const n=a.bank.count(0);s.input('a',{keys:['KeyW'],actions:[{type:'skill',key:'Q'},{type:'jump'}]});tick(s,10);assert.equal(a.equipped,null);assert.equal(a.bank.count(0),n);assert(a.player.grounded);});
test('round transition clears projectiles/status and moves teams to new spawns',()=>{const s=make(),a=s.actors.get('a');a.skill('Q');a.attack(0);s.rules.finish('A','test');tick(s,310);assert.equal(s.rules.round,2);assert.equal(a.projectiles.length,0);assert.equal(a.hp,100);assert.equal(a.armor,50);});
