import test from 'node:test';import assert from 'node:assert/strict';
import {Simulation} from '../simulation.mjs';import {MAPS} from '../src/maps.js';import {V} from '../src/physics.js';import {createServer} from '../server.mjs';import {tunnelURL,verify} from '../internet.mjs';
function make(agent='arc',map='duel'){return new Simulation({options:{map,rounds:4,unlimited:false},players:new Map([['a',{id:'a',name:'A',team:'A',agent,connected:true}],['b',{id:'b',name:'B',team:'B',agent:'arc',connected:true}]])});}
test('points persist, cap, require full cost and consume on R',()=>{const s=make(),a=s.actors.get('a');s.rules.phase='live';a.gainUlt('test');a.skill('R');assert.equal(a.cast,null);s.resetRound();assert.equal(a.ultPoints,1);for(let i=0;i<20;i++)a.gainUlt('test');assert.equal(a.ultPoints,8);a.skill('R');assert.equal(a.ultPoints,0);assert(a.cast);});
test('death and kill each award once',()=>{const s=make(),a=s.actors.get('a'),b=s.actors.get('b');s.rules.phase='live';s.damage(a,b.player,1000);s.damage(a,b.player,1000);assert.equal(a.ultPoints,1);assert.equal(b.ultPoints,1);});
test('actual humanoid mesh hits distinguish head torso legs; area remains base damage',()=>{const s=make(),a=s.actors.get('a'),b=s.actors.get('b');s.rules.phase='live';a.player.p.set(0,.9,-7);b.player.p.set(0,.9,-4);b.player.sync();for(const [y,expected,region] of [[1.7,30,'head'],[1.1,20,'body'],[.45,15,'legs']]){b.hp=100;b.armor=0;const h=a.raycast(V(.12,y,-7),V(0,0,1),4);assert.equal(h?.object.userData.body,b.player);a.hitDirect(b.player,20,h.point,h.object);assert.equal(a.lastHitRegion,region);assert.equal(b.hp,100-expected);}b.hp=100;a.area(b.player.p,2,20);assert.equal(b.hp,80);});
test('Widow copy applies seventy percent flight duration',()=>{const s=make('widow'),a=s.actors.get('a');s.rules.phase='live';a.copyAwait=true;a.copySkill={id:'arc',key:'E'};a.skill('E');assert(Math.abs(a.flight-5.6)<1e-8);});
test('two reachable distinct orbs each round; hold, release, damage, single collector',()=>{for(const map of MAPS){const s=make('arc',map.id);assert.equal(s.orbs.orbs.length,2);for(const o of s.orbs.orbs)assert(!s.physics.solids.some(b=>b.active&&b.p.y-b.h.y<1.9&&Math.abs(o.x-b.p.x)<b.h.x+.7&&Math.abs(o.z-b.p.z)<b.h.z+.7));}
 const s=make(),a=s.actors.get('a'),b=s.actors.get('b');assert.equal(s.orbs.orbs.length,2);const o=s.orbs.orbs[0];a.player.p.set(o.x,.9,o.z+1);b.player.p.set(o.x+.5,.9,o.z+1);for(const p of [a,b]){p.keys={KeyF:true};p.player.grounded=true;s.camera(p);p.raycast=()=>null;}
 s.orbs.tick(1,[a,b]);assert.equal(a.orbChannel.progress,1);a.keys={};s.orbs.tick(.1,[a]);assert.equal(o.progress,0);a.keys={KeyF:true};s.orbs.tick(1,[a]);a.lastDamage=10;s.orbs.tick(.1,[a]);assert.equal(o.progress,0);s.orbs.tick(1,[a,b]);s.orbs.tick(1,[a,b]);assert.equal(a.ultPoints,1);assert.equal(b.ultPoints,0);assert.equal(o.active,false);s.resetRound();assert.equal(s.orbs.orbs.filter(o=>o.active).length,2);
});
test('plant and defuse award only once',()=>{const s=make(),a=s.actors.get('a'),b=s.actors.get('b');s.rules.phase='live';s.rules.spike.carrier='a';s.rules.sites=[{x:0,z:0,r:3}];const p=[{id:'a',team:'A',alive:true,interact:true,grounded:true,x:0,z:0},{id:'b',team:'B',alive:true,interact:false,grounded:true,x:0,z:0}];s.rules.step(4,p);assert.deepEqual(s.rules.awards,[{id:'a',reason:'설치'}]);p[0].interact=false;p[1].interact=true;s.rules.step(7,p);s.rules.step(.1,p);assert.deepEqual(s.rules.awards,[{id:'a',reason:'설치'},{id:'b',reason:'해체'}]);});
test('HTTPS origin, authenticated polling, invite address and invalid origin rejection',async()=>{const app=createServer({publicOrigin:'https://test.trycloudflare.com'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+app.server.address().port;try{const post=(path,data={},token,origin='https://test.trycloudflare.com')=>fetch(url+'/api/'+path,{method:'POST',headers:{'Content-Type':'application/json',Origin:origin,...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(data)});const res=await post('create',{options:{map:'duel',rounds:4,unlimited:false}});assert.equal(res.status,200);const p=await res.json();const poll=await post('poll',{},p.token);assert.equal((await poll.json()).room.code,p.room.code);assert.equal((await post('poll',{},p.token,'https://wrong.test')).status,403);assert.equal((await post('poll')).status,401);const info=await fetch(url+'/api/info').then(r=>r.json());assert.deepEqual(info.addresses,['https://test.trycloudflare.com']);}finally{app.server.closeAllConnections();await new Promise(r=>app.server.close(r));}});
test('tunnel URL extraction and download integrity reject invalid content',()=>{assert.equal(tunnelURL('https://hello-world.trycloudflare.com ready'),'https://hello-world.trycloudflare.com');assert.equal(tunnelURL('https://evil.example'),null);assert.equal(verify(Buffer.from('wrong'),'0'.repeat(64)),false);});
