import {ARENA_AGENTS,AGENT_BY_ID,MODES,VERSION,distance,direction,rayRect} from './arena-data.js';
import {ArenaEngine} from './arena-engine.js';
import {ArenaRoom} from './arena-peer.js';
import {ArenaView} from './arena-view.js';
import {ArenaControls} from './arena-controls.js';
import {ProfileStore,unlockedAgents,rewardCount} from './profile.js';
import {AudioFX} from './audio.js';
import {installUpdateBanner} from './platform.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class ArenaLobby {
 constructor(){this.profile=new ProfileStore();this.dimension='2d';this.agent=unlockedAgents(this.profile.read())[0]||'spidey';this.name='플레이어';this.options={mode:'ball',rounds:3,bots:true};this.audio=new AudioFX();this.home();window.arenaLobby=this;const lobby=this;installUpdateBanner({get mode(){return lobby.running?'play':'home';}});}
 shell(html){$('#ui').innerHTML=`<main class="arena-shell"><header><a href="./index.html" class="arena-brand"><span>AF</span><div>능력전선<small>ABILITY FRONT · ${VERSION}</small></div></a><span class="arena-build">LOCAL PLAY BETA</span></header>${html}<p id="arena-error" role="status"></p></main>`;}
 bind(selector,fn){const el=$(selector);if(el)el.onclick=async()=>{try{await fn();}catch(e){this.error(e);}};}
 error(e){const node=$('#arena-error');if(node)node.textContent=e.message||String(e);else this.message(e.message||String(e));}
 home(){if(!this.profile.read().starter&&!this.profile.read().allUnlocked){this.collection(true);return;}
  this.shell(`<section class="arena-home"><div class="arena-intro"><p class="arena-kicker">SAME HEROES. NEW RULES.</p><h1>어떤 전장으로<br><em>뛰어들까?</em></h1><p>내 손에 맞는 방식으로 플레이하세요.<br>요원 해금 기록은 두 전장에서 함께 사용됩니다.</p><div class="arena-home-actions"><button id="collection">요원 보관함 <b>${unlockedAgents(this.profile.read()).length} / 11</b></button><button id="guide">처음 플레이하나요?</button><button id="patch">업데이트 노트</button></div></div><div class="arena-dimensions"><button class="dimension-card mobile-world" data-dimension="2d"><span class="arena-card-top">01 / MOBILE FIRST <b>NEW</b></span><div class="dimension-art"><i></i><i></i><i></i><strong>2D</strong></div><h2>에모 아레나</h2><p>3칸 에모 · 쿨타임 스킬 · 피해로 궁극기 충전</p><footer>휴대폰 · PC <b>플레이 →</b></footer></button><button class="dimension-card tactical-world" data-dimension="3d"><span class="arena-card-top">02 / PC FIRST</span><div class="dimension-art"><i></i><i></i><i></i><strong>3D</strong></div><h2>전술 전선</h2><p>1인칭 · 스킬 횟수제 · 정교한 공간 전투</p><footer>PC 권장 · 모바일 지원 <b>플레이 →</b></footer></button></div></section><div class="arena-footer"><span>같은 Wi-Fi · PC 없이 휴대폰이 방장</span><span>2D와 3D는 밸런스가 달라 별도 방으로 진행됩니다.</span></div>`);
  document.querySelectorAll('[data-dimension]').forEach(b=>b.onclick=()=>{this.dimension=b.dataset.dimension;this.setup();});this.bind('#collection',()=>this.collection());this.bind('#guide',()=>this.guide());this.bind('#patch',()=>this.patchNotes());
 }
 patchNotes(){this.shell(`<section class="arena-guide"><button id="back">← 돌아가기</button><p class="arena-kicker">PATCH NOTES / ${VERSION}</p><h1>베타 업데이트 확인</h1><p>이 화면은 설치된 게임이 새 버전으로 바뀌었는지 바로 확인할 수 있는 업데이트 노트입니다.</p><h2>0.8.0-beta.2</h2><ol><li>메인 화면에 <b>업데이트 노트</b> 메뉴를 추가했습니다.</li><li>Windows 자동 업데이트 및 웹 앱 캐시 버전을 새 빌드로 올렸습니다.</li><li>2D 에모 아레나와 3D 전술 전선의 기존 진행 기록은 그대로 유지됩니다.</li></ol><p>상단의 <b>ABILITY FRONT · ${VERSION}</b> 표기가 보이면 업데이트가 성공한 것입니다.</p></section>`);this.bind('#back',()=>this.home());}
 guide(){this.shell('<section class="arena-guide"><button id="back">← 돌아가기</button><h1>휴대폰만으로 같이 플레이</h1><ol><li>모두 같은 Wi-Fi에 연결하고, HTTPS로 배포된 같은 버전 게임을 엽니다.</li><li>한 명이 모드와 요원을 선택한 뒤 <b>Wi-Fi 방 만들기</b>를 누릅니다.</li><li>방장이 <b>친구 초대</b>로 만든 긴 코드를 친구에게 보냅니다.</li><li>친구는 <b>Wi-Fi 방 참가</b>에 코드를 붙여넣고, 생성된 <b>응답 코드</b>를 방장에게 돌려보냅니다.</li><li>방장이 응답 코드를 입력합니다. 친구마다 새 초대가 필요합니다. 모두 연결되면 게임 시작!</li></ol><p>공용 서버 없이 연결하기 때문에 첫 연결은 코드를 한 번씩 주고받습니다. 방장 화면을 켜 두세요. 공유기 AP 격리, 게스트 Wi-Fi, 브라우저의 로컬 연결 제한이 있으면 실패할 수 있습니다. 다른 네트워크 연결이나 자동 방 검색은 지원하지 않습니다.</p><h2>2D 조작</h2><p>왼쪽 스틱: 이동 · 공격/스킬 버튼을 끌어 조준하고 놓아 사용 · 짧게 누르면 자동 조준.<br>PC: WASD 이동, 마우스로 조준, 좌클릭 공격, Q/E/C/R 홀드 후 놓기, F 홀드 상호작용, G 폭탄 내려놓기.<br>에모는 기본 공격 한 번에 1칸 사용하고, 한 칸씩 자동 충전됩니다. 총 스킬 8발은 별도 스킬 상태입니다.</p><h2>설치와 저장</h2><p>Windows는 START-WINDOWS.bat 또는 설치 앱으로 실행합니다. iPhone/Android는 배포된 HTTPS 주소를 Safari/Chrome에서 열어 홈 화면에 추가하세요. 소스 ZIP을 업로드해야 기존 앱/웹에 반영됩니다. 요원 기록은 기기·브라우저별 로컬 저장이며 클라우드 계정 동기화는 없습니다.</p></section>');this.bind('#back',()=>this.home());}
 collection(first=false){const p=this.profile.read(),count=rewardCount(p);this.shell(`<section class="arena-collection"><div class="arena-heading"><div><p class="arena-kicker">YOUR AGENTS</p><h1>${first?'첫 번째 요원을 선택하세요':'요원 보관함'}</h1><p>${first?'처음 선택한 한 명은 무료로 해금됩니다.':`해금권 ${count}개 · 던전 보스 클리어 또는 보너스 구역 2회 도달`}</p></div>${first?'':'<button id="back">← 돌아가기</button>'}</div><div class="arena-roster">${ARENA_AGENTS.map(a=>`<button data-pick="${a.id}" style="--hero:${a.color}" ${!first&&!this.profile.owns(a.id)&&!count?'disabled':''}><span class="hero-glyph">${a.name.slice(0,1)}</span><strong>${a.name}</strong><small>${a.role}</small><em>${this.profile.owns(a.id)?'해금됨':first?'첫 요원 선택':count?'해금권 사용':'잠김'}</em></button>`).join('')}</div>${!first?'<div class="arena-code"><input id="secret" type="password" autocomplete="off" placeholder="비밀코드"><button id="redeem">코드 적용</button><button id="dungeon">던전으로 해금권 얻기 →</button></div>':''}</section>`);document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{try{if(first){this.profile.starter(b.dataset.pick);this.agent=b.dataset.pick;this.home();}else if(!this.profile.owns(b.dataset.pick)){this.profile.unlock(b.dataset.pick);this.collection();}}catch(e){this.error(e);}});this.bind('#back',()=>this.home());this.bind('#redeem',async()=>{await this.profile.redeem($('#secret').value);this.collection();});this.bind('#dungeon',()=>this.legacy());}
 legacy(){location.href=new URL('./index.html?legacy=1',location.href).href;}
 setup(){const owned=unlockedAgents(this.profile.read());if(!owned.includes(this.agent))this.agent=owned[0];this.shell(`<section class="arena-setup"><div class="arena-heading"><div><p class="arena-kicker">${this.dimension==='2d'?'AMMO ARENA':'TACTICAL FRONT'} / 5 V 5</p><h1>전투 준비</h1></div><button id="back">← 전장 선택</button></div><div class="arena-mode-list">${Object.entries(MODES).map(([id,m],i)=>`<button data-mode="${id}" class="${this.options.mode===id?'selected':''}"><span>0${i+1}</span><h3>${m.name}</h3><p>${m.detail}</p></button>`).join('')}</div><div class="arena-loadout"><div class="arena-options"><label>플레이어 이름<input id="player-name" maxlength="20" value="${esc(this.name)}"></label><label>팀<select id="team"><option value="A">A팀 · 공격 / 파랑</option><option value="B">B팀 · 수비 / 빨강</option></select></label><label>진행 라운드<input type="number" id="rounds" min="1" max="99" value="${this.options.rounds}" ${['ball','big'].includes(this.options.mode)?'disabled':''}></label><label class="arena-check"><input id="bots" type="checkbox" ${this.options.bots?'checked':''}> 빈자리에 연습 AI 추가 (총 10명)</label>${this.dimension==='3d'?'<label class="arena-check"><input id="unlimited" type="checkbox"> Q/E/C 횟수 무한 (궁극기 제외)</label>':'<p class="arena-rule-note">에모 3칸 · 스킬 쿨타임<br>궁극기는 실제로 입힌 피해로 충전<br>파괴 가능 : 불가 엄폐물 = 8 : 2</p>'}<div class="arena-hero-detail"></div></div><div><h2>요원 선택 <small>해금한 요원만 선택 가능</small></h2><div class="arena-agent-picker">${ARENA_AGENTS.map(a=>`<button data-agent="${a.id}" class="${a.id===this.agent?'selected':''}" style="--hero:${a.color}" ${!owned.includes(a.id)?'disabled':''}><span>${owned.includes(a.id)?a.name.slice(0,1):'🔒'}</span><strong>${a.name}</strong><small>${a.role}</small></button>`).join('')}</div></div></div><div class="arena-launch"><button id="solo" class="arena-primary">혼자 시작 →</button><button id="host">Wi-Fi 방 만들기</button><button id="join">Wi-Fi 방 참가</button>${this.dimension==='3d'?'<button id="legacy">기존 훈련 · 사용자설정 · 던전</button>':''}</div><p class="arena-muted">일반전: 유실된 중정 · 다른 모드: 네온 연구 정원 / 빅 에이전트는 1 대 9 / 방장은 게임 중 화면을 켜 두세요.</p></section>`);
  this.updateAgent();document.querySelectorAll('[data-agent]').forEach(b=>b.onclick=()=>{this.agent=b.dataset.agent;document.querySelectorAll('[data-agent]').forEach(el=>el.classList.toggle('selected',el===b));this.updateAgent();});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{this.capture();this.options.mode=b.dataset.mode;this.setup();});this.bind('#back',()=>this.home());this.bind('#legacy',()=>this.legacy());this.bind('#solo',async()=>{this.capture();this.makeRoom(true);await this.start();});this.bind('#host',()=>{this.capture();this.makeRoom(true);this.roomScreen();});this.bind('#join',()=>{this.capture();this.makeRoom(false);this.joinScreen();});}
 updateAgent(){const a=AGENT_BY_ID[this.agent],node=$('.arena-hero-detail');if(node)node.innerHTML=`<strong style="color:${a.color}">${a.name}</strong><p>${a.skills.map((s,i)=>`<span>${['Q','E','C','R'][i]} ${s}${i<3&&this.dimension==='2d'?' · '+a.cooldowns[i]+'초':''}</span>`).join('')}</p><small>${this.dimension==='2d'?`에모 ${a.ammo}칸 · 1칸 충전 ${a.reload}초 · 궁극기 ${a.ultCost} 피해`:''}</small><p>${a.ball}</p>`;}
 capture(){this.name=$('#player-name')?.value.trim()||this.name;this.team=$('#team')?.value||'A';this.options={...this.options,rounds:Math.min(99,Math.max(1,Math.floor(+$('#rounds')?.value||3))),bots:$('#bots')?.checked??true,unlimited:!!$('#unlimited')?.checked,dimension:this.dimension};if(this.options.mode==='big')this.options.rounds=1;}
 makeRoom(host){this.room?.close();this.room=new ArenaRoom({host,player:{name:this.name,agent:this.agent,team:this.team},options:this.options,onchange:s=>{this.options=s.options;this.dimension=s.options.dimension;this.updateRoom();},onsnapshot:s=>this.receive(s),oninput:(id,data)=>this.engine?.input(id,data),onstatus:(status,id)=>{const el=$('#peer-status');if(el)el.textContent=status==='open'?'연결 완료':status==='failed'?'연결 실패 · 같은 Wi-Fi와 공유기 격리를 확인하세요.':status==='host-left'?'방장 연결이 종료되었습니다.':'연결 상태: '+status;if(status==='host-left')this.message('방장 연결이 종료되었습니다. 모드 선택으로 돌아가세요.');if(this.room?.host&&['closed','failed'].includes(status))this.engine?.disconnect(id);}});}
 updateRoom(){const box=$('#room-players');if(box&&this.room)box.innerHTML=this.room.players.map(p=>`<div><i style="background:${AGENT_BY_ID[p.agent]?.color}"></i><strong>${esc(p.name)}</strong><span>${p.team}팀 · ${AGENT_BY_ID[p.agent]?.name||'요원'}</span><b>${p.connected?'연결됨':'연결 끊김'}</b></div>`).join('');const info=$('#room-title');if(info)info.textContent=`${this.dimension.toUpperCase()} · ${MODES[this.options.mode]?.name||''} · ${this.room.players.filter(p=>p.connected).length} / 10명`;}
 roomScreen(){this.shell('<section class="arena-room"><div class="arena-heading"><div><p class="arena-kicker">LOCAL WI-FI ROOM / HOST</p><h1 id="room-title"></h1></div><button id="leave">← 방 나가기</button></div><div id="room-players"></div><p id="peer-status">친구를 초대하거나 혼자 시작할 수 있어요.</p><div class="arena-launch"><button id="start" class="arena-primary">게임 시작 →</button><button id="invite">친구 초대</button></div><div id="pair-panel"></div><p class="arena-muted">친구마다 새 초대 코드가 필요합니다. 연결 뒤에는 PC나 외부 게임 서버를 쓰지 않습니다.</p></section>');this.updateRoom();this.bind('#leave',()=>{this.room.close();this.setup();});this.bind('#start',()=>this.start());this.bind('#invite',async()=>{const b=$('#invite');b.disabled=true;try{this.invitation=await this.room.invite();$('#pair-panel').innerHTML='<h2>1. 이 초대 코드를 친구에게 보내세요</h2><textarea id="offer-code" readonly rows="3"></textarea><button id="copy-offer">초대 코드 복사</button><h2>2. 친구에게 받은 응답 코드</h2><textarea id="answer-code" rows="3" placeholder="AF8. 응답 코드 붙여넣기"></textarea><button id="accept-answer">응답 적용 · 연결</button>';$('#offer-code').value=this.invitation.code;this.bind('#copy-offer',()=>this.copy('#offer-code'));this.bind('#accept-answer',async()=>{await this.room.accept(this.invitation.id,$('#answer-code').value);$('#peer-status').textContent='연결 중… 두 기기를 같은 Wi-Fi에 유지하세요.';});}finally{b.disabled=false;}});}
 joinScreen(){this.shell('<section class="arena-room"><p class="arena-kicker">LOCAL WI-FI ROOM / JOIN</p><h1>친구의 방에 참가</h1><p>방장에게 받은 긴 초대 코드를 넣으세요. 같은 Wi-Fi에 연결되어 있어야 합니다.</p><textarea id="join-offer" rows="4" placeholder="AF8. 초대 코드 붙여넣기"></textarea><button id="make-answer" class="arena-primary">응답 코드 만들기</button><button id="leave">← 돌아가기</button><div id="join-answer-panel"></div><h2 id="room-title"></h2><div id="room-players"></div><p id="peer-status"></p></section>');this.bind('#leave',()=>{this.room.close();this.setup();});this.bind('#make-answer',async()=>{const code=await this.room.join($('#join-offer').value);$('#join-answer-panel').innerHTML='<h2>이 응답 코드를 방장에게 보내세요</h2><textarea id="join-answer" readonly rows="4"></textarea><button id="copy-answer">응답 코드 복사</button><p>방장이 응답을 적용하고 시작하면 자동 입장합니다.</p>';$('#join-answer').value=code;this.bind('#copy-answer',()=>this.copy('#join-answer'));$('#make-answer').disabled=true;});}
 async copy(selector){const el=$(selector);try{await navigator.clipboard.writeText(el.value);this.error('복사했습니다. 친구에게 보내세요.');}catch{el.focus();el.select();this.error('코드가 선택되었습니다. 길게 눌러 복사하세요.');}}
 async start(){if(!this.room.host||this.starting)return;this.starting=true;try{const players=this.room.players.filter(p=>p.connected);if(!players.length)throw Error('연결된 플레이어가 없습니다.');if(!this.options.bots&&players.length>1&&!['A','B'].every(t=>players.some(p=>p.team===t)))throw Error('양 팀에 최소 한 명씩 필요합니다.');this.audio.start();await this.landscape();
   if(this.dimension==='2d')this.engine=new ArenaEngine(this.options,players);else {const {Arena3DEngine}=await import('./arena-3d.js');const roster=[...players];if(this.options.bots)while(roster.length<10){const counts={A:0,B:0};for(const p of roster)counts[p.team]++;const i=roster.length;roster.push({id:'bot'+i,name:'훈련 AI '+i,team:counts.A<=counts.B?'A':'B',agent:ARENA_AGENTS[i%11].id,bot:true});}this.engine=new Arena3DEngine(this.options,roster);}
   this.room.start();await this.receive(this.engine.snapshot());this.loopStart();
  }finally{this.starting=false;}}
 async landscape(){try{await screen.orientation?.lock?.('landscape');}catch{}try{this.wake=await navigator.wakeLock?.request('screen');}catch{}}
 async receive(snapshot){this.lastReceived=performance.now();this.state=snapshot;if(this.loadingView){this.queuedState=snapshot;return;}if(!this.view){this.loadingView=true;try{document.body.classList.add('arena-playing',this.dimension==='2d'?'playing-2d':'playing-3d');$('#ui').innerHTML='';if(this.dimension==='2d'){const old=$('#game'),canvas=old.cloneNode(false);old.replaceWith(canvas);this.view=new ArenaView(canvas,this.room.id);this.controls=new ArenaControls(canvas,{worldPoint:(x,y)=>this.view.worldPoint(x,y),autoAim:()=>this.autoAim(),onmenu:()=>this.menu(),onchoice:(kind,done)=>this.choice(kind,done)});}else {const {ArenaThreeView}=await import('./arena-three-view.js');this.view=new ArenaThreeView(this.room.id,snapshot,{input:d=>this.room.input(d),exit:()=>this.exit()});}if(!this.room.host){await this.landscape();this.loopStart();}}finally{this.loadingView=false;}}this.view.receive(snapshot);if(this.controls)this.controls.update(snapshot.players.find(p=>p.id===this.room.id));if(this.queuedState){const queued=this.queuedState;this.queuedState=null;this.view.receive(queued);}this.sounds(snapshot);}
 autoAim(){const a=this.state?.players.find(p=>p.id===this.room.id);if(!a)return null;const target=this.state.players.filter(p=>!p.dead&&p.team!==a.team&&p.phase<=0&&this.state.map&&!this.state.map.walls.some(w=>w.hp>0&&rayRect(a,p,w)!==null)&&(!this.state.map.bushes.some(b=>Math.abs(p.x-b.x)<b.w/2&&Math.abs(p.y-b.y)<b.h/2)||distance(a,p)<2.4||(p.revealedUntil||0)>this.state.time)).sort((x,y)=>distance(a,x)-distance(a,y))[0];return target?direction(target.x-a.x,target.y-a.y):null;}
 loopStart(){if(this.running)return;this.running=true;this.lastFrame=performance.now();this.acc=0;this.netAcc=0;const frame=now=>{if(!this.running)return;const dt=Math.min(.1,(now-this.lastFrame)/1000);this.lastFrame=now;this.acc+=dt;this.netAcc+=dt;if(this.controls&&this.netAcc>=1/30)this.room.input(this.controls.sample());if(this.engine){let steps=0;while(this.acc>=1/30&&steps++<4){this.engine.tick(1/30);this.acc-=1/30;}if(this.netAcc>=1/15){const state=this.engine.snapshot();this.receive(state);this.room.snapshot(state);this.netAcc=0;}}else {this.acc=0;if(this.netAcc>=1/30)this.netAcc=0;}
    if(this.dimension==='2d')this.view?.draw(now,this.controls?.aiming,this.controls?.aim);if(!this.room.host&&now-this.lastReceived>10000&&!this.connectionNotice){this.connectionNotice=true;this.message('방장 응답이 없습니다. 방장이 게임 화면을 다시 열어야 합니다.');}if(this.state?.phase==='done'&&!this.endShown){this.endShown=true;this.message('경기가 종료되었습니다. 모드 선택으로 돌아가 새 경기를 시작하세요.');}this.raf=requestAnimationFrame(frame);};this.raf=requestAnimationFrame(frame);}
 sounds(s){if(this.dimension!=='2d')return;const map={attack:'punch',skill:'launch',hit:'hit',kill:'kill',wall:'explode',goal:'roomClear',victory:'roomClear',ultimate:'ult',absorb:'shield',warning:'beep',lightning:'electric',kick:'launch',catch:'buy'};for(const e of s.events){if(e.id<=(this.eventId||0))continue;this.eventId=e.id;if(map[e.kind])this.audio.play(map[e.kind],e.kind==='hit'?.2:.4);}}
 dialog(html){$('#ui').innerHTML=`<div class="arena-dialog-back"><section class="arena-dialog">${html}<p id="arena-error" role="status"></p></section></div>`;if(this.controls){this.controls.clear();this.controls.suspended=true;}}
 closeDialog(){if(this.controls)this.controls.suspended=false;$('#ui').innerHTML='';this.audio.start();}
 menu(){if(this.dimension!=='2d')return;this.dialog('<p class="arena-kicker">FIELD SETTINGS</p><h2>전장 메뉴</h2><p>이 화면에서도 경기는 계속됩니다.</p><button id="resume" class="arena-primary">계속 플레이</button><button id="hud-edit">버튼 크기 · 위치 편집</button><button id="drop-bomb">설치 폭탄 내려놓기</button><label>효과음 <input id="volume" type="range" min="0" max="1" step=".05" value="'+this.audio.volume+'"></label><button id="exit">모드 선택으로 나가기</button>');this.bind('#resume',()=>this.closeDialog());this.bind('#hud-edit',()=>{this.closeDialog();this.controls.edit();});this.bind('#drop-bomb',()=>{this.controls.actions.push({type:'drop'});this.closeDialog();});this.bind('#exit',()=>this.exit());$('#volume').oninput=e=>this.audio.volume=+e.target.value;}
 choice(kind,done){let choices=kind==='size'?[['large','5배 커지기 · 체력 ↑'],['small','0.2배 작아지기 · 체력 ↓']]:kind==='arrow'?[['stun','스턴 화살'],['explosive','폭발 화살']]:ARENA_AGENTS.filter(a=>a.id!=='widow').flatMap(a=>a.skills.slice(0,3).map((s,i)=>[a.id+':'+['Q','E','C'][i],a.name+' · '+s]));this.dialog('<h2>'+({size:'크기 변경',arrow:'특수 화살',copy:'스파이 · 70% 성능'}[kind])+'</h2><div class="arena-choice-grid">'+choices.map(([id,label])=>`<button data-choice="${id}">${label}</button>`).join('')+'</div><button id="cancel">취소</button>');document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{this.closeDialog();done(b.dataset.choice);});this.bind('#cancel',()=>this.closeDialog());}
 message(text){if(!this.view){this.error(new Error(text));return;}if(this.dimension==='3d'){this.view.g.notify(text,8);return;}this.dialog('<h2>알림</h2><p>'+esc(text)+'</p><button id="resume">닫기</button><button id="exit">모드 선택으로</button>');this.bind('#resume',()=>this.closeDialog());this.bind('#exit',()=>this.exit());}
 exit(){this.running=false;cancelAnimationFrame(this.raf);this.room?.close();this.controls?.dispose();this.view?.dispose();this.wake?.release?.();location.href=new URL('./index.html',location.href).href;}
}
