import {Simulation} from './simulation-core.js';
import {Game} from './game.js';
import {MatchRules} from './match-rules.js';
import {V} from './physics.js';
import {MODES,AGENT_BY_ID,rayRect} from './arena-data.js';

class ArcadeRules extends MatchRules {
 constructor(options,sites,sim){super(options,sites);this.sim=sim;this.mode=options.mode;this.time=3;}
 step(dt,players){if(this.phase==='done')return;if(this.phase==='result'){this.time-=dt;if(this.time<=0){if(this.mode==='ball'&&Math.max(this.score.A,this.score.B)<2){const left=this.savedTime;this.nextRound();this.time=3;this.savedTime=left;return 'round';}if(this.round>=this.options.rounds||this.mode==='ball')this.phase='done';else {this.nextRound();this.time=3;return 'round';}}return;}
  if(this.phase==='buy'){this.time-=dt;if(this.time<=0){this.phase='live';this.time=this.savedTime??MODES[this.mode].seconds;}return;}
  this.time-=dt;const A=players.filter(p=>p.alive&&p.team==='A'),B=players.filter(p=>p.alive&&p.team==='B');if(this.mode==='elimination'){if(!A.length||!B.length)this.finish(A.length?'A':B.length?'B':null,'전멸');}
  if(this.mode==='big'){if(this.sim.actors.get(this.sim.bossId)?.dead)this.finish('B','빅 에이전트 처치');else if(this.time<=0)this.finish('A','빅 에이전트 생존');}
  if(this.mode==='ball'&&this.time<=0){this.result={team:this.score.A===this.score.B?null:this.score.A>this.score.B?'A':'B',reason:'시간 종료'};this.phase='done';}
 }
 role(team){return team==='A'?'attack':'defend';}
 snapshot(){return {...super.snapshot(),mode:this.mode,overtime:this.mode==='elimination'&&this.time<=0};}
}
export class Arena3DEngine extends Simulation {
 constructor(options,players){const normalized={...options,rounds:Math.max(1,options.rounds||3),map:options.mode==='standard'?'arena-wide':'arena-sport',unlimited:!!options.unlimited};const room={options:normalized,players:new Map(players.map(p=>[p.id,{...p,connected:true}]))};super(room);this.mode=options.mode;this.bossId=this.mode==='big'?players[Math.floor(Math.random()*players.length)]?.id:null;
  if(this.mode!=='standard')this.rules=new ArcadeRules(normalized,this.world.map.sites,this);if(this.bossId)for(const [id,p] of room.players)p.team=id===this.bossId?'A':'B';this.economy=this.mode==='standard'&&!normalized.unlimited;
  for(const a of this.actors.values())this.configureActor(a);this.resetRound();
 }
 configureActor(a){a.damageTotal=0;const original={tickPlayer:a.tickPlayer,tickExpansion:a.tickExpansion,outgoing:a.outgoing,gainUlt:a.gainUlt,melee:a.melee,area:a.area,use:a.use};
  a.outgoing=n=>original.outgoing.call(a,n)*(a.id===this.bossId?1.6:1);
  a.tickExpansion=dt=>{original.tickExpansion.call(a,dt);if(a.id===this.bossId)a.moveScale*=.72;};
  a.melee=(n,r,...rest)=>original.melee.call(a,n,r*(a.id===this.bossId?1.4:1),...rest);
  a.area=(p,r,...rest)=>original.area.call(a,p,r*(a.id===this.bossId?1.4:1),...rest);
  a.gainUlt=reason=>{if(a.id!==this.bossId)return original.gainUlt.call(a,reason);a.ultFraction=(a.ultFraction||0)+.55;if(a.ultFraction>=1){a.ultFraction--;original.gainUlt.call(a,reason);}};
  a.use=i=>{if(a.id!==this.bossId)return original.use(i);a.bigCooldowns??=[0,0,0];if(a.bigCooldowns[i]>0)return false;a.bigCooldowns[i]=AGENT_BY_ID[a.agent.id].cooldowns[i]*.7;return true;};
 }
 resetRound(){super.resetRound();this.ball={pos:[0,.5,0],velocity:[0,0,0],holder:null,power:null,owner:null,team:null,until:0,grace:0,pass:false,bounces:0};for(const a of this.actors.values()){a.respawnAt=0;a.bigCooldowns=[0,0,0];if(a.id===this.bossId){a.maxHP*=8;a.hp=a.maxHP;a.bodyScale=1.9;a.player.h.multiplyScalar(1.9);a.player.p.y=a.player.h.y;a.player.hp=a.hp;}}if(this.mode!=='standard')this.rules.spike.dropped=null;}
 recordDeath(a,source){Simulation.prototype.recordDeath.call(this,a,source);if(this.mode==='ball'||this.mode==='big'&&a.id!==this.bossId)a.respawnAt=this.time+5;if(this.ball?.holder===a.id)this.kick(a,false);}
 input(id,data){const a=this.actors.get(id);if(a&&this.mode==='ball'&&this.ball.holder===id&&(data.actions||[]).some(e=>e.type==='attack')&&!a.dead&&a.stun<=0){this.kick(a);data={...data,actions:data.actions.filter(e=>e.type!=='attack')};}super.input(id,data);}
 bots(){for(const a of this.actors.values()){if(!this.room.players.get(a.id)?.bot||a.dead||this.time<(a.botThink||0))continue;a.botThink=this.time+.18;const foes=[...this.actors.values()].filter(b=>b.team!==a.team&&!b.dead).sort((x,y)=>a.player.p.distanceToSquared(x.player.p)-a.player.p.distanceToSquared(y.player.p));const enemy=foes[0];let target=enemy?.player.p||V();if(this.mode==='ball'){target=this.ball.holder===a.id?V(0,.9,(a.team==='A'?1:-1)*this.world.map.spawn):V(...this.ball.pos);}if(this.mode==='standard'){const s=this.rules.spike;if(s.state==='planted')target=V(s.position.x,.9,s.position.z);else if(s.carrier===a.id){const site=this.world.map.sites[a.id.length%2];target=V(site.x,.9,site.z);}else if(this.rules.role(a.team)==='attack'&&s.dropped)target=V(s.dropped.x,.9,s.dropped.z);}
   const delta=target.clone().sub(a.player.p),dist=delta.length(),aim=(enemy&&a.player.p.distanceTo(enemy.player.p)<16?enemy.player.p:target).clone().sub(a.player.p),yaw=Math.atan2(-aim.x,-aim.z),forward=delta.clone().applyAxisAngle(V(0,1,0),-yaw);let keys=dist>2?[forward.z<0?'KeyW':'KeyS',forward.x<-.5?'KeyA':forward.x>.5?'KeyD':null].filter(Boolean):[];if(dist<4)keys.push('KeyF');const actions=[];if(enemy&&a.player.p.distanceTo(enemy.player.p)<(a.agent.id==='arc'?25:3)){actions.push({type:'attack',button:a.agent.id==='arc'?2:0});}if(this.mode==='ball'&&this.ball.holder===a.id&&dist<16)actions.push({type:'attack',button:0});if(this.time>(a.botSkillAt||0)){actions.push({type:'skill',key:['Q','E','C'][Math.floor(this.time+a.id.length)%3]});if(a.ultReady)actions.push({type:'skill',key:'R'});a.botSkillAt=this.time+3;}if(a.charge)actions.push({type:'releaseQ',key:'Q'});if(a.menu==='size')actions.push({type:'chooseSize',value:'large'});if(a.menu==='arrow')actions.push({type:'chooseArrow',value:1});if(a.menu==='copy')actions.push({type:'copy',agent:'spidey',key:'Q'});if(a.wallPreview)actions.push({type:'skill',key:'C'});if(a.equipped==='bomb'||a.equipped==='web'||a.scope)actions.push({type:'attack',button:0});if(this.rules.phase==='buy')actions.push({type:'buy',item:'all'});this.input(a.id,{keys,yaw,pitch:0,actions});}}
 respawn(a){const kills=a.kills,points=a.ultPoints;Game.prototype.reset.call(a,false);a.kills=kills;a.ultPoints=points;a.ultReady=points>=a.ultCost;a.mode='play';a.player.active=true;a.player.mesh.visible=true;a.bank.fill();a.armor=50;a.player.p.fromArray(this.world.spawn(this.rules.role(a.team),[...this.actors.values()].filter(b=>b.team===a.team).indexOf(a)));a.player.hp=a.hp;a.yaw=a.team==='A'?Math.PI:0;a.pitch=0;a.respawnAt=0;a.root=a.stun=a.dot=0;a.player.root=a.player.stun=a.player.dot=0;this.corpses=this.corpses.filter(c=>c.id!==a.id);this.camera(a);this.event({kind:'respawn',target:a.id,at:this.time});}
 kick(a,shoot=true){const b=this.ball,dir=a.direction();b.holder=null;b.owner=a.id;b.team=a.team;b.pos=[a.player.p.x+dir.x*.9,.5,a.player.p.z+dir.z*.9];const speed=shoot?(a.agent.id==='arc'?23:18):0;b.velocity=[dir.x*speed,0,dir.z*speed];b.power=a.agent.id;b.until=this.time+2;b.grace=this.time+.35;b.pass=false;b.bounces=0;}
 tickBall(dt){const b=this.ball,h=this.actors.get(b.holder),m=this.world.map;if(h&&!h.dead){b.pos=[h.player.p.x,h.player.p.y,h.player.p.z];b.power=h.agent.id;b.until=this.time+2;return;}const active=b.until>this.time,start={x:b.pos[0],y:b.pos[2]},next={x:b.pos[0]+b.velocity[0]*dt,y:b.pos[2]+b.velocity[2]*dt};let hit=null;for(const w of this.physics.solids){if(!w.active||w.p.y-w.h.y>1)continue;const t=rayRect(start,next,{x:w.p.x,y:w.p.z,w:w.h.x*2,h:w.h.z*2},.35);if(t!==null&&(!hit||t<hit.t))hit={w,t};}
  if(hit){const w=hit.w;if(active&&['bane','vision'].includes(b.power)&&w.destructible&&!b.pass){b.pass=true;if(b.power==='bane'){w.active=false;w.mesh.visible=false;b.velocity=b.velocity.map(n=>n*.6);}}else if(active&&b.power==='cap'&&b.bounces<1){b.velocity[0]*=-1;b.velocity[2]*=-1;b.bounces++;}else b.velocity=[0,0,0];}else {b.pos[0]=next.x;b.pos[2]=next.y;}
  const drag=active&&b.power==='pigeon'?.65:1;b.velocity=b.velocity.map(n=>n*Math.exp(-dt*drag));
  for(const team of ['A','B'])if(Math.abs(b.pos[0])<7&&Math.abs(b.pos[2]-(team==='A'?-m.spawn:m.spawn))<1.8){const winner=team==='A'?'B':'A';this.rules.savedTime=this.rules.time;this.rules.finish(winner,'골!');return;}
  for(const a of this.actors.values()){if(a.dead||a.phased>0||a.id===b.owner&&this.time<b.grace)continue;if(Math.hypot(a.player.p.x-b.pos[0],a.player.p.z-b.pos[2])>(active&&b.power==='ant'?.7:1.2))continue;const owner=this.actors.get(b.owner);if(active&&owner&&a.team!==owner.team&&Math.hypot(...b.velocity)>3){if(b.power==='spidey')a.player.slow=.6;if(b.power==='thor')a.player.stun=.25;if(b.power==='widow'){a.player.dot=2;a.player.dotDamage=3;a.dotSource=owner;}if(b.power==='panther')a.player.v.addScaledVector(V(...b.velocity).normalize(),5);}if(active&&b.power==='hera'&&owner?.team===a.team&&owner.id!==a.id)a.hp=Math.min(a.maxHP,a.hp+12);b.holder=a.id;b.owner=a.id;b.team=a.team;b.velocity=[0,0,0];b.power=a.agent.id;b.until=this.time+2;break;}
 }
 tick(dt){this.bots();const oldHP=new Map([...this.actors.values()].map(a=>[a.id,a.hp]));super.tick(dt);if(this.rules.phase!=='live')return;for(const a of this.actors.values()){if(a.dead&&a.connected&&a.respawnAt&&this.time>=a.respawnAt){this.respawn(a);continue;}if(!a.dead&&a.player.p.y<-12){a.hp=0;a.dead=true;a.player.active=false;a.player.mesh.visible=false;this.recordDeath(a,null);}if(a.bigCooldowns)a.bigCooldowns=a.bigCooldowns.map(n=>Math.max(0,n-dt));if(this.mode==='elimination'&&this.rules.time<=0&&!a.dead){a.hp=Math.max(0,Math.min(a.hp,oldHP.get(a.id))-dt);a.player.hp=a.hp;if(a.hp<=1e-7){a.dead=true;a.player.active=false;a.player.mesh.visible=false;this.recordDeath(a,null);}}}
  if(this.mode==='ball')this.tickBall(dt);
 }
 snapshot(){const s=super.snapshot();s.arcade={mode:this.mode,bossId:this.bossId,ball:this.mode==='ball'?this.ball:null};for(const p of s.players){const a=this.actors.get(p.id);p.respawnAt=a.respawnAt||0;p.bigCooldowns=a.bigCooldowns;}return s;}
}
