import {AGENT_BY_ID,MODES,distance,inRect,clamp} from './arena-data.js';
const TAU=Math.PI*2;
export class ArenaView {
 constructor(canvas,id){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.id=id;this.camera={x:0,y:0};this.smooth=new Map();this.last=0;this.resize();this.hud=document.createElement('div');this.hud.className='arena-match-hud';this.hud.innerHTML='<div class="arena-score"></div><div class="arena-hero-hud"></div><div class="arena-notice"></div><div class="arena-feed"></div>';document.body.append(this.hud);}
 resize(){this.w=innerWidth;this.h=innerHeight;const dpr=devicePixelRatio||1;this.canvas.width=Math.round(this.w*dpr);this.canvas.height=Math.round(this.h*dpr);this.canvas.style.width='100%';this.canvas.style.height='100%';this.dpr=dpr;this.unit=Math.min(this.w/28,this.h/18);}
 worldPoint(x,y){return {x:(x-this.w/2)/this.unit+this.camera.x,y:(y-this.h/2)/this.unit+this.camera.y};}
 receive(state){this.state=state;this.me=state.players.find(a=>a.id===this.id);}
 circle(x,y,r,color,stroke=null,line=.07){const c=this.ctx;c.beginPath();c.arc(x,y,r,0,TAU);if(color){c.fillStyle=color;c.fill();}if(stroke){c.strokeStyle=stroke;c.lineWidth=line;c.stroke();}}
 rect(x,y,w,h,color){this.ctx.fillStyle=color;this.ctx.fillRect(x-w/2,y-h/2,w,h);}
 draw(now,aiming,aim){if(!this.state||!this.me)return;if(this.w!==innerWidth||this.h!==innerHeight)this.resize();const s=this.state,c=this.ctx,me=this.me,dt=Math.min(.1,(now-this.last)/1000||.016);this.last=now;const follow=me.dead?s.players.find(a=>a.team===me.team&&!a.dead)||me:me;
  this.camera.x+=(follow.x-this.camera.x)*(1-Math.exp(-dt*14));this.camera.y+=(follow.y-this.camera.y)*(1-Math.exp(-dt*14));const halfX=this.w/this.unit/2,halfY=this.h/this.unit/2;this.camera.x=clamp(this.camera.x,-s.map.w/2+halfX,s.map.w/2-halfX);this.camera.y=clamp(this.camera.y,-s.map.h/2+halfY,s.map.h/2-halfY);
  c.setTransform(this.dpr,0,0,this.dpr,0,0);c.fillStyle='#111f2c';c.fillRect(0,0,this.w,this.h);c.translate(this.w/2,this.h/2);c.scale(this.unit,this.unit);c.translate(-this.camera.x,-this.camera.y);
  const left=this.camera.x-halfX-3,right=this.camera.x+halfX+3,top=this.camera.y-halfY-3,bottom=this.camera.y+halfY+3,visible=r=>r.x+(r.w||2)/2>left&&r.x-(r.w||2)/2<right&&r.y+(r.h||2)/2>top&&r.y-(r.h||2)/2<bottom;
  this.rect(0,0,s.map.w,s.map.h,'#314d5b');c.lineWidth=.025;c.strokeStyle='#3c5c69';for(let x=Math.floor(left/2)*2;x<right;x+=2){c.beginPath();c.moveTo(x,Math.max(top,-s.map.h/2));c.lineTo(x,Math.min(bottom,s.map.h/2));c.stroke();}for(let y=Math.floor(top/2)*2;y<bottom;y+=2){c.beginPath();c.moveTo(Math.max(left,-s.map.w/2),y);c.lineTo(Math.min(right,s.map.w/2),y);c.stroke();}
  c.strokeStyle='#8ec1b047';c.lineWidth=.12;c.strokeRect(-s.map.w/2+.2,-s.map.h/2+.2,s.map.w-.4,s.map.h-.4);c.setLineDash([.25,.3]);c.strokeStyle='#a1b2bd30';c.beginPath();c.moveTo(0,-s.map.h/2);c.lineTo(0,s.map.h/2);c.stroke();c.setLineDash([]);
  for(const pit of s.map.pits)if(visible(pit)){this.rect(pit.x,pit.y,pit.w+.35,pit.h+.35,'#79bce0');this.rect(pit.x,pit.y,pit.w,pit.h,'#0a1426');c.strokeStyle='#928ac43d';c.lineWidth=.12;c.strokeRect(pit.x-pit.w/2+.3,pit.y-pit.h/2+.3,pit.w-.6,pit.h-.6);}
  if(s.options.mode==='standard')for(let i=0;i<s.map.sites.length;i++){const p=s.map.sites[i];this.circle(p.x,p.y,p.r,'#e8c67116','#e7c98760');this.text(i?'B':'A',p.x,p.y+.35,'#eddb96',1.2);}
  if(s.options.mode==='ball')for(const goal of s.map.goals){const color=goal.team===me.team?'#68c6ff':'#ff6d83';this.rect(goal.x,goal.y,goal.w,1.3,color+'35');for(let i=-3;i<=3;i++)this.rect(goal.x+i,goal.y,.04,1.1,color+'70');this.rect(goal.x,goal.y-.7,goal.w,.12,color);this.text(goal.team===me.team?'OUR GOAL':'ENEMY GOAL',goal.x,goal.y+(goal.y<0?1.4:-1.1),color,.36);}
  for(const bush of s.map.bushes)if(visible(bush)){this.rect(bush.x,bush.y,bush.w,bush.h,'#1d614f');for(let x=-bush.w/2+.3;x<bush.w/2;x+=.65)for(let y=-bush.h/2+.3;y<bush.h/2;y+=.7){c.fillStyle=(Math.round(x*10+y*10)%2)?'#418c68':'#34876a';c.beginPath();c.moveTo(bush.x+x-.3,bush.y+y+.3);c.lineTo(bush.x+x-.15,bush.y+y-.35);c.lineTo(bush.x+x+.08,bush.y+y-.02);c.lineTo(bush.x+x+.25,bush.y+y-.43);c.lineTo(bush.x+x+.3,bush.y+y+.3);c.fill();}}
  for(const f of s.fields)if(visible(f)){this.circle(f.x,f.y,f.r,f.kind==='fire'?'#ffad432d':f.kind==='web'?'#e7fcff28':'#f5625d20',f.kind==='trap'?'#fbb09b':'#d7eafa40');if(f.kind==='web'){c.lineWidth=.035;c.strokeStyle='#d9eef7aa';for(let i=0;i<8;i++){c.beginPath();c.moveTo(f.x,f.y);c.lineTo(f.x+Math.cos(i/8*TAU)*f.r,f.y+Math.sin(i/8*TAU)*f.r);c.stroke();}}}
  for(const corpse of s.corpses){this.circle(corpse.x,corpse.y,.48,'#111f26','#7c8b9390');this.text(AGENT_BY_ID[corpse.agent]?.name+' · '+corpse.name,corpse.x,corpse.y+.9,'#b4c3cb',.25);}
  if(aiming&&!me.dead)this.drawAim(me,aiming,aim);
  for(const w of s.map.walls)if(w.hp>0&&visible(w)){const color=w.dynamic?'#347c66':w.breakable?'#8c8472':'#526679';this.rect(w.x+.15,w.y+.22,w.w+.2,w.h+.15,'#142b3870');this.rect(w.x,w.y,w.w,w.h,color);this.rect(w.x,w.y-w.h/2-.13,w.w,.26,w.dynamic?'#72dfba':w.breakable?'#c4b18a':'#91afc1');this.rect(w.x+w.w/2-.08,w.y,.16,w.h,'#14263045');if(w.breakable){c.lineWidth=.04;c.strokeStyle='#5f5448';c.strokeRect(w.x-w.w/2+.12,w.y-w.h/2+.12,w.w-.24,w.h-.24);if(w.hp<100){c.beginPath();c.moveTo(w.x-.3,w.y-.3);c.lineTo(w.x+.05,w.y);c.lineTo(w.x-.2,w.y+.4);c.stroke();}}else{this.rect(w.x,w.y,.24,Math.min(w.h-.2,.8),'#a4c1cf66');}}
  const players=[...s.players].sort((a,b)=>a.y-b.y);for(const a of players){if(a.dead||!visible(a))continue;const enemy=a.team!==me.team;if(enemy&&(a.phase>0||(distance(me,a)>2.4&&s.map.bushes.some(b=>inRect(a,b))&&(a.revealedUntil||0)<s.time)))continue;let p=this.smooth.get(a.id);if(!p){p={x:a.x,y:a.y};this.smooth.set(a.id,p);}if(distance(p,a)>4){p.x=a.x;p.y=a.y;}else {p.x+=(a.x-p.x)*(1-Math.exp(-dt*20));p.y+=(a.y-p.y)*(1-Math.exp(-dt*20));}this.drawAgent({...a,x:p.x,y:p.y},enemy,a.id===me.id,now/1000);}
  for(const p of s.shots){if(!visible(p))continue;const height=p.lob?Math.sin(clamp(p.traveled/p.range,0,1)*Math.PI)*1.5:0;this.circle(p.x,p.y,.12,'#10283255');c.save();c.translate(p.x,p.y-height);c.rotate(Math.atan2(p.dy,p.dx));if(['arrow','knife','poisonKnife'].includes(p.kind)){this.rect(0,0,.6,.08,p.color);c.fillStyle='#f4f6ff';c.beginPath();c.moveTo(.4,0);c.lineTo(.15,-.15);c.lineTo(.15,.15);c.fill();}else if(p.kind==='shield'){this.circle(0,0,.38,p.color,'#e9fbff',.09);this.circle(0,0,.16,'#e9fbff');}else{this.circle(0,0,(p.r||.15)*2,p.color+'25');this.circle(0,0,p.r||.15,p.color,'#f4ffff',.035);}c.restore();}
  for(const soul of s.souls){const pulse=Math.sin(now/170+soul.id)*.04;this.circle(soul.x,soul.y-.3,.4+pulse,'#76f9d418');this.circle(soul.x,soul.y-.3,.19+pulse,'#aaffdf','#efffff');this.text((soul.expires-s.time).toFixed(1),soul.x,soul.y-.8,'#a7ffe0',.26);}
  if(s.options.mode==='standard'){const b=s.spike;if(b.state!=='defused'){const holder=s.players.find(a=>a.id===b.carrier),x=holder?holder.x:b.x,y=holder?holder.y-.9:b.y;this.rect(x,y,.55,.7,b.state==='planted'?'#ff8970':'#efd482');this.rect(x,y,.18,.4,'#405161');if(b.state==='planted')this.circle(x,y,.8+Math.sin(now/100)*.1,null,'#ffa383');}}
  if(s.options.mode==='ball'){const b=s.ball,p=s.players.find(a=>a.id===b.holder),x=p?p.x+p.aimX*.8:b.x,y=p?p.y+p.aimY*.8:b.y,col=b.powerUntil>s.time?AGENT_BY_ID[b.power]?.color:'#ffffff';this.circle(x,y,.62,null,col+'80',.1);this.circle(x,y,.38,'#f5f0d2','#182f40',.06);this.circle(x,y,.13,col);}
  for(const e of s.events)this.effect(e,s.time);
  if(now-(this.hudAt||0)>100){this.hudAt=now;this.drawHud();}
 }
 text(text,x,y,color='#fff',size=.4){const c=this.ctx;c.fillStyle=color;c.font=`700 ${size}px system-ui,sans-serif`;c.textAlign='center';c.fillText(text,x,y);}
 drawAgent(a,enemy,local,t){const c=this.ctx,d=AGENT_BY_ID[a.agent],scale=a.scale||1,form=a.transformed?'#62cc67':d.color;this.circle(a.x,a.y+.13,.48*scale,'#0c1c3570');c.save();c.translate(a.x,a.y);if(a.flight>0||a.flying)c.translate(0,-.32-Math.sin(t*5)*.06);c.globalAlpha=a.phase>0?.42:1;this.circle(0,0,.53*scale,null,local?'#ddf898':enemy?'#ff667b':'#61c5ff',.07);c.scale(scale,scale);c.rotate(Math.atan2(a.aimY,a.aimX)+Math.PI/2);const swing=a.attackAnim>0?Math.sin(a.attackAnim*14)*.24:0;
  // Shared rig, agent-specific silhouettes, armor, weapons and hand motion.
  c.lineJoin='round';this.rect(-.2,.23,.2,.36,'#1c2c43');this.rect(.2,.23,.2,.36,'#1c2c43');this.circle(0,-.02,.36,form,'#132536',.065);this.rect(-.39,-.03-swing,.19,.37,form);this.rect(.39,-.03+swing,.19,.37,form);this.circle(0,-.25,.23,form,'#173342',.05);
  if(a.agent==='spidey'){for(const sx of [-1,1]){c.fillStyle='#f2f6ef';c.beginPath();c.moveTo(sx*.04,-.32);c.lineTo(sx*.18,-.38);c.lineTo(sx*.13,-.22);c.fill();}c.strokeStyle='#8a3236';c.lineWidth=.025;c.beginPath();c.moveTo(0,-.48);c.lineTo(0,-.1);c.stroke();}
  if(a.agent==='arc'){this.rect(0,-.28,.3,.18,'#eac56e');this.rect(0,-.3,.27,.035,'#a8f7ff');this.circle(0,.07,.1,'#dcfcff');this.circle(.4,-.2,.09,'#b3ecff');}
  if(a.agent==='bane'){this.circle(-.4,.02,.17,form);this.circle(.4,.02,.17,form);this.rect(0,-.4,.38,.1,'#26383d');this.rect(0,.24,.56,.14,a.transformed?'#655681':'#556b80');}
  if(a.agent==='cap'){if(!a.shieldAway){this.circle(-.43,-.09,.3,'#dc6e78','#f7eee1',.055);this.circle(-.43,-.09,.17,'#5e9bd5','#f7eee1',.055);this.text('★',-.43,0,'#fff',.26);}this.text('A',0,-.25,'#fff',.17);}
  if(a.agent==='thor'){this.rect(-.2,.17,.66,.46,'#9c4d5b');this.rect(.43,-.13,.07,.56,'#c79c69');this.rect(.43,-.44,.36,.22,'#bed9e5');this.rect(0,-.27,.25,.2,'#eac7a2');this.rect(0,-.43,.4,.12,'#dbc777');}
  if(a.agent==='widow'){this.rect(0,-.24,.24,.23,'#edd0bc');this.rect(-.23,-.28,.16,.46,'#ab555e');this.rect(.23,-.28,.16,.46,'#ab555e');if(a.gun>0)this.rect(.42,-.38,.13,.48,'#d1dbe4');this.rect(0,.12,.12,.15,'#eb5368');}
  if(a.agent==='pigeon'){c.strokeStyle='#dbc09a';c.lineWidth=.07;c.beginPath();c.arc(.3,-.18,.52,-1.5,1.5);c.stroke();c.strokeStyle='#e3e6e9';c.lineWidth=.02;c.beginPath();c.moveTo(.34,-.7);c.lineTo(.34,.34);c.stroke();this.rect(0,-.31,.35,.1,'#dbe7ee');}
  if(a.agent==='ant'){this.rect(0,-.3,.3,.25,'#b4c5d4');this.rect(0,-.33,.29,.07,'#e9586f');c.strokeStyle='#e2e8eb';c.lineWidth=.05;for(const sx of [-1,1]){c.beginPath();c.moveTo(sx*.14,-.44);c.lineTo(sx*.25,-.65);c.stroke();}}
  if(a.agent==='hera'){c.strokeStyle='#70d0b2';c.lineWidth=.08;for(const sx of [-1,1]){c.beginPath();c.moveTo(sx*.2,-.33);c.lineTo(sx*.38,-.65);c.lineTo(sx*.1,-.48);c.stroke();}this.rect(.43,-.34,.08,.5,'#d5fff3');}
  if(a.agent==='panther'){this.circle(0,-.25,.23,'#303350','#a48ac4',.05);for(const sx of [-1,1]){c.fillStyle='#303350';c.beginPath();c.moveTo(sx*.22,-.37);c.lineTo(sx*.18,-.59);c.lineTo(sx*.06,-.43);c.fill();this.rect(sx*.1,-.31,.1,.035,'#edf5ff');for(let j=0;j<3;j++)this.rect(sx*.39+j*.04,-.33+(sx>0?swing:-swing),.025,.27,'#d5eaff');}}
  if(a.agent==='vision'){this.rect(0,.18,.59,.4,'#b5b76f');this.circle(0,-.26,.2,'#c76f94');this.circle(0,-.4,.065,'#ffe7a0');this.rect(0,-.28,.27,.04,'#c3fdf9');}
  if(a.shield){c.strokeStyle='#c9ecff';c.lineWidth=.12;c.beginPath();c.arc(0,-.15,.7,Math.PI,TAU);c.stroke();}if(a.spin>0){c.rotate(t*8);this.circle(.8,0,.2,'#bdd8ff');}c.restore();
  const width=Math.max(.9,scale*.8);this.rect(a.x,a.y-.88*scale,width,.13,'#142a3e');c.fillStyle=enemy?'#fc7888':'#76dfb7';c.fillRect(a.x-width/2,a.y-.88*scale-.065,width*clamp(a.hp/a.maxHP,0,1),.13);if(local)this.text('▼',a.x,a.y-1.15*scale,'#dff997',.3);if(a.stun>0)this.text('✦',a.x,a.y-1.2*scale,'#ffda82',.5);
 }
 drawAim(a,info,aim){const c=this.ctx,d=AGENT_BY_ID[a.agent],r=info.key==='attack'?d.range:info.key==='Q'&&a.agent==='cap'?3+6*info.charge:info.key==='Q'&&a.agent==='pigeon'?5+8*info.charge:info.key==='E'&&a.agent==='spidey'?3:info.key==='R'?5.1:9;const dir=aim||{x:a.aimX,y:a.aimY};c.save();c.translate(a.x,a.y);c.rotate(Math.atan2(dir.y,dir.x));c.fillStyle=info.cancel?'#ff789730':'#edffec28';c.strokeStyle=info.cancel?'#ff819a':'#e2fff2';c.lineWidth=.065;c.setLineDash([.22,.12]);if(info.key==='attack'&&['punch','claws','hammer'].includes(d.kind)){c.beginPath();c.moveTo(0,0);c.arc(0,0,r,-.9,.9);c.closePath();c.fill();c.stroke();}else if(a.agent==='spidey'&&info.key==='Q'){this.circle(2+6*info.distance,0,2,'#ffffff20','#e7fff2');c.beginPath();c.moveTo(0,0);c.lineTo(2+6*info.distance,0);c.stroke();}else if((a.agent==='bane'&&info.key==='R')||(['panther','hera','vision'].includes(a.agent)&&info.key==='C'))this.circle(0,0,r,'#ffffff14','#e2fff2');else {c.fillRect(0,-.2,r,.4);c.strokeRect(0,-.2,r,.4);c.beginPath();c.moveTo(r-.45,-.4);c.lineTo(r,0);c.lineTo(r-.45,.4);c.stroke();}c.restore();}
 effect(e,now){const age=now-e.at,c=this.ctx;if(age<0)return;if(e.kind==='hit'&&age<.55){this.text(e.amount,e.x,e.y-.5-age*1.8,'#fff5cb',.42);return;}if(e.kind==='beam'&&age<.12){c.strokeStyle=e.color;c.lineWidth=e.width*2;c.globalAlpha=(1-age/.12)*.75;c.beginPath();c.moveTo(e.x,e.y);c.lineTo(e.ex,e.ey);c.stroke();c.strokeStyle='#fff8eb';c.lineWidth=e.width*.55;c.stroke();c.globalAlpha=1;return;}if(e.kind==='absorb'&&age<.65){for(let i=0;i<7;i++){const t=clamp(age/.65-i*.04,0,1);this.circle(e.x+(e.ex-e.x)*t+Math.sin(t*7+i)*.15,e.y+(e.ey-e.y)*t,.15*(1-t)+.03,'#a0ffdc');}return;}if(e.kind==='lightning'&&age<.35){c.strokeStyle='#caffff';c.lineWidth=.08;c.beginPath();c.moveTo(e.x+.2,e.y-3);c.lineTo(e.x-.18,e.y-1.5);c.lineTo(e.x+.22,e.y-1.6);c.lineTo(e.x,e.y);c.stroke();this.circle(e.x,e.y,age*2,null,'#abecff');return;}if(e.kind==='warning'&&age<1.9){this.circle(e.x,e.y,e.r||2,'#ff8c7118','#ffb08880');return;}if(['circle','ultimate','wall','rewind','revive','recall'].includes(e.kind)&&age<.6){c.globalAlpha=1-age/.6;this.circle(e.x,e.y,(e.r||2)*(.4+age),null,e.color||'#cef6ff',.12);c.globalAlpha=1;}if(['slash','cone'].includes(e.kind)&&age<.3){c.save();c.translate(e.x,e.y);c.rotate(Math.atan2(e.dy,e.dx));c.strokeStyle=e.color;c.lineWidth=e.kind==='cone'?.18:.13;c.globalAlpha=1-age/.3;c.beginPath();c.arc(0,0,e.r*(.55+age),-.85,.85);c.stroke();c.restore();}if(e.kind==='ants'&&age<.85){for(let i=0;i<22;i++){const b=e.targets[i%e.targets.length],t=age/.85;this.circle(e.x+(b.x-e.x)*t+Math.sin(i*2+t*5)*.12,e.y+(b.y-e.y)*t,.055,'#eccc9f');}}
 }
 drawHud(){const s=this.state,a=this.me,d=AGENT_BY_ID[a.agent],phase=s.phase==='ready'?'준비':s.phase==='done'?'경기 종료':s.phase==='result'?'라운드 종료':s.overtime?'연장전':Math.max(0,Math.ceil(s.left))+'초';this.hud.querySelector('.arena-score').textContent=`${MODES[s.options.mode].name}  ·  ${s.score.A} : ${s.score.B}  ·  ${phase}`;
  const ammo=Array.from({length:3},(_,i)=>`<i><em style="width:${a.ammo>i?100:a.ammo===i?a.reloadProgress*100:0}%"></em></i>`).join('');let gauge='';if(a.agent==='vision')gauge=`${a.phase>0?'투명화 '+a.phase.toFixed(1)+'초 · ':''}비행 ${Math.floor(a.fuel)} · 회복 ${Math.floor(a.healFuel)}`;if(a.agent==='arc')gauge='보호막 '+Math.ceil(a.shieldHP);if(a.agent==='panther')gauge='저장 에너지 '+Math.floor(a.energy);if(a.agent==='bane')gauge=a.transformed?'그린 몬스터':'분노 '+Math.floor(a.ult/d.ultCost*100)+'%';if(a.size!=='normal')gauge=(a.size==='large'?'거대화':'축소')+' '+Math.ceil(a.sizeTime)+'초';
  this.hud.querySelector('.arena-hero-hud').innerHTML=`<strong style="color:${d.color}">${a.transformed?'그린 몬스터':d.name}</strong><b>${Math.ceil(a.hp)} <small>/ ${Math.ceil(a.maxHP)} HP</small></b><div class="arena-ammo">${ammo}</div><small>${gauge||d.role}</small>`;
  let notice=a.dead?(a.respawnAt?Math.max(0,Math.ceil(a.respawnAt-s.time))+'초 후 부활':'탈락 · 팀원 관전'):a.cast?a.cast.name+' '+Math.max(0,a.cast.ends-s.time).toFixed(1)+'초':a.stun>0?'기절 '+a.stun.toFixed(1)+'초':s.options.mode==='ball'&&s.ball.holder===a.id?'공 보유 · 공격 버튼으로 패스 / 슛':s.options.mode==='big'&&a.id===s.bossId?'당신이 빅 에이전트입니다. 생존하세요!':'';
  if(s.options.mode==='standard'&&!a.dead){if(s.spike.actor===a.id)notice=(s.spike.state==='planted'?'해체':'설치')+' '+s.spike.progress.toFixed(1)+'초';else if(s.spike.carrier===a.id)notice='폭탄 보유 · 설치 구역에서 F 홀드 / G 내려놓기';else if(s.spike.state==='planted')notice='설치 폭탄 '+Math.ceil(s.spike.left)+'초';}
  if(s.phase==='result'||s.phase==='done')notice=(s.result?.team?s.result.team+'팀 승리':'무승부')+' · '+(s.result?.reason||'');this.hud.querySelector('.arena-notice').textContent=notice;
  const kills=s.events.filter(e=>e.kind==='kill'&&s.time-e.at<2).slice(-3);this.hud.querySelector('.arena-feed').replaceChildren(...kills.map(e=>{const el=document.createElement('div');el.textContent=(s.players.find(a=>a.id===e.source)?.name||'환경')+'  ›  '+(s.players.find(a=>a.id===e.target)?.name||'플레이어');return el;}));
 }
 dispose(){this.hud.remove();}
}
