import {AGENT_BY_ID} from './arena-data.js';
// Offline signaling: no account, public signaling service, STUN or TURN.
// Phones exchange SDP once; subsequent game traffic uses a direct DataChannel.
export const PROTOCOL=8;
export function encodeSignal(kind,description,room,peer){const body={v:PROTOCOL,kind,description,room,peer,expires:Date.now()+15*60e3};return 'AF8.'+btoa(unescape(encodeURIComponent(JSON.stringify(body))));}
export function decodeSignal(text,kind){try{const raw=String(text).trim();if(!raw.startsWith('AF8.')||raw.length>90000)throw 0;const v=JSON.parse(decodeURIComponent(escape(atob(raw.slice(4)))));if(v.v!==PROTOCOL||v.kind!==kind||v.expires<Date.now()||typeof v.room!=='string'||typeof v.peer!=='string'||typeof v.description?.sdp!=='string'||v.description.sdp.length>60000||v.description.type!==(kind==='offer'?'offer':'answer'))throw 0;return v;}catch{throw Error('연결 코드가 올바르지 않거나 15분이 지났습니다. 새 코드를 모두 복사하세요.');}}
const waitICE=pc=>new Promise((resolve,reject)=>{if(pc.iceGatheringState==='complete')return resolve();const timer=setTimeout(()=>{cleanup();reject(Error('연결 주소 수집이 지연됩니다. 같은 Wi-Fi인지 확인하고 다시 만드세요.'));},12000);function cleanup(){clearTimeout(timer);pc.removeEventListener('icegatheringstatechange',change);}function change(){if(pc.iceGatheringState==='complete'){cleanup();resolve();}}pc.addEventListener('icegatheringstatechange',change);});
export class ArenaPeer {
 constructor({room,peer,onmessage=()=>{},onstatus=()=>{}}){if(!globalThis.RTCPeerConnection)throw Error('이 브라우저는 직접 연결을 지원하지 않습니다. Safari/Chrome 최신 버전의 HTTPS 게임 주소에서 열어주세요.');this.room=room;this.peer=peer;this.onmessage=onmessage;this.onstatus=onstatus;this.pc=new RTCPeerConnection({iceServers:[]});this.frames=new Map();this.seq=0;this.closed=false;this.pc.ondatachannel=e=>this.attach(e.channel);this.pc.onconnectionstatechange=()=>{onstatus(this.pc.connectionState);if(this.pc.connectionState==='failed')this.close();};}
 attach(channel){this.channel=channel;channel.onopen=()=>this.onstatus('open');channel.onclose=()=>this.onstatus('closed');channel.onerror=()=>this.onstatus('error');channel.onmessage=e=>{if(typeof e.data!=='string'||e.data.length>20000)return;try{const v=JSON.parse(e.data);if(v.chunk===true){if(!Number.isInteger(v.id)||!Number.isInteger(v.i)||!Number.isInteger(v.n)||v.n<1||v.n>100||v.i<0||v.i>=v.n||typeof v.data!=='string'||v.data.length>10000)return;for(const [id,f] of this.frames)if(Date.now()-f.at>5000)this.frames.delete(id);if(this.frames.size>8)this.frames.delete(this.frames.keys().next().value);let f=this.frames.get(v.id);if(!f){f={n:v.n,parts:new Map(),at:Date.now()};this.frames.set(v.id,f);}if(f.n!==v.n)return;f.parts.set(v.i,v.data);if(f.parts.size===f.n){this.frames.delete(v.id);const packet=JSON.parse(Array.from({length:f.n},(_,i)=>f.parts.get(i)).join(''));this.onmessage(packet);}}else this.onmessage(v);}catch{/* ignore malformed peer packets */}};}
 ensureAddress(){if(!/^a=candidate:/m.test(this.pc.localDescription?.sdp||''))throw Error('이 브라우저가 로컬 연결 주소를 제공하지 않았습니다. 일반 Wi-Fi에 연결하고 브라우저의 로컬 네트워크 접근 권한을 확인하세요. 게스트 Wi-Fi·VPN에서는 연결이 제한될 수 있습니다.');}
 async offer(){this.attach(this.pc.createDataChannel('ability-front',{ordered:true}));await this.pc.setLocalDescription(await this.pc.createOffer());await waitICE(this.pc);this.ensureAddress();return encodeSignal('offer',this.pc.localDescription,this.room,this.peer);}
 async answer(code){const s=decodeSignal(code,'offer');this.room=s.room;this.peer=s.peer;await this.pc.setRemoteDescription(s.description);await this.pc.setLocalDescription(await this.pc.createAnswer());await waitICE(this.pc);this.ensureAddress();return encodeSignal('answer',this.pc.localDescription,this.room,this.peer);}
 async accept(code){const s=decodeSignal(code,'answer');if(s.room!==this.room||s.peer!==this.peer)throw Error('다른 친구의 응답입니다. 이 초대에 대한 응답 코드를 입력하세요.');if(this.pc.signalingState!=='have-local-offer')throw Error('이미 사용한 초대입니다. 새 친구 초대를 만드세요.');await this.pc.setRemoteDescription(s.description);}
 send(packet){if(this.channel?.readyState!=='open')return false;const raw=JSON.stringify(packet);if(raw.length>800000||this.channel.bufferedAmount>1000000)return false;if(raw.length<10000)this.channel.send(raw);else{const id=++this.seq,n=Math.ceil(raw.length/9000);for(let i=0;i<n;i++)this.channel.send(JSON.stringify({chunk:true,id,i,n,data:raw.slice(i*9000,(i+1)*9000)}));}return true;}
 close(){if(this.closed)return;this.closed=true;this.channel?.close();this.pc.close();this.frames.clear();}
}
export class ArenaRoom {
 constructor({host=true,player,options,onchange=()=>{},onsnapshot=()=>{},oninput=()=>{},onstatus=()=>{}}){this.host=host;this.id=host?'host':null;this.code=Math.random().toString(36).slice(2,9);this.player=player;this.options=options;this.onchange=onchange;this.onsnapshot=onsnapshot;this.oninput=oninput;this.onstatus=onstatus;this.players=host?[{...player,id:'host',connected:true}]:[];this.links=new Map();this.started=false;this.closed=false;}
 state(){return {options:this.options,players:this.players,started:this.started,owner:'host'};}
 broadcast(packet){for(const p of this.links.values())p.send(packet);}
 update(){const state=this.state();this.onchange(state);if(this.host)this.broadcast({type:'room',state});}
 async invite(){if(!this.host||this.started)throw Error('대기실 방장만 초대할 수 있습니다.');if(this.links.size>=9)throw Error('최대 10명까지 참가할 수 있습니다.');const id='p'+crypto.randomUUID().slice(0,8),p=this.newLink(id);this.links.set(id,p);try{return {id,code:await p.offer()};}catch(e){p.close();this.links.delete(id);throw e;}}
 async join(code){if(this.host)throw Error('참가 모드에서 입력하세요.');const signal=decodeSignal(code,'offer');this.id=signal.peer;this.code=signal.room;const p=this.newLink(this.id);this.links.set('host',p);try{return await p.answer(code);}catch(e){p.close();this.links.clear();throw e;}}
 async accept(id,code){const p=this.links.get(id);if(!p)throw Error('초대를 먼저 만드세요.');await p.accept(code);}
 newLink(id){return new ArenaPeer({room:this.code,peer:id,onstatus:status=>{this.onstatus(status,id);if(status==='open'){if(this.host)this.links.get(id)?.send({type:'hello',id});else this.links.get('host')?.send({type:'join',player:this.player});}if(['closed','failed'].includes(status)&&!this.closed){if(this.host){const a=this.players.find(a=>a.id===id);if(a)a.connected=false;this.update();}else this.onstatus('host-left',id);}},onmessage:p=>this.message(id,p)});}
 message(id,p){if(!p||typeof p!=='object')return;
  if(this.host){const peer=this.links.get(id);if(!peer)return;if(p.type==='join'&&!this.started&&!this.players.some(a=>a.id===id)){const pl=p.player||{},requested=pl.team==='B'?'B':'A',team=this.players.filter(p=>p.connected&&p.team===requested).length>=5?(requested==='A'?'B':'A'):requested;if(!AGENT_BY_ID[pl.agent]||this.players.filter(p=>p.connected).length>=10)return;this.players.push({id,name:String(pl.name||'친구').slice(0,20),agent:pl.agent,team,connected:true});this.update();}
   if(p.type==='input'&&this.started&&this.players.some(a=>a.id===id&&a.connected)){const now=performance.now();if(now-(peer.windowStart||0)>1000){peer.windowStart=now;peer.count=0;}if((peer.count=(peer.count||0)+1)<=90)this.oninput(id,p.data);}
   if(p.type==='ping')peer.send({type:'pong',at:p.at});
  }else{if(p.type==='room'&&p.state&&Array.isArray(p.state.players)&&p.state.players.length<=10){this.options=p.state.options;this.players=p.state.players;this.started=!!p.state.started;this.onchange(p.state);}if(p.type==='snapshot'&&p.data)this.onsnapshot(p.data);if(p.type==='pong')this.ping=Date.now()-p.at;}
 }
 start(){if(!this.host)return;this.started=true;this.update();}
 input(data){if(this.host)this.oninput('host',data);else this.links.get('host')?.send({type:'input',data});}
 snapshot(data){if(this.host)this.broadcast({type:'snapshot',data});}
 close(){this.closed=true;for(const p of this.links.values())p.close();this.links.clear();}
}
