import {drawSouls} from './souls.js';
import {LocalHistory} from './local-history.js';
import {preventGameShortcuts} from './visuals.js';
import {Expansion} from './expansion.js';
import {ULT_COST,HIT_MULTIPLIERS,hitRegion} from './balance.js';
import {OrbSystem,drawOrbs} from './orbs.js';
import * as T from './three.module.js';
import {AbilitySystem} from './abilities.js';
import {AGENTS,ARMOR} from './agents.js';
import {Body,Physics,V,ChargeBank,overlaps} from './physics.js';
import {World,box,sphere,cylinder,mat,humanoid} from './world.js';
import {AudioFX} from './audio.js';
const $=s=>globalThis.document?.querySelector(s),ui=$('#ui'),canvas=$('#game'),clamp=T.MathUtils.clamp;
const zoneNames=['중앙 · 설치 폭탄 연습','01 · 기동 / 물리 실험','02 · 방어 훈련','03 · 다중 표적','04 · 추적 훈련'];
function zone(p){return p.x<-2&&p.z<-2?1:p.x>2&&p.z<-2?2:p.x<-2&&p.z>2?3:p.x>2&&p.z>2?4:0;}
export class Game extends AbilitySystem {
 constructor(){
  super();
  this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.15;
  this.scene=new T.Scene();this.scene.background=new T.Color('#91b8cb');this.scene.fog=new T.Fog('#91b8cb',40,110);this.camera=new T.PerspectiveCamera(78,innerWidth/innerHeight,.06,160);this.camera.rotation.order='YXZ';this.scene.add(this.camera);
  this.scene.add(new T.HemisphereLight('#c9eafd','#435451',2.5));const sun=new T.DirectionalLight('#fff0d8',3.2);sun.position.set(-14,35,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-33,right:33,top:33,bottom:-33,near:1,far:100});sun.shadow.bias=-.0003;this.scene.add(sun);
  this.physics=new Physics();this.world=new World(this.scene,this.physics);this.audio=new AudioFX();this.player=new Body(V(-3,.9,-3),V(.36,.9,.36));this.player.mass=4;this.physics.movers.push(this.player);this.ray=new T.Raycaster();this.keys={};this.mode='select';this.selected=0;this.tipSkill=0;this.t=0;this.acc=0;this.last=performance.now();this.frame=0;this.effects=[];this.projectiles=[];this.tasks=[];this.traps=[];this.arrows=[];this.kills=0;this.damageTotal=0;this.round=1;this.sensitivity=.002;this.hits=0;this.savedSettings();this.select(0);this.input();this.resize();window.addEventListener('resize',()=>this.resize());requestAnimationFrame(t=>this.loop(t));
 }
 savedSettings(){try{const s=JSON.parse(localStorage.getItem('af-settings')||'{}');this.sensitivity=s.sensitivity||.002;this.audio.volume=s.volume??.35;}catch{}}
 saveSettings(){try{localStorage.setItem('af-settings',JSON.stringify({sensitivity:this.sensitivity,volume:this.audio.volume}));}catch{}}
 restoreDisplay(){this.renderer.setPixelRatio(Math.max(1.5,Math.min(devicePixelRatio||1,2)));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.autoUpdate=true;this.renderer.shadowMap.needsUpdate=true;this.scene.traverse(o=>{if(o.isDirectionalLight){o.castShadow=true;o.shadow.mapSize.set(2048,2048);o.shadow.needsUpdate=true;}});}
 resize(){this.restoreDisplay();this.renderer.setSize(innerWidth,innerHeight);this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();}
 select(i){this.selected=i;this.agent=AGENTS[i];document.documentElement.style.setProperty('--accent',this.agent.color);if(this.preview)this.scene.remove(this.preview);this.preview=humanoid(this.agent.color,this.agent.dark,this.agent.id);this.preview.position.set(0,1.4,0);this.preview.scale.multiplyScalar(1.8);this.scene.add(this.preview);this.selection();}
 selection(){this.mode='select';this.release(false);this.lockExit();if(this.arms)this.arms.visible=false;this.preview.visible=true;const a=this.agent;ui.innerHTML=`<main class="menu"><div class="topline"><div class="brand">능력전선 <span>ABILITY FRONT</span></div><span class="badge">DISPLAY FIX / A</span></div><div class="agent-info"><div class="eyebrow">${a.role} / AGENT 0${this.selected+1}</div><h1>${a.name}</h1><div class="en">${a.en}</div><p class="description">${a.desc}</p><div class="passive">${a.passive}</div><div class="skill-summary">${a.skills.map((s,i)=>`<button data-tip="${i}"><b>${s[0]}</b>${s[1]}</button>`).join('')}</div><p class="skill-detail">${a.skills[this.tipSkill][2]}</p></div><div class="screen-note"><b>THE TRAINING GROUND</b>04개 구역 / 10개 훈련 봇<br>물리 상호작용 · 능력 전투</div><div class="agent-select">${AGENTS.map((a,i)=>`<button class="agent-card ${i===this.selected?'active':''}" data-agent="${i}"><span class="num">0${i+1} / ${a.icon}</span><strong>${a.name}</strong><small>${a.role}</small></button>`).join('')}</div><div class="mobile-notice">PC 키보드와 마우스가 필요한 게임입니다.</div><div class="bottomline"><div class="small">WASD 이동 · 마우스 시점 · Space 점프<br>11요원 싱글플레이 테스트 · 크레딧 무한 · 처치·사망·설치·해체·구슬로 궁극기 충전</div><button id="choose" class="primary">${a.name} 선택 →</button></div></main>`;
  ui.querySelectorAll('[data-agent]').forEach(b=>b.onclick=()=>{this.tipSkill=0;this.select(+b.dataset.agent);});ui.querySelectorAll('[data-tip]').forEach(b=>b.onclick=()=>{this.tipSkill=+b.dataset.tip;$('.skill-detail').textContent=a.skills[this.tipSkill][2];});$('#choose').onclick=()=>{this.audio.start();this.audio.play('buy');this.reset(true);this.shop(true);};
 }
 reset(full=true){
  this.world.reset();for(const a of this.arrows||[])if(a.mesh)this.scene.remove(a.mesh);for(const p of this.projectiles)this.scene.remove(p.mesh);this.projectiles=[];for(const e of this.effects)this.scene.remove(e.mesh);this.effects=[];for(const tr of this.traps)this.scene.remove(tr.mesh);this.traps=[];this.tasks=[];this.arrows=[];this.release(false);this.player.h.set(.36,.9,.36);this.player.p.set(-3,.91,-3);this.player.v.set(0,0,0);this.yaw=-.4;this.pitch=0;this.hp=this.agent.hp;this.maxHP=this.agent.hp;this.armor=this.agent.id==='cap'?15:0;this.armorType=null;this.reserve=0;this.lastDamage=-100;this.bank=new ChargeBank(this.agent);this.equipped=null;this.ultCost=ULT_COST[this.agent.id];this.ultPoints=full?0:(this.ultPoints||0);this.ultReady=this.ultPoints>=this.ultCost;this.orbChannel=null;this.ult=0;this.transformed=false;this.rage=0;this.cast=null;this.flight=0;this.flightKind=null;this.thorLand=0;this.ascend=false;this.webTime=0;this.grapple=null;this.shieldHP=0;this.shieldOn=false;this.shieldAway=false;this.shieldProp=null;this.hammer=null;this.spin=0;this.cool={punch:0,right:0,shield:0};this.charge=null;this.scope=0;this.scopeFree=false;this.bombFree=false;this.gunFree=false;this.specialFree=false;this.hold=null;this.slam=false;this.dash=0;this.arrowType=0;this.arrowMenu=false;this.copySkill=null;this.copyAwait=false;this.attackAnim=0;this.flash=0;this.hitmark=0;this.dead=false;this.spike={state:'idle',progress:0,remaining:45,half:false,beep:0};this.roundTime=100;this.objective=false;this.elapsed=0;this.toastTime=0;if(full){this.kills=0;this.damageTotal=0;this.round=1;}this.resetExpansion();for(const mesh of this.soulMeshes||[])mesh.visible=false;this.buildArms();if(!this.id){this.timeline=new LocalHistory(this);this.orbs=new OrbSystem(this.world,this.physics);drawOrbs(this);}
 }
 buildArms(){if(this.arms)this.camera.remove(this.arms);const a=this.agent;this.arms=new T.Group();this.handGroups=[];this.camera.add(this.arms);for(const side of [-1,1]){const arm=new T.Group();arm.position.set(side*.43,-.4,-.55);arm.rotation.x=-.35;arm.rotation.z=side*-.12;this.arms.add(arm);box(.21,.25,.45,a.dark,0,-.05,.16,arm);box(.25,.23,.25,a.color,0,0,-.08,arm);for(let k=0;k<4;k++)box(.047,.08,.12,'#cedae0',-.087+k*.058,.07,-.2,arm);box(.14,.05,.17,a.color,0,.13,.1,arm).material=mat(a.color,true);this.handGroups.push(arm);}this.heldVisual=new T.Group();this.arms.add(this.heldVisual);this.arms.traverse(m=>{if(m.isMesh){m.castShadow=false;m.receiveShadow=false;m.renderOrder=100;m.material=m.material.clone();m.material.depthTest=false;}});this.updateHeldVisual();}
 updateHeldVisual(){if(!this.heldVisual)return;for(const arm of this.handGroups||[])arm.traverse(m=>{if(!m.isMesh)return;m.userData.baseColor??=m.material.color.clone();m.material.color.copy(this.agent.id==='bane'&&this.transformed?new T.Color('#65cf65'):m.userData.baseColor);});while(this.heldVisual.children.length)this.heldVisual.remove(this.heldVisual.children[0]);const id=this.agent.id,c=this.agent.color,g=this.heldVisual;g.position.set(.35,-.28,-.65);if(this.equipped==='bomb'){sphere(.14,'#bdf1f1',g);}if(this.equipped==='web'){const ring=new T.Mesh(new T.TorusGeometry(.085,.018,6,16),mat('#cbfcff',true));ring.position.set(.03,-.03,-.04);g.add(ring);}if(id==='cap'&&!this.shieldAway){const s=cylinder(.28,.28,.035,c,g);s.rotation.x=Math.PI/2;s.position.set(-.7,.02,.06);cylinder(.18,.18,.04,'#bddeec',s);}if(id==='thor'&&!this.hammer){box(.3,.18,.18,'#c1d3e4',.06,.19,-.02,g);box(.04,.38,.04,'#785952',.06,-.05,-.02,g);}if(this.equipped==='gun'){box(.11,.12,.38,'#303e4c',.01,.04,-.12,g);box(.075,.065,.14,c,.01,.1,-.2,g);}if(id==='pigeon'){const bow=new T.Mesh(new T.TorusGeometry(.32,.023,8,30,Math.PI),mat(c));bow.rotation.z=Math.PI/2;bow.position.x=-.68;g.add(bow);}if(this.shieldOn){const disk=new T.Mesh(new T.CircleGeometry(.6,40),new T.MeshBasicMaterial({color:c,transparent:true,opacity:.18,side:T.DoubleSide,depthTest:false}));disk.position.set(-.35,.14,-.2);g.add(disk);}}
 shop(initial=false){this.release(false);this.scope=0;this.equipped=null;this.mode='shop';this.lockExit();if(this.arms)this.arms.visible=false;const a=this.agent;ui.innerHTML=`<div class="modal-back"><section class="panel"><div class="panel-head"><div><div class="eyebrow">LOADOUT / ${a.en}</div><h2>${a.name} · 스킬 구매</h2><div class="small">테스트 크레딧 <b style="color:#a8e8d9">∞</b> · 궁극기는 구매 불가 / 적 처치로 충전</div></div><button id="back-agent">요원 변경</button></div><div class="shop-grid">${a.skills.slice(0,3).map((s,i)=>`<button class="shop-item" data-buy="${i}" ${!this.bank.canBuy(i)?'disabled':''}><h3>${s[0]} · ${s[1]}</h3><p>${s[2]}</p><div class="cost"><span>${s[4]===0?'기본 제공':s[4]+' 크레딧'}</span><b>${this.bank.count(i)} / ${s[3]}${this.bank.timers[i]>0?` · ${Math.ceil(this.bank.timers[i])}초 후 +1`:""}</b></div></button>`).join('')}</div><div class="section-label">방어구 / 한 종류 장착</div><div class="shop-grid">${ARMOR.map((a,i)=>`<button class="shop-item ${this.armorType===i?'active':''}" data-armor="${i}"><h3>${a.name}</h3><p>${a.desc}</p><div class="cost"><span>${a.price} 크레딧</span><b>${this.armorType===i?'장착됨':'구매'}</b></div></button>`).join('')}</div><div class="bottomline"><button id="buy-all">스킬 최대 구매</button><div class="small">Space 기본 점프 · Shift 천천히 걷기 · Ctrl 앉기<br>B 상점 · H 조작법 · Esc 일시정지</div><button id="deploy" class="primary">${initial?'훈련 시작':'훈련 복귀'} →</button></div></section></div>`;
  ui.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const i=+b.dataset.buy;if(a.skills[i][4]===0)return;if(this.bank.buy(i)){this.audio.play('buy');this.shop(initial);}});ui.querySelectorAll('[data-armor]').forEach(b=>b.onclick=()=>{const i=+b.dataset.armor;this.armorType=i;this.armor=ARMOR[i].value;this.reserve=ARMOR[i].regen;this.audio.play('buy');this.shop(initial);});$('#buy-all').onclick=()=>{for(let i=0;i<3;i++)if(a.skills[i][4]>0)while(this.bank.buy(i)){}this.audio.play('buy');this.shop(initial);};$('#back-agent').onclick=()=>this.selection();$('#deploy').onclick=()=>this.play();
 }
 lockExit(){this.keys={};this.charge=null;this.release(false);this.mouseDown=false;if(document.pointerLockElement)document.exitPointerLock();}
 async play(){this.audio.start();this.restoreDisplay();try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();if(navigator.keyboard?.lock)await navigator.keyboard.lock();}catch{}this.mode='play';this.preview.visible=false;this.arms.visible=true;this.audio.start();this.hud();if(this.touchControls)return;try{const promise=canvas.requestPointerLock();promise?.catch(()=>{this.notify('화면을 클릭해 마우스 시점을 활성화하세요.');});}catch{this.notify('화면을 클릭해 마우스 시점을 활성화하세요.');}}
 pause(help=false){if(this.mode==='select')return;this.release(false);this.mode='pause';this.lockExit();ui.innerHTML=`<div class="modal-back"><section class="panel"><div class="panel-head"><div><div class="eyebrow">TRAINING CONTROL</div><h2>${help?'조작법 · 훈련 설정':'훈련 일시정지'}</h2></div><button id="resume" class="primary">계속하기</button></div><div class="help-grid"><div><b>W A S D</b>이동</div><div><b>마우스</b>시점 / 조준</div><div><b>Space</b>기본 점프 / 아크 활공 중 상승 전환</div><div><b>왼쪽 Shift / Ctrl</b>홀드: 걷기 / 앉기</div><div><b>좌클릭 / 우클릭</b>펀치 / 요원별 보조 공격</div><div><b>Q · E · C · R</b>일반 스킬 / 궁극기</div><div><b>1</b>장착 해제 / 기본 공격</div><div><b>F 홀드</b>설치 폭탄 설치·해체 / 장비 회수</div><div><b>B / H / Esc</b>상점 / 도움말 / 일시정지</div><div><b>V</b>던전 모드 대시</div></div><div class="settings"><label>시점 감도 <input id="sens" type="range" min="0.5" max="4" step="0.1" value="${this.sensitivity*1000}"></label><label>효과음 <input id="volume" type="range" min="0" max="1" step="0.05" value="${this.audio.volume}"></label><label>화면: 첫 사진 기준 <button id="restore-display">화면 복원</button></label><span>DISPLAY FIX A · 3D ${this.renderer.domElement.width}×${this.renderer.domElement.height} · 그림자 ${this.renderer.shadowMap.enabled?'켜짐':'꺼짐'} · AA ${this.renderer.getContext().getContextAttributes()?.antialias?'켜짐':'미지원'}</span></div><div class="section-label">훈련 구역으로 이동</div><div class="zone-buttons">${['중앙','01 기동','02 방어','03 다중 표적','04 추적'].map((s,i)=>`<button data-zone="${i}">${s}</button>`).join('')}</div><div class="bottomline"><button id="reset">훈련 초기화</button><button id="objective">설치 폭탄 연습 ${this.objective?'끄기':'시작'}</button><button id="agents">요원 변경</button></div><p class="small">설치 폭탄 연습: 중앙 A 지점에서 F 4초 설치 → 45초 내 F 7초 해체. 해체는 절반 진행 저장.<br>현재 버전은 혼자 테스트하는 훈련장입니다. 팀 대전·매치메이킹은 포함되지 않습니다.</p></section></div>`;$('#resume').onclick=()=>this.play();$('#sens').oninput=e=>{this.sensitivity=+e.target.value/1000;this.saveSettings();};$('#volume').oninput=e=>{this.audio.volume=+e.target.value;this.saveSettings();this.audio.play('buy');};$('#restore-display').onclick=()=>{this.resize();this.pause(help);};ui.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>{const pts=[[0,0],[-13,-5],[13,-5],[-13,7],[14,7]],p=pts[+b.dataset.zone];this.player.p.set(p[0],.91,p[1]);this.player.v.set(0,0,0);this.yaw=+b.dataset.zone>2?Math.PI:0;this.pitch=0;this.play();});$('#reset').onclick=()=>{this.reset();this.shop(true);};$('#agents').onclick=()=>this.selection();$('#objective').onclick=()=>{this.objective=!this.objective;this.roundTime=100;this.spike={state:'idle',progress:0,remaining:45,half:false,beep:0};this.player.p.set(0,.91,9);this.play();this.notify('A 지점에서 F를 길게 눌러 설치하세요.');};
 }
 hud(){ui.innerHTML=`<canvas id="map" class="minimap" width="220" height="220"></canvas><div class="map-caption">TRAINING COMPLEX / N ↑</div><div class="hud-top"><div id="timer" class="timer">훈련장</div><div id="zone" class="zone-title"></div></div><div id="stats" class="hud-right"></div><div id="scope"></div><div id="crosshair" class="crosshair"></div><div id="target" class="reticle-label"></div><div id="toast"></div><div id="cast" class="castbar"></div><div id="flash"></div><div class="bottom-hud"><div class="health"><div class="name">${this.agent.name}</div><div><strong id="hp">100</strong> <small id="armor">◇ 0</small></div><div class="health-bar"><i id="hpbar"></i></div></div><div id="abilities" class="abilities"></div><div class="hud-hint">B 상점 · H 조작법<br>Space 점프 · Shift 걷기 · Ctrl 앉기<br>1 기본 공격 · Esc 일시정지</div></div>`;this.mapCtx=$('#map').getContext('2d');}
 notify(text,time=2.5){this.toastText=text;this.toastTime=time;}
 input(){
  window.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('blur',()=>{if(this.net)return;this.keys={};if(this.mode==='play')this.pause();});
  document.addEventListener('pointerlockchange',()=>{if(this.net)return;if(!this.touchControls&&!document.pointerLockElement&&this.mode==='play')this.pause();});
  window.addEventListener('keydown',e=>{if(this.net)return;preventGameShortcuts(e);if(this.mode!=='play'){if(e.code==='Escape'&&['pause','shop','arrow'].includes(this.mode)){e.preventDefault();this.play();}if(e.code==='KeyC'&&this.mode==='arrow')this.confirmArrow();return;}if(['Space','ControlLeft','ShiftLeft','KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','KeyC','KeyR','KeyF','KeyB','KeyH','Digit1','KeyV'].includes(e.code))e.preventDefault();this.keys[e.code]=true;if(e.repeat)return;if(e.code==='KeyB'){this.shop();return;}if(e.code==='KeyH'){this.pause(true);return;}if(e.code==='Escape'){this.pause();return;}if(e.code==='Space'){if(!this.busy()&&!this.scope&&this.flight>0&&this.flightKind==='arc'){this.ascend=!this.ascend;}else if(!this.busy(false)&&!this.scope)this.jump(1);}if(e.code==='Digit1'){this.stowCharge();this.equipped=null;this.scope=0;this.shieldOn=false;this.release(false);this.updateHeldVisual();}if(e.code==='KeyV')this.notify('V 대시는 던전 모드에서 사용할 수 있습니다.');if(['KeyQ','KeyE','KeyC','KeyR'].includes(e.code))this.skill(e.code.slice(-1));});
  window.addEventListener('keyup',e=>{if(this.net)return;delete this.keys[e.code];if(this.mode!=='play')return;if(this.charge&&e.code==='Key'+(this.charge.releaseKey||'Q')){this.releaseCharge();}});
  window.addEventListener('mousemove',e=>{if(this.net)return;if(this.mode!=='play'||document.pointerLockElement!==canvas)return;this.yaw-=e.movementX*this.sensitivity;this.pitch=clamp(this.pitch-e.movementY*this.sensitivity,-1.48,1.48);if(this.hold){this.dragAmount+=Math.abs(e.movementX)+Math.abs(e.movementY);this.dragVelocity.lerp(V(-e.movementX*this.sensitivity*220,e.movementY*-this.sensitivity*220,0).applyAxisAngle(V(0,1,0),this.yaw),.5);}});
  canvas.addEventListener('mousedown',e=>{if(this.net)return;preventGameShortcuts(e);if(this.mode!=='play')return;e.preventDefault();if(document.pointerLockElement!==canvas){this.play();return;}if(this.busy())return;this.mouseDown=true;this.attack(e.button);});window.addEventListener('mouseup',e=>{if(this.net)return;this.mouseDown=false;if(e.button===2&&this.hold)this.release(true);});window.addEventListener('wheel',e=>{if(this.net)return;if(this.mode==='arrow'){e.preventDefault();this.arrowSelection=(this.arrowSelection+(e.deltaY>0?1:2))%3;this.renderArrows();}else if(this.hold){e.preventDefault();this.holdDistance=clamp(this.holdDistance+e.deltaY*.005,2,9);}}, {passive:false});
 }
 gainUlt(reason){this.ultPoints=Math.min(this.ultCost,(this.ultPoints||0)+1);this.ultReady=this.ultPoints>=this.ultCost;this.notify(`${reason} · 궁극기 ${this.ultPoints} / ${this.ultCost}`,2);}
 hitDirect(b,amount,point,object,status){this.lastHitRegion=hitRegion(b,point,object);this.hitBot(b,amount*HIT_MULTIPLIERS[this.lastHitRegion],status);}
 tickOrbs(dt){if(!this.orbs)return;this.orbs.tick(dt,[this],a=>a.objective&&Math.hypot(a.player.p.x,a.player.p.z-9)<2.6);drawOrbs(this);}
 busy(blockBeam=true){return (blockBeam&&this.beamTime>0)||!!this.orbChannel||this.dead||!!this.cast||!!(this.objective&&this.keys.KeyF&&this.spike?.progress>0);}
 direction(){return V(0,0,-1).applyEuler(new T.Euler(this.pitch,this.yaw,0,'YXZ'));}
 origin(){return this.camera.position.clone();}
 raycast(origin,dir,distance=60,ignore=null){const ignored=b=>b===ignore||(ignore instanceof Set&&ignore.has(b));this.scene.updateMatrixWorld(true);this.ray.set(origin,dir.clone().normalize());this.ray.far=distance;const objects=[...this.world.colliders.filter(m=>m.userData.body.active),...this.world.objects.filter(b=>b.active&&!ignored(b)).map(b=>b.mesh),...this.world.bots.filter(b=>b.active&&!ignored(b)).map(b=>b.mesh)];const hits=this.ray.intersectObjects(objects,true);return hits.find(h=>h.object.userData.body?.active)||null;}
 visible(b,origin=this.origin()){const delta=b.p.clone().sub(origin);const h=this.raycast(origin,delta,delta.length()+.8);return !h||h.object.userData.body===b;}
 aim(range=60){return this.raycast(this.origin(),this.direction(),range);}
 use(i){const infinite=this.agent.id==='cap'&&this.ult>0||this.agent.id==='pigeon'&&this.ult>0&&i===0;const ok=this.bank.use(i,infinite);if(!ok)this.notify('스킬이 없습니다. B로 상점에서 구매하세요.');return ok;}
 jump(mult=1){if(!this.player.grounded)return;const height=1.15*mult*(this.agent.id==='spidey'&&this.transformed&&mult===1?1.3:1);this.player.v.y=Math.sqrt(2*22*height);this.player.grounded=false;this.audio.play('jump');}
 schedule(delay,fn){this.tasks.push({at:this.t+delay,fn});}
 castFor(name,duration,done,interrupt=false){this.cast={name,total:duration,left:duration,done,interrupt};this.audio.play('charge');}
 transformBane(){if(this.agent.id!=='bane'||this.transformed||this.rage<100)return;this.transformed=true;if(!this.shrinkTime)this.resizeBody(1.15);this.updateHeldVisual();this.maxHP=200;this.hp=Math.min(200,this.hp+100);this.audio.play('ult');this.burst(this.player.p,this.agent.color,35,3);this.notify('그린 몬스터 · 체력 200 / 스킬 활성화',3);}
 hurt(amount,source=null){if(this.phased>0)return;if(this.agent.id==='panther')this.energy+=Math.max(0,amount)*.5;if(this.dead||amount<=0)return;const orig=amount;if(this.spin>0&&source){this.hitBot(source,amount*(this.spinScale||1));this.audio.play('shield');return;}if(this.shieldOn){if(this.shieldKind==='arc'){const absorb=Math.min(this.shieldHP,amount);this.shieldHP-=absorb;amount-=absorb;if(this.shieldHP<=0){this.shieldOn=false;this.updateHeldVisual();}}else if(this.shieldKind==='cap'&&!this.shieldAway){const d=(source?source.p:this.player.p.clone().add(this.direction())).clone().sub(this.player.p).normalize();if(d.dot(this.direction())>.4)amount=Math.max(0,amount-50*(this.capScale||1));}this.audio.play('shield');}
  const absorbed=Math.min(this.armor,amount*(this.armorType===2?1:.66));this.armor-=absorbed;amount-=absorbed;this.hp-=amount;this.lastDamage=this.t;this.flash=.22;this.audio.play('hit',.5);if(this.cast?.interrupt){this.cast=null;this.notify('피격으로 스킬이 중단되었습니다.');}if(this.agent.id==='bane'){this.rage=clamp(this.rage+orig,0,100);this.transformBane();}if(this.hp<=0){this.hp=0;this.dead=true;this.gainUlt("사망");this.release(false);this.cast=null;this.transformed=false;this.notify('훈련 종료 · 잠시 후 상점으로 이동합니다.',2);this.schedule(2,()=>{this.reset(false);this.shop(true);});}
 }
 hitBot(b,amount,status=null,scaled=false){if(!scaled)amount=this.outgoing(amount);if(!b||!b.bot||!b.active)return;const actual=Math.max(0,Math.min(b.hp,amount));b.hp-=amount;this.damageTotal+=actual;this.hitmark=.17;this.audio.play('hit',.55);this.burst(b.p.clone().add(V(0,.5,0)),this.agent.color,8,.6);if(status)Object.assign(b,status);if(this.agent.id==='bane'){this.rage=clamp(this.rage+actual,0,100);this.transformBane();}if(b.hp<=0){b.active=false;b.mesh.visible=false;b.respawn=4;this.kills++;this.spawnSoul(b.p);this.gainUlt('처치');this.audio.play('kill');}}
 area(center,radius,damage,status=null){for(const b of this.world.bots)if(b.active&&b.p.distanceTo(center)<=radius+b.h.x&&this.visible(b,center.clone().add(V(0,.25,0))))this.hitBot(b,damage,status);}
 melee(damage,range=2.25,cool=.45){if(this.sizeMode==='large')damage*=5;if(this.sizeMode==='small')damage=4;if(this.cool.punch>0)return;this.cool.punch=cool;this.punchSide=1-(this.punchSide||0);this.attackAnim=.24;this.audio.play('punch');const h=this.aim(range);if(h?.object.userData.body?.bot)this.hitDirect(h.object.userData.body,damage,h.point,h.object);else if(h){const b=h.object.userData.body;if(b.destructible)this.damageWall(b,this.outgoing(damage));if(b.movable)b.v.add(this.direction().multiplyScalar(4));this.burst(h.point,'#d6d9d4',6,.5);this.audio.play('hit',.4);}}
 beam(start,end,color,width=.025,life=.18,opacity=1){const delta=end.clone().sub(start),m=new T.Mesh(new T.CylinderGeometry(width,width,delta.length(),6),new T.MeshBasicMaterial({color,transparent:true,opacity}));m.position.copy(start).addScaledVector(delta,.5);m.quaternion.setFromUnitVectors(V(0,1,0),delta.normalize());this.scene.add(m);this.effects.push({mesh:m,life,total:life,opacity});}
 burst(p,color,n=12,power=1){n=Math.min(n,12,Math.max(0,100-this.effects.length));for(let i=0;i<n;i++){const m=sphere(.025+Math.random()*.045,color);m.material=new T.MeshBasicMaterial({color,transparent:true});m.position.copy(p);this.scene.add(m);this.effects.push({mesh:m,life:.4+Math.random()*.3,total:.7,v:V(Math.random()-.5,Math.random()-.2,Math.random()-.5).multiplyScalar(power*6)});}}
 ring(p,r,color,life=.6){const m=new T.Mesh(new T.RingGeometry(r*.88,r,48),new T.MeshBasicMaterial({color,transparent:true,opacity:.8,side:T.DoubleSide}));m.rotation.x=-Math.PI/2;m.position.copy(p);m.position.y=Math.max(.06,p.y);this.scene.add(m);this.effects.push({mesh:m,life,total:life,expand:true});}
 projectile(options){const p={p:options.origin?.clone()||this.origin(),v:options.velocity?.clone()||this.direction().multiplyScalar(options.speed||22),life:options.life||5,damage:0,color:this.agent.color,radius:.09,gravity:0,hit:new Set(),...options};p.mesh=sphere(p.radius,p.color);p.mesh.material=mat(p.color,true);p.mesh.position.copy(p.p);this.scene.add(p.mesh);this.projectiles.push(p);return p;}
 shootRay(damage,color,spread=0){let dir=this.direction();if(spread)dir.add(V((Math.random()-.5)*spread,(Math.random()-.5)*spread,(Math.random()-.5)*spread)).normalize();const h=this.raycast(this.origin(),dir,65);const end=h?h.point:this.origin().addScaledVector(dir,65);this.beam(this.origin().add(V(.12,-.12,0)),end,color,.035,.18);if(h?.object.userData.body?.bot)this.hitDirect(h.object.userData.body,damage,h.point,h.object);else if(h){this.damageWall(h.object.userData.body,this.outgoing(damage));this.burst(h.point,color);}this.attackAnim=.2;this.audio.play('beam');}
 impact(p,point,b=null,hit=null){if(this.expansionImpact(p,point,b,hit))return true;
  if(p.kind==='enemy'){if(b===this.player)this.hurt(p.damage*HIT_MULTIPLIERS[hitRegion(this.player,point)],p.source);this.burst(point,'#ffb9a2',5,.5);return true;}
  if(p.kind==='webBomb'){this.ring(point.clone().setY(Math.max(.08,point.y)),2.5*p.scale,'#c4fbf7',1.5*p.scale);for(let i=0;i<10;i++){const end=point.clone().add(V(Math.cos(i*.628)*2.5*p.scale,.04,Math.sin(i*.628)*2.5*p.scale));this.beam(point.clone().add(V(0,.04,0)),end,'#c9fcff',.018,1.5*p.scale);}this.area(point.clone().add(V(0,.9,0)),2.5*p.scale,0,{root:1.5*p.scale});this.audio.play('web');return true;}
  if(b?.bot&&!p.hit.has(b)){this.hitDirect(b,p.damage,point,hit?.object,p.status);p.hit.add(b);}
  if(p.kind==='arrow'){if(b?.bot&&p.arrowType===2){this.area(point,1*p.scale,30*p.scale);this.ring(point.clone().setY(.09),1*p.scale,'#ffc86f');this.audio.play('explode');}p.mesh.position.copy(point);this.arrows.push({p:point.clone(),type:p.arrowType,mesh:p.mesh});p.keepMesh=true;return true;}
  if(p.kind==='shield'||p.kind==='hammer'){
   if(b?.bot){p.p.copy(point).addScaledVector(p.v.clone().normalize(),.002);return false;}
   if(p.kind==='shield'&&p.autoReturn&&!p.returning){p.returning=true;p.hit.clear();p.p.copy(point).addScaledVector(p.v.clone().normalize(),-.35);return false;}
   p.v.set(0,0,0);p.dropped=true;p.returning=false;p.p.copy(point).add(V(0,.12,0));p.dropBody=new Body(p.p,V(.3,.12,.3),p.mesh);if(p.kind==='shield')this.shieldProp=p;return false;
  }
  this.burst(point,p.color,10,.8);if(p.kind==='missile'){this.ring(point.clone().setY(.1),.6,'#ffc886');this.audio.play('explode',.55);}if(p.kind==='net')this.audio.play('electric');return true;
 }
 tickProjectiles(dt){
  for(let i=this.projectiles.length-1;i>=0;i--){const p=this.projectiles[i];let remove=false;
   if(p.dropped&&!p.returning){this.physics.step(p.dropBody,dt,22);p.p.copy(p.dropBody.p);p.mesh.rotation.y+=dt*2;continue;}
   p.life-=dt;
   if((p.kind==='shield'||p.kind==='hammer')&&p.returning){p.dropped=false;const d=this.origin().sub(p.p);if(d.length()<.9){remove=true;if(p.kind==='shield'){this.shieldAway=false;this.shieldProp=null;}else this.hammer=null;this.updateHeldVisual();this.audio.play('shield');}else p.v.copy(d.normalize().multiplyScalar(28));}
   if(p.target?.active&&!p.dropped){const desired=p.target.p.clone().sub(p.p).normalize().multiplyScalar(p.speed||22);p.v.lerp(desired,Math.min(1,dt*8));}
   if(!remove){p.v.y-=p.gravity*dt;const step=p.v.clone().multiplyScalar(dt),length=step.length();const next=p.p.clone().add(step);const h=length>0?this.raycast(p.p,step,length+.02,new Set([p.source,...((['shield','hammer'].includes(p.kind)||p.piercing)?p.hit:[])])):null;let hitBody=h?.object.userData.body,hitPoint=h?.point;
    if(p.enemy){const r=new T.Ray(p.p,step.clone().normalize());const box3=new T.Box3(this.player.p.clone().sub(this.player.h),this.player.p.clone().add(this.player.h));const hit=r.intersectBox(box3,V());if(hit&&hit.distanceTo(p.p)<=length&&(!h||hit.distanceTo(p.p)<h.distance)){hitBody=this.player;hitPoint=hit;
     if(this.spin>0){p.enemy=false;p.kind='reflected';p.target=p.source;p.source=null;p.damage*=this.spinScale||1;p.v.negate();p.p.addScaledVector(p.v.clone().normalize(),.2);this.audio.play('shield');continue;}
    }}
    if(hitPoint){
     const normal=h?.face?.normal.clone().transformDirection(h.object.matrixWorld);
     if(p.kind==='webBomb'&&normal&&normal.y<.5&&!(p.enemyContact&&hitBody?.bot)){p.p.copy(hitPoint).addScaledVector(normal,.025);p.v.reflect(normal).multiplyScalar(.35);}
     else remove=this.impact(p,hitPoint,hitBody,h);
    }else if(next.y<=.08){next.y=.08;remove=this.impact(p,next);}else{p.p.copy(next);}
    if(p.kind==='shield'&&p.autoReturn&&!p.returning&&p.life<4.25){p.returning=true;p.hit.clear();}
    if(p.kind==='hammer'&&!p.returning&&p.life<6.7){p.v.set(0,0,0);p.dropped=true;p.dropBody=new Body(p.p,V(.2,.15,.2),p.mesh);}
    p.mesh.position.copy(p.p);p.mesh.rotation.y+=dt*9;
    if(this.frame%4===0&&['missile','hammer','reflected','net'].includes(p.kind))this.burst(p.p,p.color,1,.1);
   }
   if(p.life<=0&&!p.dropped){if(p.kind==='shield'){this.impact(p,p.p);continue;}if(p.kind==='hammer'){this.impact(p,p.p);continue;}if(p.kind==='arrow')this.impact(p,p.p);remove=true;}
   if(remove){if(!p.keepMesh)this.scene.remove(p.mesh);this.projectiles.splice(i,1);}
  }
 }
 tickPlayer(dt){
  const p=this.player;const crouch=!!this.keys.ControlLeft;const size=this.bodyScale||1;const targetH=(crouch?.56:.9)*size;if(targetH<p.h.y){p.p.y-=p.h.y-targetH;p.h.y=targetH;}else if(targetH>p.h.y){const test={p:p.p.clone().add(V(0,targetH-p.h.y,0)),h:V(.36*size,targetH,.36*size)};if(![...this.physics.solids,...this.world.objects].some(b=>b.active&&overlaps(test,b,.001))){p.p.copy(test.p);p.h.y=targetH;}}
  let speed=5.5*this.agent.speed*(this.moveScale||1);if(this.agent.id==='spidey'&&this.transformed)speed*=1.3;if(this.agent.id==='bane'&&this.transformed)speed*=.7;if(this.slow>0)speed*=.3;if(this.keys.ShiftLeft)speed*=.48;if(crouch)speed*=.48;
  const input=V((this.keys.KeyD?1:0)-(this.keys.KeyA?1:0),0,(this.keys.KeyS?1:0)-(this.keys.KeyW?1:0));if(input.lengthSq()>0)input.normalize().applyAxisAngle(V(0,1,0),this.yaw).multiplyScalar(speed);if(this.busy(false)||this.scope||this.root>0)input.set(0,0,0);
  p.v.x=T.MathUtils.damp(p.v.x,input.x,18,dt);p.v.z=T.MathUtils.damp(p.v.z,input.z,18,dt);
  let gravity=22;
  if(this.flight>0){this.flight=Math.max(0,this.flight-dt);gravity=0;if(this.flightKind==='arc'){p.v.y=T.MathUtils.damp(p.v.y,this.ascend?4*(this.flightScale||1):0,6,dt);}else{p.v.y=this.flight>2*(this.flightScale||1)?3.8:0;}if(p.p.y>12)p.v.y=Math.min(0,p.v.y);if(this.frame%24===0){this.burst(p.p.clone().add(V(0,-.7,0)),'#9fdcfb',3,.6);this.audio.play('flight',.3);}}
  if(this.slam){this.slamTime-=dt;gravity=0;if(this.slamTime>0)p.v.y=5;else p.v.y=-26;}
  if(this.dash>0){this.dash-=dt;p.v.x=this.dashDir.x*25;p.v.z=this.dashDir.z*25;const ahead=p.p.clone().addScaledVector(this.dashDir,1.6);for(const b of this.physics.solids)if(b.active&&b.destructible&&b.p.distanceTo(ahead)<3.5){b.active=false;b.mesh.visible=false;this.burst(b.p,'#c3a27d',30,2);this.audio.play('explode');}for(const b of [...this.world.bots,...this.world.objects])if(b.active&&b.p.distanceTo(ahead)<3&&!this.dashHits.has(b)){this.dashHits.add(b);b.v.addScaledVector(this.dashDir,20*(this.dashScale||1));b.v.y+=5;if(b.bot)this.hitBot(b,80*(this.dashScale||1));}}
  if(this.grapple){this.grapple.time-=dt;const end=this.grapple.target?.active?this.grapple.target.p:this.grapple.point;const d=end.clone().sub(p.p);if(d.length()<1.1||this.grapple.time<=0){this.grapple=null;}else{p.v.copy(d.normalize().multiplyScalar(23*(this.webScale||1)));gravity=0;if(this.frame%3===0)this.beam(this.origin(),end,'#d2fcff',.022,.05);}}
  this.fallPeak=Math.max(this.fallPeak||0,p.p.y-p.h.y);const oldVy=p.v.y,wasGround=p.grounded;this.physics.step(p,dt,gravity);
  if(p.grounded){const fall=(this.fallPeak||0)-(p.p.y-p.h.y);if(!wasGround&&fall>3.5&&!['spidey','arc','thor'].includes(this.agent.id)&&!this.slam)this.hurt(Math.min(100,(fall-3.5)*12));this.fallPeak=p.p.y-p.h.y;}if(p.grounded&&((!wasGround&&oldVy<-2)||(this.slam&&this.slamTime<=0))){this.audio.play('land',Math.min(1,-oldVy/15));this.landAnim=.14;if(this.thorLand&&this.flight<=0){this.area(p.p,.7*this.thorLand,30*this.thorLand);this.ring(p.p.clone().setY(.09),.7*this.thorLand,'#c4cefa');const targets=this.world.bots.filter(b=>b.active&&b.p.distanceTo(p.p)<9&&this.visible(b)).sort((a,b)=>a.p.distanceTo(p.p)-b.p.distanceTo(p.p)).slice(0,3);for(const b of targets)this.lightning(b.p,20*this.thorLand,1);this.thorLand=0;}if(this.slam&&this.slamTime<=0){this.slam=false;this.area(p.p,6.8,50,{stun:3});this.ring(p.p.clone().setY(.08),6.8,'#b0eb94');this.burst(p.p,'#b0eb94',35,3);this.audio.play('explode');}}
  if(p.grounded&&input.lengthSq()>1){this.stepTimer=(this.stepTimer||0)+dt;if(this.stepTimer>(crouch?.55:this.keys.ShiftLeft?.48:.33)){this.audio.play('step',crouch?.15:this.keys.ShiftLeft?.25:.6);this.stepTimer=0;}}
  if(this.agent.id==='spidey'&&!this.dead)this.hp=Math.min(this.maxHP,this.hp+dt*(this.transformed?5:1));
  if(this.armorType===2&&this.reserve>0&&this.t-this.lastDamage>3&&this.armor<25){const regen=Math.min(dt*12.5,this.reserve,25-this.armor);this.armor+=regen;this.reserve-=regen;}
  if(this.hold){if(!this.hold.active||this.webTime<=0){this.release(false);}else{const dir=this.direction(),h=this.raycast(this.origin(),dir,this.holdDistance,this.hold);let distance=this.holdDistance;if(h)distance=Math.max(1.2,h.distance-this.hold.h.x-.12);const goal=this.origin().addScaledVector(dir,distance);const delta=goal.sub(this.hold.p);this.hold.v.copy(delta.multiplyScalar(12).clampLength(0,22));this.hold.v.y+=22*dt;this.dragVelocity.multiplyScalar(Math.exp(-3*dt));if(this.frame%3===0)this.beam(this.origin().add(V(.12,-.2,0)),this.hold.p,'#cef8fc',.02,.06);}}
  if(!this.busy()){if(this.shieldProp&&p.p.distanceTo(this.shieldProp.p)<2){this.scene.remove(this.shieldProp.mesh);this.projectiles=this.projectiles.filter(x=>x!==this.shieldProp);this.shieldProp=null;this.shieldAway=false;this.updateHeldVisual();this.audio.play('shield');}if(this.keys.KeyF&&this.hammer?.dropped&&p.p.distanceTo(this.hammer.p)<2){this.scene.remove(this.hammer.mesh);this.projectiles=this.projectiles.filter(x=>x!==this.hammer);this.hammer=null;this.updateHeldVisual();}}
 }
 tickBots(dt){
  for(const b of this.world.bots){if(!b.active){b.respawn-=dt;if(b.respawn<=0){b.active=true;b.hp=100;b.p.copy(b.home);b.v.set(0,0,0);b.root=b.stun=b.slow=b.dot=0;b.mesh.visible=true;b.sync();}continue;}
   for(const k of ['root','stun','slow','deaf'])b[k]=Math.max(0,b[k]-dt);if(b.dot>0){b.dot-=dt;this.hitBotSilent(b,this.outgoing(b.dotDamage||2)*dt);}
   if(b.shrinkTime>0){b.shrinkTime-=dt;if(b.shrinkTime<=0&&b.originalH){b.h.copy(b.originalH);b.mesh.scale.setScalar(1);}}b.v.x*=Math.exp(-4*dt);b.v.z*=Math.exp(-4*dt);
   const delta=this.player.p.clone().sub(b.p);if(delta.lengthSq()>0)b.mesh.rotation.y=Math.atan2(delta.x,delta.z);
   if(b.mode==='follow'&&b.root<=0&&b.stun<=0){const target=zone(this.player.p)===4?this.player.p:b.home;const d=target.clone().sub(b.p);d.y=0;if(d.length()>(target===b.home?.08:1.3)){d.normalize();const speed=b.slow>0?.96:3.2;let steer=d;for(const angle of [0,.8,-.8,1.5,-1.5]){const v=d.clone().applyAxisAngle(V(0,1,0),angle);const test={p:b.p.clone().addScaledVector(v,.9),h:b.h};if(!this.physics.solids.some(s=>s.active&&overlaps(test,s))){steer=v;break;}}b.v.x+=steer.x*speed*4*dt;b.v.z+=steer.z*speed*4*dt;}}
   if(b.root>0||b.stun>0){b.v.x=0;b.v.z=0;}
   if(b.mode==='attack'&&b.stun<=0&&!this.dead){b.shot-=dt;if(b.shot<=0&&delta.length()<35){b.shot=1.8;const start=b.p.clone().add(V(0,.45,0));const to=this.player.p.clone().sub(start);const h=this.raycast(start,to,to.length(),b);if(!h){this.projectile({kind:'enemy',enemy:true,source:b,origin:start,velocity:to.normalize().multiplyScalar(15),damage:b.shrinkTime>0?10:12,radius:.12,color:'#ff996d',life:4});this.audio.play('beam',.3);b.mesh.userData.arms[1].rotation.x=-1;}}}
   this.physics.step(b,dt);const movement=Math.hypot(b.v.x,b.v.z);const phase=Math.sin(this.t*9)*Math.min(.5,movement*.16);b.mesh.userData.legs[0].rotation.x=phase;b.mesh.userData.legs[1].rotation.x=-phase;b.mesh.userData.arms[0].rotation.x=-phase;b.mesh.userData.arms[1].rotation.x=T.MathUtils.damp(b.mesh.userData.arms[1].rotation.x,phase,5,dt);b.mesh.userData.head.rotation.z=b.stun>0?Math.sin(this.t*14)*.16:0;if((b.root>0||b.stun>0)&&this.frame%20===0)this.ring(b.p.clone().setY(b.p.y-b.h.y+.06),.65,b.stun>0?'#c9b6ff':'#c2fcff',.35);
  }
 }
 hitBotSilent(b,amount){if(!b.active)return;b.hp-=amount;this.damageTotal+=amount;if(b.hp<=0)this.hitBot(b,0);}
 tickObjects(dt){for(const b of this.world.objects){if(!b.active)continue;b.hitTimer=Math.max(0,b.hitTimer-dt);const vel=b.v.clone(),speed=vel.length();if(speed>4&&b.hitTimer<=0){const ray=new T.Ray(b.p,vel.clone().normalize());for(const bot of this.world.bots){if(!bot.active)continue;const half=bot.h.clone().add(b.h);const hit=ray.intersectBox(new T.Box3(bot.p.clone().sub(half),bot.p.clone().add(half)),V());if(hit&&hit.distanceTo(b.p)<=speed*dt+.08){this.hitDirect(bot,clamp(speed*3,10,80),hit);bot.v.addScaledVector(vel,.4);b.hitTimer=.6;break;}}}if(!b.held){b.v.x*=Math.exp(-(b.grounded?5:.5)*dt);b.v.z*=Math.exp(-(b.grounded?5:.5)*dt);}const was=b.grounded;this.physics.step(b,dt);if(!was&&b.grounded&&vel.y<-3)this.audio.play('land',.3);}}
 tickTraps(dt){for(let i=this.traps.length-1;i>=0;i--){const tr=this.traps[i];if(tr.timer<0){if(this.world.bots.some(b=>b.active&&Math.hypot(b.p.x-tr.p.x,b.p.z-tr.p.z)<.6*tr.scale+b.h.x&&Math.abs(b.p.y-b.h.y-tr.p.y)<1)){tr.timer=.7;this.audio.play('beep');}}else{tr.timer-=dt;tr.beep-=dt;tr.mesh.material=mat(Math.floor(this.t*20)%2?'#ffca78':'#df6389',true);if(tr.beep<=0){this.audio.play('beep',.4);tr.beep=.1;}if(tr.timer<=0){this.area(tr.p.clone().add(V(0,.5,0)),1.2*tr.scale,50*tr.scale);this.ring(tr.p,1.2*tr.scale,'#ffd280');this.burst(tr.p,'#ffbd8a',25,2);this.audio.play('explode');this.scene.remove(tr.mesh);this.traps.splice(i,1);}}}}
 tickSpike(dt){if(!this.objective)return;const s=this.spike,near=Math.hypot(this.player.p.x,this.player.p.z-9)<2.6&&this.player.grounded;const act=this.keys.KeyF&&near&&!this.cast&&!this.dead;if(s.state==='idle'){this.roundTime-=dt;if(act){s.progress+=dt;if(s.progress>=4){s.state='planted';this.gainUlt('설치');s.progress=0;this.notify('설치 폭탄 설치 완료 · 45초 내 해체하세요.');this.audio.play('ult',.6);}}else s.progress=0;if(this.roundTime<=0)this.finishRound('시간 종료 · 방어 성공');}
  else if(s.state==='planted'){s.remaining-=dt;s.beep-=dt;if(s.beep<=0){this.audio.play('beep',.6);s.beep=s.remaining>20?1:s.remaining>10?.5:.2;this.ring(V(0,.08,9),1.1,'#ffd392',.25);}if(act){s.progress+=dt;if(s.progress>=3.5)s.half=true;if(s.progress>=7){this.gainUlt('해체');this.finishRound('설치 폭탄 해체 성공');return;}}else s.progress=s.half?3.5:0;if(s.remaining<=0){this.ring(V(0,.1,9),8,'#9beae8',1.5);this.audio.play('explode');this.finishRound('설치 폭탄 작동 · 공격 성공');}}
 }
 finishRound(text){this.objective=false;this.spike.state='done';this.spike.progress=0;this.notify(text,4);if(this.agent.id==='spidey')this.transformed=false;this.ult=0;this.round++;this.orbs=new OrbSystem(this.world,this.physics);}
 tick(dt){this.t+=dt;this.elapsed+=dt;this.frame++;if(this.agent.id==='ant'&&!this.id)this.timeline?.tick(dt);this.tickExpansion?.(dt);for(const task of [...this.tasks])if(task.at<=this.t){this.tasks.splice(this.tasks.indexOf(task),1);task.fn();if(this.mode!=='play')return;}
  this.bank.tick(dt);for(const k in this.cool)this.cool[k]=Math.max(0,this.cool[k]-dt);for(const k of ['ult','spin','toastTime','attackAnim','hitmark','flash','landAnim'])this[k]=Math.max(0,(this[k]||0)-dt);
  if(this.webTime>0){this.webTime=Math.max(0,this.webTime-dt);if(this.webTime===0){this.release(false);if(this.equipped==='web')this.equipped=null;this.grapple=null;this.updateHeldVisual();}}
  if(this.cast){this.cast.left-=dt;if(this.cast.left<=0){const done=this.cast.done;this.cast=null;done();}}
  this.tickOrbs(dt);if(!this.dead)this.tickPlayer(dt);this.tickBots(dt);this.tickObjects(dt);this.tickProjectiles(dt);this.tickTraps(dt);this.tickSpike(dt);
  if(this.agent.id==='thor'&&this.ult>0){this.ultTick-=dt;if(this.ultTick<=0){this.ultTick=.38;const targets=this.world.bots.filter(b=>b.active&&this.visible(b));if(targets.length){const b=targets[this.ultIndex++%targets.length];this.projectile({kind:'missile',target:b,speed:32,damage:25,radius:.16,color:'#c2b8ff',life:3});this.lightning(b.p,20,.7);}}}
  if(this.spin>0&&this.frame%8===0){const p=this.player.p.clone().add(V(Math.sin(this.t*15)*.85,.2,Math.cos(this.t*15)*.85));this.beam(this.player.p,p,'#add9ff',.12,.08);}
  for(let i=this.effects.length-1;i>=0;i--){const e=this.effects[i];e.life-=dt;if(e.life<=0){this.scene.remove(e.mesh);e.mesh.geometry.dispose();if(e.mesh.material.transparent)e.mesh.material.dispose();this.effects.splice(i,1);continue;}if(e.v){e.v.y-=9*dt;e.mesh.position.addScaledVector(e.v,dt);}if(e.expand)e.mesh.scale.multiplyScalar(1+dt*.8);if(e.mesh.material.transparent)e.mesh.material.opacity=(e.opacity??1)*Math.min(1,e.life/e.total);}
 }
 updateCamera(){if(this.mode==='select'){this.camera.position.set(4.1,2.75,6.3);this.camera.lookAt(-1.8,1.95,0);this.preview.rotation.y=.35+Math.sin(performance.now()*.00025)*.12;this.preview.position.y=1.98+Math.sin(performance.now()*.0018)*.018;this.preview.userData.arms.forEach((a,i)=>a.rotation.z=Math.sin(performance.now()*.001+i)*.025);return;}if(!this.player)return;this.camera.rotation.set(this.pitch||0,this.yaw||0,0,'YXZ');this.camera.position.copy(this.player.p).add(V(0,this.player.h.y-.18*(this.bodyScale||1),0));const speed=Math.hypot(this.player.v.x,this.player.v.z),walk=this.player.grounded&&speed>.3?Math.sin(this.t*11)*.012*speed/5:0;this.camera.position.y+=walk;if(this.arms){this.arms.position.y=walk-(this.landAnim||0)*.15;this.arms.position.x=Math.cos(this.t*5)*.005;this.arms.scale.setScalar(this.agent.id==='bane'&&this.transformed?1.25:1);this.handGroups.forEach((a,i)=>{const punch=Math.sin((this.attackAnim/.24)*Math.PI);a.position.z=-.55-(i===this.punchSide?Math.max(0,punch)*.48:0);a.rotation.x=-.35+(this.charge?Math.min(1,(this.t-this.charge.start))*.35:0);if(this.soulAbsorb>0){const pull=Math.sin(Math.PI*(1-this.soulAbsorb/.7));a.rotation.x-=pull*.9;a.position.z-=pull*.25;}});if(this.flight>0){this.handGroups[0].rotation.z=-.4;this.handGroups[1].rotation.z=.4;}else{this.handGroups[0].rotation.z=.12;this.handGroups[1].rotation.z=-.12;}}
 }
 updateHud(){if(this.mode!=='play'||!$('#hp'))return;$('#hp').textContent=Math.ceil(this.hp);$('#armor').textContent=`◇ ${Math.ceil(this.armor)}${this.reserve>0?' +'+Math.ceil(this.reserve):''}`;$('#hpbar').style.width=clamp(this.hp/this.maxHP*100,0,100)+'%';$('#zone').textContent=zoneNames[zone(this.player.p)];$('#timer').textContent=this.objective?this.spike.state==='planted'?this.spike.remaining.toFixed(1):`${Math.floor(this.roundTime/60)}:${String(Math.floor(this.roundTime%60)).padStart(2,'0')}`:'FREE PRACTICE';$('#stats').innerHTML=`${this.agent.id==='panther'?'<strong>저장 에너지 '+Math.floor(this.energy)+'</strong><br>':''}${this.agent.id==='vision'?'<strong>'+(this.phased>0?'투명화 '+this.phased.toFixed(1)+'초 · ':this.beamTime>0?'마인드 빔 '+this.beamTime.toFixed(1)+'초 · 이동 가능 · ':'')+'비행 '+Math.floor(this.flightGauge)+' / 회복 '+Math.floor(this.healGauge)+'</strong><br>':''}${this.agent.id==='ant'?'<strong>'+({large:'대형',small:'소형'}[this.sizeMode]||'일반')+' · '+Math.ceil(this.sizeTime)+'초</strong><br>':''}<strong>${this.kills} 처치</strong> / ${Math.round(this.damageTotal)} 피해<br>라운드 ${String(this.round).padStart(2,'0')} · 크레딧 ∞${this.agent.id==='bane'?`<br>분노 ${Math.floor(this.rage)} / 100`:''}${this.flight>0?`<br>활공 ${this.flight.toFixed(1)}s`:''}${this.webTime>0?`<br>거미줄 ${this.webTime.toFixed(1)}s`:''}${this.shieldOn?`<br>보호막 ${this.shieldKind==='arc'?Math.ceil(this.shieldHP):'정면 방어'}`:''}`;
  $('#abilities').innerHTML=this.agent.skills.map((s,i)=>{const count=i===3?(this.ultReady?1:0):this.bank.count(i);const equipped=i===0&&['bomb','gun'].includes(this.equipped)||i===1&&(this.shieldOn||this.flight>0)||i===2&&(this.webTime>0||this.scope||this.spin>0);const cooldown=i<3?this.bank.timers[i]:this.ult;return `<div class="ability ${equipped?'selected':''} ${count===0&&!equipped&&i!==3?'empty':''} ${i===3&&this.ultReady?'ready':''}"><kbd>${s[0]}</kbd><span>${i===3?(this.ultReady?'준비':this.transformed?'변신':this.ult>0?this.ult.toFixed(0)+'s':this.ultPoints+' / '+this.ultCost):count+' / '+s[3]}</span><strong>${s[1]}</strong>${cooldown>0?`<em>${Math.ceil(cooldown)}초</em>`:''}</div>`;}).join('');
  $('#crosshair').className='crosshair'+(this.hitmark>0?' hit':'');$('#scope').className=this.scope?'scope':'';$('#flash').className=this.flash>0?'damage-flash':'';$('#toast').innerHTML=this.toastTime>0?`<div class="toast">${this.toastText}</div>`:'';
  let bar='',amount=0;if(this.orbChannel){bar='궁극기 구슬 획득';amount=this.orbChannel.progress/2;}else if(this.cast){bar=this.cast.name;amount=1-this.cast.left/this.cast.total;}else if(this.charge){bar=this.charge.kind==='arrow'?'화살 차징':'방패 차징';amount=clamp((this.t-this.charge.start)*(this.ult>0&&this.agent.id==='pigeon'?2:1)/1.4,0,1);}else if(this.objective&&this.spike.progress>0){bar=this.spike.state==='idle'?'설치 폭탄 설치':'설치 폭탄 해체';amount=this.spike.progress/(this.spike.state==='idle'?4:7);}$('#cast').innerHTML=bar?`${bar} · ${Math.floor(amount*100)}%<div><i style="width:${amount*100}%"></i></div>`:'';
  if(this.frame%6===0){const h=this.aim(40),b=h?.object.userData.body;$('#target').textContent=this.orbs?.orbs.some(o=>o.active&&Math.hypot(o.x-this.player.p.x,o.z-this.player.p.z)<1.7)?'F 2초 홀드 · 궁극기 구슬 +1':b?.bot?`훈련 봇 · ${Math.ceil(b.hp)} HP${b.stun>0?' · 기절':b.root>0?' · 구속':''}`:b?.movable?'이동 가능한 물체':b?.destructible?'파괴 가능한 엄폐물':this.hold?'우클릭을 놓아 던지기 · 휠로 거리 조절':'';}
  const c=this.mapCtx;if(c){c.clearRect(0,0,220,220);c.fillStyle='#0d2330';c.fillRect(0,0,220,220);const conv=n=>(n+28)/56*220;c.strokeStyle='#5e828a';c.strokeRect(4,4,212,212);c.strokeStyle='#65879166';c.beginPath();c.moveTo(110,4);c.lineTo(110,216);c.moveTo(4,110);c.lineTo(216,110);c.stroke();for(const b of this.physics.solids){if(!b.active)continue;c.fillStyle=b.destructible?'#957d58':'#496671';c.fillRect(conv(b.p.x-b.h.x),conv(b.p.z-b.h.z),b.h.x*2/56*220,b.h.z*2/56*220);}for(const b of this.world.objects){c.fillStyle='#d8a86a';c.fillRect(conv(b.p.x)-2,conv(b.p.z)-2,4,4);}for(const b of this.world.bots){if(!b.active)continue;c.fillStyle=b.mode==='attack'?'#ff8b7b':b.mode==='follow'?'#bba3ee':'#85dad4';c.beginPath();c.arc(conv(b.p.x),conv(b.p.z),3,0,Math.PI*2);c.fill();}for(const o of this.orbs?.orbs||[])if(o.active){c.fillStyle='#cdb4ff';c.beginPath();c.arc(conv(o.x),conv(o.z),4,0,Math.PI*2);c.fill();}c.font='12px sans-serif';c.fillStyle='#a3bfc7';c.fillText('01',12,20);c.fillText('02',195,20);c.fillText('03',12,208);c.fillText('04',195,208);c.save();c.translate(conv(this.player.p.x),conv(this.player.p.z));c.rotate(this.yaw);c.fillStyle='#fff6bf';c.beginPath();c.moveTo(0,-7);c.lineTo(-4,5);c.lineTo(0,3);c.lineTo(4,5);c.closePath();c.fill();c.restore();}
 }
 loop(now){const dt=Math.min((now-this.last)/1000,.08);this.last=now;if(this.net){this.net.frame(dt);this.renderer.render(this.scene,this.camera);requestAnimationFrame(t=>this.loop(t));return;}if(this.mode==='play'){this.acc+=dt;let steps=0;while(this.acc>=1/120&&steps++<10){this.tick(1/120);this.acc-=1/120;if(this.mode!=='play')break;}}else this.acc=0;drawSouls(this,this.dead?[]:(this.soulOrbs||[]).map(o=>({...o,to:this.origin().toArray(),clock:this.t})));this.updateCamera();if(this.mode==='play'&&this.frame%6===0)this.updateHud();this.renderer.render(this.scene,this.camera);requestAnimationFrame(t=>this.loop(t));}
}
Object.assign(Game.prototype,Expansion);
