import {V,Body} from './physics.js';
import {ARMOR} from './agents.js';

const clone=(v,seen=new Map())=>{if(v===null||typeof v!=='object')return v;if(v.player instanceof Body&&v.agent)return v;if(v instanceof Body||v.isObject3D||v.isMaterial||v.isBufferGeometry)return v;if(v.isVector3||v.isQuaternion||v.isEuler)return v.clone();if(seen.has(v))return seen.get(v);if(v instanceof Set)return new Set([...v].map(x=>clone(x,seen)));if(v instanceof Map)return new Map([...v].map(([k,x])=>[k,clone(x,seen)]));const out=Array.isArray(v)?[]:{};seen.set(v,out);for(const k of Object.keys(v))out[k]=clone(v[k],seen);return out;};
const skip=new Set(['sim','physics','scene','world','player','camera','ray','agent','audio','bank','effects','keys','connected','id','team','lastInput']);
const actorState=a=>{const out={};for(const k of Object.keys(a))if(!skip.has(k)&&typeof a[k]!=='function')out[k]=a[k];return clone(out);};
const bodyState=b=>({body:b,p:b.p.clone(),h:b.h.clone(),v:b.v.clone(),active:b.active,hp:b.hp,held:b.held,phased:b.phased,grounded:b.grounded,root:b.root,stun:b.stun,slow:b.slow,deaf:b.deaf,dot:b.dot,dotDamage:b.dotDamage,antSlow:b.antSlow,antSlowTime:b.antSlowTime,decay:b.decay,contacts:clone(b.contacts),hitTimer:b.hitTimer,owner:b.owner});
export const RoundSystem={
 initRoundSystems(){this.corpses=[];this.dynamicWalls=[];this.history=[];this.roundDeaths=0;this.revision=0;this.lossStreak={A:0,B:0};this.economy=this.world.map.size===5&&!this.room.options.unlimited;},
 roundBeforeReset(){this.history=[];this.pendingRewind=null;this.corpses=[];this.roundDeaths=0;for(const w of this.dynamicWalls){w.active=false;this.scene.remove(w.mesh);}this.physics.solids=this.physics.solids.filter(b=>!b.thorn);this.dynamicWalls=[];this.savedLoadouts=new Map([...this.actors.values()].filter(a=>a.bank).map(a=>[a.id,{base:[...a.bank.base],extra:[...a.bank.extra],armor:a.dead?0:a.armor,armorType:a.armorType,reserve:a.dead?0:a.reserve}]));},
 economyReset(a){const half=this.rules.round===1||this.rules.round===Math.ceil(this.room.options.rounds/2)+1;const old=this.savedLoadouts?.get(a.id);if(this.economy){if(half){a.credits=800;this.lossStreak={A:0,B:0};}else a.credits??=800;a.armor=half?(a.agent.id==='cap'?15:0):(old?.armor||0);a.armorType=half?null:old?.armorType;a.reserve=half?0:old?.reserve||0;for(let i=0;i<3;i++){a.bank.base[i]=a.agent.skills[i][5];a.bank.extra[i]=half?0:Math.min(old?.extra[i]||0,a.agent.skills[i][3]-a.bank.base[i]);a.bank.timers[i]=0;}}else{a.bank.fill();a.armor=50;a.armorType=1;}if(a.agent.id==='vision'&&[...this.actors.values()].some(b=>b.team===a.team&&['thor','cap'].includes(b.agent.id)))a.hp=a.maxHP=120;},
 buy(a,item,index){if(this.rules.phase!=='buy'||a.dead)return false;let price=0;if(item==='armor'){if(!ARMOR[index])return false;price=ARMOR[index].price;}else{if(!Number.isInteger(item)||item<0||item>2||!a.bank.canBuy(item))return false;price=a.agent.skills[item][4];}if(this.economy&&a.credits<price){a.notify('크레딧이 부족합니다.');return false;}if(item==='armor'){a.armorType=index;a.armor=ARMOR[index].value;a.reserve=ARMOR[index].regen;}else a.bank.buy(item);if(this.economy)a.credits-=price;return true;},
 reward(a,n){if(this.economy)a.credits=Math.min(9000,(a.credits||0)+n);},
 awardPlant(id){const team=this.actors.get(id)?.team;for(const a of this.actors.values())if(a.team===team)this.reward(a,300);},
 settleEconomy(){if(!this.economy)return;const win=this.rules.result?.team;if(!win)return;for(const team of ['A','B'])this.lossStreak[team]=team===win?Math.max(0,this.lossStreak[team]-1):Math.min(3,this.lossStreak[team]+1);for(const a of this.actors.values()){const saved=!a.dead&&a.team!==win&&((this.rules.role(a.team)==='attack'&&this.rules.spike.state==='idle')||(this.rules.role(a.team)==='defend'&&this.rules.spike.remaining<=0));this.reward(a,a.team===win?3000:saved?1000:1900+500*Math.max(0,this.lossStreak[a.team]-1));}},
 dropBomb(a){const s=this.rules.spike;if(s.carrier!==a.id)return;s.dropped={x:a.player.p.x,y:a.player.p.y-a.player.h.y,z:a.player.p.z};s.carrier=null;s.actor=null;s.progress=0;s.lastCarrier=a.id;s.dropTimer=1;a.bombSelected=false;},
 recordDeath(a,source){this.roundDeaths++;a.ancestor=false;a.ancestorUnlocked=false;a.visionFlight=false;a.phased=0;a.player.phased=false;a.orbChannel=null;this.dropBomb(a);this.corpses=this.corpses.filter(c=>c.id!==a.id);this.corpses.push({id:a.id,team:a.team,agent:a.agent.id,name:this.room.players.get(a.id)?.name||'플레이어',pos:[a.player.p.x,a.player.p.y-a.player.h.y+.04,a.player.p.z],at:this.time});if(source?.actor&&source.actor.team!==a.team){source.actor.spawnSoul(a.player.p);this.reward(source.actor,200);}this.event({kind:'death',target:a.id,source:source?.actor?.id||null,at:this.time});},
 revive(id){const a=this.actors.get(id),c=this.corpses.find(c=>c.id===id);if(!a||!c||!a.dead||!a.connected)return false;a.dead=false;a.hp=50;a.armor=0;a.player.active=true;a.player.phased=false;a.bodyScale=1;a.player.h.set(.36,.9,.36);a.player.p.set(c.pos[0],c.pos[1]+.9,c.pos[2]);a.player.v.set(0,0,0);a.player.hp=50;a.player.mesh.visible=true;a.player.sync();a.revivePower=2;a.root=a.stun=a.dot=0;a.player.root=a.player.stun=a.player.dot=0;a.keys={};this.corpses=this.corpses.filter(x=>x.id!==id);this.event({kind:'revive',target:id,at:this.time});return true;},
 captureHistory(){if(![...this.actors.values()].some(a=>a.agent.id==='ant'))return;if(this.time<(this.historyAt||0))return;this.historyAt=this.time+.1;const actors=[...this.actors.values()].map(a=>({id:a.id,state:actorState(a),bank:clone({base:a.bank.base,extra:a.bank.extra,timers:a.bank.timers}),token:a.grabToken}));this.history.push({at:this.time,actors,bodies:[...this.physics.solids,...this.physics.movers].map(bodyState),spike:clone(this.rules.spike),roundTime:this.rules.time,corpses:clone(this.corpses),orbs:clone(this.orbs.orbs),roundDeaths:this.roundDeaths,walls:[...this.dynamicWalls]});while(this.history[0]?.at<this.time-5.3)this.history.shift();},
 requestRewind(a){this.pendingRewind=a.id;},
 applyRewind(){const id=this.pendingRewind;if(!id)return;this.pendingRewind=null;const h=this.history.filter(h=>h.at<=this.time-5).at(-1);if(!h)return;for(const saved of h.actors){const a=this.actors.get(saved.id);if(!a)continue;for(const p of [...a.projectiles,...a.traps,...a.arrows])if(p.mesh)this.scene.remove(p.mesh);for(const e of a.effects)this.scene.remove(e.mesh);const state=clone(saved.state);Object.assign(a,state);a.grabToken=saved.token;a.effects=[];Object.assign(a.bank,clone(saved.bank));a.keys={};a.lastInput=this.time;for(const p of [...a.projectiles,...a.traps,...a.arrows])if(p.mesh)this.scene.add(p.mesh);if(a.id===id){a.ultPoints=0;a.ultReady=false;a.cast=null;}if(!a.connected){a.dead=true;a.player.active=false;}}
  for(const b of this.dynamicWalls)if(!h.walls.includes(b)){b.active=false;this.scene.remove(b.mesh);}this.dynamicWalls=[...h.walls];this.physics.solids=this.physics.solids.filter(b=>!b.thorn||h.walls.includes(b));for(const b of h.walls)if(!this.physics.solids.includes(b))this.physics.solids.push(b);
  for(const saved of h.bodies){const b=saved.body;for(const [key,v] of Object.entries(saved))if(key!=='body')b[key]=clone(v);if(b.actor&&!b.actor.connected)b.active=false;if(b.mesh){this.scene.add(b.mesh);b.mesh.visible=b.active;}b.sync();}
  this.rules.spike=clone(h.spike);this.rules.time=h.roundTime;this.corpses=clone(h.corpses);this.orbs.orbs=clone(h.orbs);this.roundDeaths=h.roundDeaths;this.history=[];this.historyAt=this.time;this.revision++;this.event({kind:'rewind',at:this.time});
 }
};
