const KEY='af-3d-touch-layout';
export function installTouchEditor(control){let saved;try{saved=JSON.parse(localStorage.getItem(KEY)||'{}');}catch{saved={};}const elements=[...control.root.querySelectorAll('button,.touch-stick')];elements.forEach((el,i)=>el.dataset.layoutId=String(i));
 const apply=()=>{for(const el of elements){const p=saved[el.dataset.layoutId];if(!p)continue;Object.assign(el.style,{position:'fixed',left:(p.x*100)+'%',top:(p.y*100)+'%',width:p.size+'px',height:p.size+'px',transform:'translate(-50%,-50%)',margin:0});}};apply();
 control.editHUD=()=>{control.clear();control.editingHUD=true;control.root.hidden=false;const old=control.active;control.active=()=>true;const panel=document.createElement('div');panel.className='arena-hud-editor touch-editor-panel';panel.innerHTML='<strong>3D 터치 UI 편집</strong><span>버튼을 선택하고 끌어 이동하세요.</span><input aria-label="버튼 크기" type="range" min="38" max="160" value="64"><button data-save>저장</button><button data-reset>초기화</button>';document.body.append(panel);const abort=new AbortController();let drag=null,selected=null;
  control.root.addEventListener('pointerdown',e=>{const el=e.target.closest('[data-layout-id]');if(!el)return;e.preventDefault();e.stopImmediatePropagation();selected=el;const r=el.getBoundingClientRect();saved[el.dataset.layoutId]??={x:(r.left+r.width/2)/innerWidth,y:(r.top+r.height/2)/innerHeight,size:r.width};panel.querySelector('input').value=saved[el.dataset.layoutId].size;drag=e.pointerId;el.setPointerCapture(drag);},{capture:true,signal:abort.signal});
  control.root.addEventListener('pointermove',e=>{if(drag!==e.pointerId||!selected)return;e.preventDefault();e.stopImmediatePropagation();const p=saved[selected.dataset.layoutId];p.x=Math.min(.96,Math.max(.04,e.clientX/innerWidth));p.y=Math.min(.92,Math.max(.08,e.clientY/innerHeight));apply();},{capture:true,signal:abort.signal});control.root.addEventListener('pointerup',()=>drag=null,{signal:abort.signal});panel.querySelector('input').oninput=e=>{if(selected){saved[selected.dataset.layoutId].size=+e.target.value;apply();}};
  const close=()=>{abort.abort();control.active=old;control.editingHUD=false;panel.remove();control.clear();};panel.querySelector('[data-save]').onclick=()=>{localStorage.setItem(KEY,JSON.stringify(saved));close();};panel.querySelector('[data-reset]').onclick=()=>{saved={};localStorage.removeItem(KEY);for(const el of elements)el.removeAttribute('style');close();};
 };
}
