import * as T from './three.module.js';
import {V} from './physics.js';
export function decorateAgent(mesh,friendly){
 const rim=new T.Color(friendly?'#279cff':'#ff384c');mesh.traverse(m=>{if(!m.isMesh)return;m.material=m.material.clone();m.userData.originalColor=m.material.color?.clone();m.material.onBeforeCompile=shader=>{shader.uniforms.teamRim={value:rim};shader.fragmentShader='uniform vec3 teamRim;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <opaque_fragment>','float edgeGlow=pow(1.0-abs(dot(normalize(normal),normalize(vViewPosition))),2.5);totalEmissiveRadiance+=teamRim*edgeGlow*2.5;outgoingLight+=teamRim*edgeGlow*2.5;\n#include <opaque_fragment>');};m.material.customProgramCacheKey=()=> 'team-rim-v1';m.castShadow=false;});
}
export function poseAgent(mesh,p,time){const size=p.bodyScale||1;mesh.scale.set(size,p.height/.9,size);mesh.rotation.y=p.yaw+Math.PI;const swing=Math.sin(time*10)*Math.min(.55,Math.hypot(...[p.vel[0],p.vel[2]])*.1);mesh.userData.legs.forEach((l,i)=>l.rotation.x=i?swing:-swing);mesh.userData.arms.forEach((arm,i)=>{arm.rotation.x=p.attackAnim>0&&i===(p.punchSide||0)?-1.5:p.flight>0?-.8:p.cast?-.65:i?-swing:swing;arm.rotation.z=p.agent==='bane'&&p.transformed?(i?.3:-.3):0;});
 const state=p.agent==='bane'&&p.transformed?'monster':'normal';if(mesh.userData.form!==state){mesh.userData.form=state;mesh.traverse(m=>{if(!m.isMesh||!m.material.color)return;m.material.color.copy(state==='monster'?new T.Color('#78bc57'):m.userData.originalColor||m.material.color);});if(p.agent==='bane')mesh.userData.torso.scale.set(state==='monster'?1.1:1,state==='monster'?1.05:1,state==='monster'?1.1:1);}
}
export function expansionVisuals(net,s){const g=net.g;net.extraVisuals??=[];for(const [key,positions,size,color] of [['ants',s.ants||[],[.06,.035,.09],'#e59e74'],['fire',s.fire||[],[.7,.08,.7],'#c58cff']]){net.instances??={};let batch=net.instances[key];if(!batch){batch=new T.InstancedMesh(new T.BoxGeometry(...size),new T.MeshBasicMaterial({color}),1000);batch.frustumCulled=false;net.instances[key]=batch;g.scene.add(batch);}batch.count=Math.min(1000,positions.length);const matrix=new T.Matrix4();for(let i=0;i<batch.count;i++){matrix.makeTranslation(...positions[i]);batch.setMatrixAt(i,matrix);}batch.instanceMatrix.needsUpdate=true;}const items=[...(s.projectiles||[]).filter(p=>p.dropped&&p.kind==='shield').map(p=>({pos:[p.pos[0],p.pos[1]+.7,p.pos[2]],size:[.045,1.4,.045],color:'#8edaff'})),...(net.me?.wallPreview?net.me.wallPlan.map(p=>({pos:[p.x,p.y,p.z],size:[1.5,4,.5],color:'#88efb6',angle:-net.me.wallAngle})):[])];items.slice(0,760).forEach((p,i)=>{let m=net.extraVisuals[i];if(!m){m=new T.Mesh(new T.BoxGeometry(1,1,1),new T.MeshBasicMaterial({transparent:true,opacity:.7}));net.extraVisuals.push(m);g.scene.add(m);}m.visible=true;m.position.fromArray(p.pos);m.scale.fromArray(p.size);m.rotation.y=p.angle||0;m.material.color.set(p.color);});for(let i=items.length;i<net.extraVisuals.length;i++)net.extraVisuals[i].visible=false;
 net.wallMeshes??=[];(s.walls||[]).forEach((w,i)=>{let m=net.wallMeshes[i];if(!m){m=new T.Mesh(new T.BoxGeometry(1.5,4,.5),new T.MeshStandardMaterial({color:'#61947a',roughness:.85}));net.wallMeshes.push(m);g.scene.add(m);}m.visible=w.active;m.position.fromArray(w.pos);m.rotation.y=w.angle;});for(let i=(s.walls||[]).length;i<net.wallMeshes.length;i++)net.wallMeshes[i].visible=false;
 net.corpseMeshes??=new Map();const ids=new Set();for(const c of s.corpses||[]){ids.add(c.id);let m=net.corpseMeshes.get(c.id);if(!m){m=new T.Mesh(new T.CylinderGeometry(.38,.38,.06,20),new T.MeshStandardMaterial({color:c.team===net.me.team?'#438fee':'#da5566',emissive:c.team===net.me.team?'#153b72':'#641622',emissiveIntensity:.8}));const canvas=document.createElement('canvas');canvas.width=512;canvas.height=64;const ctx=canvas.getContext('2d');ctx.fillStyle='#071525dd';ctx.fillRect(0,0,512,64);ctx.fillStyle='#fff';ctx.font='24px sans-serif';ctx.textAlign='center';ctx.fillText(c.label,256,42);const sprite=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(canvas),depthTest:true}));sprite.scale.set(2.8,.35,1);sprite.position.y=.65;m.add(sprite);net.corpseMeshes.set(c.id,m);g.scene.add(m);}m.visible=true;m.position.fromArray(c.pos);}for(const [id,m] of net.corpseMeshes)if(!ids.has(id))m.visible=false;
}
export function preventGameShortcuts(e){if(e.target?.isContentEditable||['INPUT','TEXTAREA','SELECT'].includes(e.target?.tagName))return;if(e.ctrlKey&&['KeyW','KeyR','KeyS','KeyD','KeyF','KeyG','KeyQ','KeyE','KeyC','KeyB','KeyH','KeyV','Space','Digit1','Digit4','Tab'].includes(e.code))e.preventDefault();}
